In [2]:
import alpaca
import keyring
import pandas as pd

In [3]:
service = "api.alpaca.markets"
API_KEY = keyring.get_password(service, "ALPACA_API_KEY")
SECRET_KEY = keyring.get_password(service, "ALPACA_SECRET_KEY")

print(f"API Key: {API_KEY[:3]}")
print(f"API Secret: {SECRET_KEY[:3]}")

API Key: AKK
API Secret: Bjz

In [4]:
#import pandas as pd
from alpaca.data.historical.screener import ScreenerClient
from alpaca.data.requests import MostActivesRequest
from alpaca.data.enums import MostActivesBy

# 1. Initialize the Screener Client
# Replace with your actual Alpaca API keys or environment variables
#API_KEY = api_key
#SECRET_KEY = api_secret

screener_client = ScreenerClient(api_key=API_KEY, secret_key=SECRET_KEY)

# 2. Configure your liquidity query
# You can sort 'by' MostActivesBy.VOLUME or MostActivesBy.TRADES
request_params = MostActivesRequest(
    by=MostActivesBy.VOLUME,
    top=100  # Supports fetching between 1 and 100 assets
)

# 3. Fetch data from Alpaca
try:
    most_active_data = screener_client.get_most_actives(request_params)
    
    # 4. Parse the results into a Pandas DataFrame for easier viewing
    liquidity_list = []
    for asset in most_active_data.most_actives:
        liquidity_list.append({
            "Symbol": asset.symbol,
            "Daily Volume": asset.volume,
            "Trade Count": asset.trade_count
        })
        
    df = pd.DataFrame(liquidity_list)
    print(f"Top Liquidity Assets (Last Updated: {most_active_data.last_updated})")
    print(df.to_string(index=False))

except Exception as e:
    print(f"An error occurred: {e}")

Top Liquidity Assets (Last Updated: 2026-10-12 15:16:00.205992+00:00)
Symbol  Daily Volume  Trade Count
  MNDR   135499548.0    1050372.0
  VCIG    86176294.0     266642.0
  FRGT    79177470.0     158435.0
  YMAT    65298251.0     563502.0
  CLWT    61248960.0     382833.0
  SXTC    48959143.0      58205.0
  SPCX    36932081.0     486404.0
  SDST    35703478.0      32329.0
  SOXS    35175476.0     211541.0
  SKYA    33498781.0     169805.0
  LNKS    32666136.0     185683.0
   IPW    31531612.0      96271.0
  GIXI    30851141.0     403583.0
  INTC    30740986.0     299826.0
  WBUY    30536518.0      95059.0
  SOXL    29685382.0     568603.0
  NVDA    29508872.0     880286.0
   NOK    29442063.0      45788.0
  SNXX    28986331.0      92803.0
  ONDS    27960432.0      54831.0
   DKI    27927662.0      51536.0
   NVD    26914453.0       7420.0
  BITO    26734212.0      12794.0
  IREN    25762701.0     231223.0
  MSTZ    23586356.0      14473.0
  DAIC    22936711.0     181854.0
  PLUG    22246714.0      46573.0
  RIME    20931255.0      27326.0
  KORU    19625391.0     146499.0
  DRAM    19482013.0     144943.0
  MEDS    18754998.0     176856.0
  GRAB    17751338.0      35475.0
  SOFI    16371429.0      69652.0
  TQQQ    16200701.0     128156.0
  IONQ    16190661.0     269222.0
     T    16013868.0      60162.0
    NU    15734869.0      42587.0
  NCPL    15318168.0      74163.0
   WFF    15136144.0     323011.0
  TSLG    15055125.0       4823.0
  CBRG    15021969.0      11485.0
   AAL    14267526.0      24572.0
  SNAP    14212654.0      40349.0
   SMR    13918364.0      57263.0
  TSLL    12873941.0      26502.0
  DVLT    12806542.0       9227.0
  SQQQ    12737450.0      37537.0
  ASTS    12100306.0     128434.0
  SPCH    12017598.0      25871.0
    VZ    11701364.0      71827.0
   MUU    11444224.0      89637.0
   CCC    11415191.0      32153.0
  MMED    11251206.0      56096.0
  PLTR    11181021.0     206327.0
  SOAR    11149169.0      12171.0
  OPEN    11029246.0      22911.0
  RXRX    10974235.0      26309.0
  IBIT    10896327.0      31017.0
    MU    10742442.0     450534.0
   RWM    10380249.0       3312.0
  SNDQ    10200909.0      36650.0
   OLB    10077444.0      17978.0
  SMCI    10058121.0      76390.0
   NIO    10050649.0      18336.0
  GPUS     9900907.0       8449.0
   CMG     9793556.0      65407.0
  MRVL     9573293.0     164317.0
  EOSE     9497042.0      27325.0
  RZLV     9400515.0      12428.0
   QID     9332532.0       5120.0
  PLTD     9149381.0       3318.0
  BMNR     9092856.0      55178.0
  ACHR     8964168.0      20710.0
   MDT     8851609.0      70770.0
  CTVA     8846962.0      46396.0
  CRWV     8838443.0      94791.0
  AAPL     8821578.0     278792.0
  AAOX     8816002.0      46523.0
   EWZ     8805779.0      27720.0
   XLE     8736524.0      47379.0
     F     8727193.0      35514.0
   QQQ     8697033.0     251879.0
  HUMA     8626481.0       5093.0
  AGNC     8570029.0      26068.0
  META     8413012.0     224180.0
  TSLA     8219223.0     315961.0
   NKE     8214473.0      53385.0
  AMZN     8117316.0     158680.0
   BAC     8115272.0      63962.0
  MARA     8036766.0      28087.0
  STLA     8008214.0      11409.0
   RKT     7996734.0      23285.0
  KWEB     7967607.0      16904.0
   UNG     7951373.0       6894.0
  ORCL     7947239.0     116520.0
   BMY     7889866.0      71249.0
   BBD     7812701.0      11636.0
  SSPC     7779719.0       9761.0
  QTEX     7773595.0      24371.0
  CIFR     7700440.0      33941.0

In [5]:
df

   Symbol  Daily Volume  Trade Count
0    MNDR   135499548.0    1050372.0
1    VCIG    86176294.0     266642.0
2    FRGT    79177470.0     158435.0
3    YMAT    65298251.0     563502.0
4    CLWT    61248960.0     382833.0
..    ...           ...          ...
95    BMY     7889866.0      71249.0
96    BBD     7812701.0      11636.0
97   SSPC     7779719.0       9761.0
98   QTEX     7773595.0      24371.0
99   CIFR     7700440.0      33941.0

[100 rows x 3 columns]

In [6]:
#write most liquid assets to file in documentation folder
#df.to_csv("../../documentation/most_liquid_assets_2026-10-11.csv", index=False)

In [20]:
liquid_assets = df['Symbol'].to_list()
liquid_assets.sort()
liquid_assets

['AAL',
 'AAOX',
 'AAPL',
 'ACHR',
 'AGNC',
 'AMZN',
 'ASTS',
 'BAC',
 'BBD',
 'BITO',
 'BMNR',
 'BMY',
 'CBRG',
 'CCC',
 'CIFR',
 'CLWT',
 'CMG',
 'CRWV',
 'CTVA',
 'DAIC',
 'DKI',
 'DRAM',
 'DVLT',
 'EOSE',
 'EWZ',
 'F',
 'FRGT',
 'GIXI',
 'GPUS',
 'GRAB',
 'HUMA',
 'IBIT',
 'INTC',
 'IONQ',
 'IPW',
 'IREN',
 'KORU',
 'KWEB',
 'LNKS',
 'MARA',
 'MDT',
 'MEDS',
 'META',
 'MMED',
 'MNDR',
 'MRVL',
 'MSTZ',
 'MU',
 'MUU',
 'NCPL',
 'NIO',
 'NKE',
 'NOK',
 'NU',
 'NVD',
 'NVDA',
 'OLB',
 'ONDS',
 'OPEN',
 'ORCL',
 'PLTD',
 'PLTR',
 'PLUG',
 'QID',
 'QQQ',
 'QTEX',
 'RIME',
 'RKT',
 'RWM',
 'RXRX',
 'RZLV',
 'SDST',
 'SKYA',
 'SMCI',
 'SMR',
 'SNAP',
 'SNDQ',
 'SNXX',
 'SOAR',
 'SOFI',
 'SOXL',
 'SOXS',
 'SPCH',
 'SPCX',
 'SQQQ',
 'SSPC',
 'STLA',
 'SXTC',
 'T',
 'TQQQ',
 'TSLA',
 'TSLG',
 'TSLL',
 'UNG',
 'VCIG',
 'VZ',
 'WBUY',
 'WFF',
 'XLE',
 'YMAT']

In [9]:
assets_us_equity = pd.read_json('../../tests/assets_us_equity.json')
assets_us_equity

,id,class,exchange,symbol,name,status,tradable,marginable,maintenance_margin_requirement,margin_requirement_long,margin_requirement_short,shortable,easy_to_borrow,borrow_status,fractionable,attributes
0,74e36620-d3b4-4fc1-9694-8b00d518e037,us_equity,OTC,IMAQW,INTERNATIONAL MEDIA ACQUISITION CORP Warrant ...,active,False,False,100,100,100,False,False,hard_to_borrow,False,[]
1,37d1d98b-e0a3-4d24-ba18-18a6f195f98a,us_equity,OTC,IMAQR,INTERNATIONAL MEDIA ACQUISITION CORP Rights,active,False,False,100,100,100,False,False,hard_to_borrow,False,[]
2,65e4a66c-005d-4444-91e4-0533df1415bf,us_equity,OTC,LGMK,"LogicMark, Inc. Common Stock",active,False,False,100,100,100,False,False,hard_to_borrow,False,[]
3,84186725-7658-4269-a9b5-47868cecc88d,us_equity,OTC,PNSTQ,"Pinstripes Holdings, Inc. Class A Common Stock",active,False,False,100,100,100,False,False,hard_to_borrow,False,[]
4,42dfd0ef-6991-44c7-9857-d6d09604d4b9,us_equity,OTC,CLVSQ,"Clovis Oncology, Inc. Common Stock",active,False,False,100,100,100,False,False,hard_to_borrow,False,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14190,edb6073c-3db3-4a63-a7fd-c9da326d6228,us_equity,BATS,SPLS,PIMCO US Stocks PLUS Active Bond Exchange-Trad...,active,True,True,30,30,30,False,False,hard_to_borrow,False,[overnight_tradable]
14191,55e1856c-2bc5-4c9c-a15d-8d941f57cc93,us_equity,NASDAQ,SPKLW,Spark I Acquisition Corp. Warrant,active,True,True,100,100,100,False,False,hard_to_borrow,False,[overnight_halted]
14192,fac6037d-a616-479e-9af1-39093979244d,us_equity,NYSE,CMTG,"Claros Mortgage Trust, Inc.",active,True,True,100,100,100,True,True,easy_to_borrow,True,"[fractional_eh_enabled, has_options, overnight..."
14193,d81921e6-ead8-4523-aab4-4a380fc033a0,us_equity,NASDAQ,SPKLU,Spark I Acquisition Corp. Unit,active,True,True,75,75,75,False,False,hard_to_borrow,False,[overnight_halted]
14194,d003ec42-a014-4e80-a1eb-ccf344f8007e,us_equity,NASDAQ,SPKL,Spark I Acquisition Corp. Class A Ordinary Share,active,True,True,75,75,75,False,False,hard_to_borrow,True,"[fractional_eh_enabled, overnight_halted]"

In [11]:
assets_us_equity.info()

<class 'pandas.DataFrame'>
RangeIndex: 14195 entries, 0 to 14194
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              14195 non-null  str
 1   class                           14195 non-null  str
 2   exchange                        14195 non-null  str
 3   symbol                          14195 non-null  str
 4   name                            14195 non-null  str
 5   status                          14195 non-null  str
 6   tradable                        14195 non-null  bool
 7   marginable                      14195 non-null  bool
 8   maintenance_margin_requirement  14195 non-null  int64
 9   margin_requirement_long         14195 non-null  int64
 10  margin_requirement_short        14195 non-null  int64
 11  shortable                       14195 non-null  bool
 12  easy_to_borrow                  14195 non-null  bool
 13  borrow_status                   14195 non-null  str
 14  fractionable                    14195 non-null  bool
 15  attributes                      14195 non-null  object
dtypes: bool(5), int64(3), object(1), str(7)
memory usage: 2.8+ MB

In [22]:
assets_us_equity_tsfs = assets_us_equity[(assets_us_equity['tradable'] == True) & (assets_us_equity['status'] == 'active') & (assets_us_equity['fractionable'] == True) & (assets_us_equity['shortable'] == True)].drop(columns=['tradable', 'status', 'fractionable', 'shortable'])

In [23]:
assets_us_equity_tsfs

,id,class,exchange,symbol,name,marginable,maintenance_margin_requirement,margin_requirement_long,margin_requirement_short,easy_to_borrow,borrow_status,attributes
884,95a3e392-291a-44ff-826a-7baaa4907d77,us_equity,AMEX,CMT,"Core Molding Technologies, Inc.",True,75,75,75,True,easy_to_borrow,"[fractional_eh_enabled, overnight_tradable]"
891,9c028c5a-14bd-4d11-b388-5cca57ee9ef3,us_equity,NYSE,BTE,Baytex Energy Corp.,True,50,50,50,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."
892,cfae5876-5fd7-43ec-8daf-d583ef094a8b,us_equity,NYSE,CMS,CMS Energy Corporation,True,30,30,30,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."
893,3d42e2e7-f7b6-4ed1-8221-46eb2b923b8a,us_equity,NYSE,BLSH,Bullish,True,100,100,100,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."
894,15c86db7-bc00-4cad-a92a-15a57e4144dd,us_equity,NYSE,CMRE,Costamare Inc.,True,50,50,50,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."
...,...,...,...,...,...,...,...,...,...,...,...,...
14144,44ddf865-1d4c-443a-b0a4-d8304a703836,us_equity,NYSE,GRMN,Garmin Ltd,True,40,40,40,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."
14146,16fac120-b725-4908-ae7b-e33b7fd3c86b,us_equity,NASDAQ,BZ,KANZHUN LIMITED American Depository Shares,True,30,30,30,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."
14160,b65e1cd5-0682-4eb3-844c-8901712b9cc4,us_equity,NYSE,BWA,BorgWarner Inc.,True,30,30,30,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."
14178,eea32630-0fda-496b-89df-cb9558bff431,us_equity,NYSE,SPNT,SiriusPoint Ltd.,True,50,50,50,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."
14192,fac6037d-a616-479e-9af1-39093979244d,us_equity,NYSE,CMTG,"Claros Mortgage Trust, Inc.",True,100,100,100,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."

In [37]:
assets_us_equity_tsfs[assets_us_equity_tsfs['symbol'] == 'BRK.B']

,id,class,exchange,symbol,name,marginable,maintenance_margin_requirement,margin_requirement_long,margin_requirement_short,easy_to_borrow,borrow_status,attributes
7197,71bb19d0-6c5f-4881-9552-33224badd810,us_equity,NYSE,BRK.B,BERKSHIRE HATHAWAY Class B,True,75,75,75,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."

In [28]:
assets_us_equity

,id,class,exchange,symbol,name,status,tradable,marginable,maintenance_margin_requirement,margin_requirement_long,margin_requirement_short,shortable,easy_to_borrow,borrow_status,fractionable,attributes
0,74e36620-d3b4-4fc1-9694-8b00d518e037,us_equity,OTC,IMAQW,INTERNATIONAL MEDIA ACQUISITION CORP Warrant ...,active,False,False,100,100,100,False,False,hard_to_borrow,False,[]
1,37d1d98b-e0a3-4d24-ba18-18a6f195f98a,us_equity,OTC,IMAQR,INTERNATIONAL MEDIA ACQUISITION CORP Rights,active,False,False,100,100,100,False,False,hard_to_borrow,False,[]
2,65e4a66c-005d-4444-91e4-0533df1415bf,us_equity,OTC,LGMK,"LogicMark, Inc. Common Stock",active,False,False,100,100,100,False,False,hard_to_borrow,False,[]
3,84186725-7658-4269-a9b5-47868cecc88d,us_equity,OTC,PNSTQ,"Pinstripes Holdings, Inc. Class A Common Stock",active,False,False,100,100,100,False,False,hard_to_borrow,False,[]
4,42dfd0ef-6991-44c7-9857-d6d09604d4b9,us_equity,OTC,CLVSQ,"Clovis Oncology, Inc. Common Stock",active,False,False,100,100,100,False,False,hard_to_borrow,False,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14190,edb6073c-3db3-4a63-a7fd-c9da326d6228,us_equity,BATS,SPLS,PIMCO US Stocks PLUS Active Bond Exchange-Trad...,active,True,True,30,30,30,False,False,hard_to_borrow,False,[overnight_tradable]
14191,55e1856c-2bc5-4c9c-a15d-8d941f57cc93,us_equity,NASDAQ,SPKLW,Spark I Acquisition Corp. Warrant,active,True,True,100,100,100,False,False,hard_to_borrow,False,[overnight_halted]
14192,fac6037d-a616-479e-9af1-39093979244d,us_equity,NYSE,CMTG,"Claros Mortgage Trust, Inc.",active,True,True,100,100,100,True,True,easy_to_borrow,True,"[fractional_eh_enabled, has_options, overnight..."
14193,d81921e6-ead8-4523-aab4-4a380fc033a0,us_equity,NASDAQ,SPKLU,Spark I Acquisition Corp. Unit,active,True,True,75,75,75,False,False,hard_to_borrow,False,[overnight_halted]
14194,d003ec42-a014-4e80-a1eb-ccf344f8007e,us_equity,NASDAQ,SPKL,Spark I Acquisition Corp. Class A Ordinary Share,active,True,True,75,75,75,False,False,hard_to_borrow,True,"[fractional_eh_enabled, overnight_halted]"

In [32]:
#now let's use the pgsql class from pgsql.py to write these dataframes to our sql db
from db.pgsql import pgsql
from sqlalchemy import text

In [34]:
db = pgsql()
db.set_table_name('assets_us_equity')
db.set_pdf(assets_us_equity)
db.write_pdf_to_sql()

True

In [35]:
assets_us_equity_tsfs

,id,class,exchange,symbol,name,marginable,maintenance_margin_requirement,margin_requirement_long,margin_requirement_short,easy_to_borrow,borrow_status,attributes
884,95a3e392-291a-44ff-826a-7baaa4907d77,us_equity,AMEX,CMT,"Core Molding Technologies, Inc.",True,75,75,75,True,easy_to_borrow,"[fractional_eh_enabled, overnight_tradable]"
891,9c028c5a-14bd-4d11-b388-5cca57ee9ef3,us_equity,NYSE,BTE,Baytex Energy Corp.,True,50,50,50,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."
892,cfae5876-5fd7-43ec-8daf-d583ef094a8b,us_equity,NYSE,CMS,CMS Energy Corporation,True,30,30,30,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."
893,3d42e2e7-f7b6-4ed1-8221-46eb2b923b8a,us_equity,NYSE,BLSH,Bullish,True,100,100,100,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."
894,15c86db7-bc00-4cad-a92a-15a57e4144dd,us_equity,NYSE,CMRE,Costamare Inc.,True,50,50,50,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."
...,...,...,...,...,...,...,...,...,...,...,...,...
14144,44ddf865-1d4c-443a-b0a4-d8304a703836,us_equity,NYSE,GRMN,Garmin Ltd,True,40,40,40,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."
14146,16fac120-b725-4908-ae7b-e33b7fd3c86b,us_equity,NASDAQ,BZ,KANZHUN LIMITED American Depository Shares,True,30,30,30,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."
14160,b65e1cd5-0682-4eb3-844c-8901712b9cc4,us_equity,NYSE,BWA,BorgWarner Inc.,True,30,30,30,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."
14178,eea32630-0fda-496b-89df-cb9558bff431,us_equity,NYSE,SPNT,SiriusPoint Ltd.,True,50,50,50,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."
14192,fac6037d-a616-479e-9af1-39093979244d,us_equity,NYSE,CMTG,"Claros Mortgage Trust, Inc.",True,100,100,100,True,easy_to_borrow,"[fractional_eh_enabled, has_options, overnight..."

In [36]:
from datetime import datetime
from alpaca.data.historical import StockHistoricalDataClient
from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame

# Initialize the historical data client (use your API keys)
client = StockHistoricalDataClient(API_KEY, SECRET_KEY)

# Build the request
request_params_aapl = StockBarsRequest(
    symbol_or_symbols=["AAPL"],
    timeframe=TimeFrame.Day,
    start=datetime(2026, 9, 11),
    end=datetime(2026, 10, 11)
)

# Fetch data and convert to a pandas DataFrame
bars_aapl = client.get_stock_bars(request_params_aapl)
df_aapl = bars_aapl.df
print(df_aapl)

                                     open      high       low   close  \
symbol timestamp
AAPL   2026-09-11 04:00:00+00:00  327.450  336.2200  326.3000  332.27
       2026-09-14 04:00:00+00:00  334.790  335.5000  331.3400  333.08
       2026-09-15 04:00:00+00:00  330.135  331.7800  328.3500  331.34
       2026-09-16 04:00:00+00:00  332.530  335.4800  330.7000  332.41
       2026-09-17 04:00:00+00:00  334.770  338.3400  330.1833  337.00
       2026-09-18 04:00:00+00:00  337.905  338.4900  332.5300  336.13
       2026-09-21 04:00:00+00:00  335.280  339.6400  333.0500  338.98
       2026-09-22 04:00:00+00:00  340.135  345.3400  338.7500  339.75
       2026-09-23 04:00:00+00:00  341.075  341.8000  335.5000  337.02
       2026-09-24 04:00:00+00:00  336.720  338.9100  334.3000  335.92
       2026-09-25 04:00:00+00:00  336.040  341.6700  334.5300  341.07
       2026-09-28 04:00:00+00:00  340.370  342.9880  338.0400  338.40
       2026-09-29 04:00:00+00:00  336.965  337.0850  328.7000  329.40
       2026-09-30 04:00:00+00:00  330.800  339.5000  330.1401  333.02
       2026-10-01 04:00:00+00:00  330.000  332.4816  325.8100  330.32
       2026-10-02 04:00:00+00:00  333.260  334.5400  330.6100  333.69
       2026-10-05 04:00:00+00:00  332.815  336.2100  331.6500  332.89
       2026-10-06 04:00:00+00:00  332.280  334.3800  330.6200  333.63
       2026-10-07 04:00:00+00:00  336.960  338.6700  332.7800  336.67
       2026-10-08 04:00:00+00:00  336.815  341.5700  335.9000  340.42
       2026-10-09 04:00:00+00:00  331.695  338.6100  330.7000  336.64

                                      volume  trade_count        vwap
symbol timestamp
AAPL   2026-09-11 04:00:00+00:00  50906905.0    1001537.0  333.144960
       2026-09-14 04:00:00+00:00  39524847.0    1031536.0  333.684654
       2026-09-15 04:00:00+00:00  31916076.0     688356.0  330.541211
       2026-09-16 04:00:00+00:00  36100868.0     637488.0  332.945495
       2026-09-17 04:00:00+00:00  36817969.0     668736.0  335.467058
       2026-09-18 04:00:00+00:00  86726840.0     681554.0  336.096486
       2026-09-21 04:00:00+00:00  35165402.0     717707.0  337.856484
       2026-09-22 04:00:00+00:00  40814327.0     701605.0  341.063608
       2026-09-23 04:00:00+00:00  31795692.0     636292.0  337.346040
       2026-09-24 04:00:00+00:00  24871878.0     524733.0  336.682496
       2026-09-25 04:00:00+00:00  30134469.0     605912.0  339.285622
       2026-09-28 04:00:00+00:00  32989725.0     710434.0  339.919521
       2026-09-29 04:00:00+00:00  38641024.0     764858.0  331.015191
       2026-09-30 04:00:00+00:00  50149031.0     791087.0  335.108110
       2026-10-01 04:00:00+00:00  36471598.0     707896.0  329.613724
       2026-10-02 04:00:00+00:00  33442044.0     628334.0  333.164889
       2026-10-05 04:00:00+00:00  34584115.0     648605.0  333.417529
       2026-10-06 04:00:00+00:00  30604659.0     592886.0  333.137074
       2026-10-07 04:00:00+00:00  34279939.0     615813.0  336.000429
       2026-10-08 04:00:00+00:00  35483577.0     668880.0  339.339077
       2026-10-09 04:00:00+00:00  38038338.0     735437.0  334.765394

In [40]:
df_aapl.info()

<class 'pandas.DataFrame'>
MultiIndex: 21 entries, ('AAPL', Timestamp('2026-09-11 04:00:00+0000', tz='UTC')) to ('AAPL', Timestamp('2026-10-09 04:00:00+0000', tz='UTC'))
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   open         21 non-null     float64
 1   high         21 non-null     float64
 2   low          21 non-null     float64
 3   close        21 non-null     float64
 4   volume       21 non-null     float64
 5   trade_count  21 non-null     float64
 6   vwap         21 non-null     float64
dtypes: float64(7)
memory usage: 1.5 KB

In [41]:
df_aapl

                                     open      high       low   close  \
symbol timestamp
AAPL   2026-09-11 04:00:00+00:00  327.450  336.2200  326.3000  332.27
       2026-09-14 04:00:00+00:00  334.790  335.5000  331.3400  333.08
       2026-09-15 04:00:00+00:00  330.135  331.7800  328.3500  331.34
       2026-09-16 04:00:00+00:00  332.530  335.4800  330.7000  332.41
       2026-09-17 04:00:00+00:00  334.770  338.3400  330.1833  337.00
       2026-09-18 04:00:00+00:00  337.905  338.4900  332.5300  336.13
       2026-09-21 04:00:00+00:00  335.280  339.6400  333.0500  338.98
       2026-09-22 04:00:00+00:00  340.135  345.3400  338.7500  339.75
       2026-09-23 04:00:00+00:00  341.075  341.8000  335.5000  337.02
       2026-09-24 04:00:00+00:00  336.720  338.9100  334.3000  335.92
       2026-09-25 04:00:00+00:00  336.040  341.6700  334.5300  341.07
       2026-09-28 04:00:00+00:00  340.370  342.9880  338.0400  338.40
       2026-09-29 04:00:00+00:00  336.965  337.0850  328.7000  329.40
       2026-09-30 04:00:00+00:00  330.800  339.5000  330.1401  333.02
       2026-10-01 04:00:00+00:00  330.000  332.4816  325.8100  330.32
       2026-10-02 04:00:00+00:00  333.260  334.5400  330.6100  333.69
       2026-10-05 04:00:00+00:00  332.815  336.2100  331.6500  332.89
       2026-10-06 04:00:00+00:00  332.280  334.3800  330.6200  333.63
       2026-10-07 04:00:00+00:00  336.960  338.6700  332.7800  336.67
       2026-10-08 04:00:00+00:00  336.815  341.5700  335.9000  340.42
       2026-10-09 04:00:00+00:00  331.695  338.6100  330.7000  336.64

                                      volume  trade_count        vwap
symbol timestamp
AAPL   2026-09-11 04:00:00+00:00  50906905.0    1001537.0  333.144960
       2026-09-14 04:00:00+00:00  39524847.0    1031536.0  333.684654
       2026-09-15 04:00:00+00:00  31916076.0     688356.0  330.541211
       2026-09-16 04:00:00+00:00  36100868.0     637488.0  332.945495
       2026-09-17 04:00:00+00:00  36817969.0     668736.0  335.467058
       2026-09-18 04:00:00+00:00  86726840.0     681554.0  336.096486
       2026-09-21 04:00:00+00:00  35165402.0     717707.0  337.856484
       2026-09-22 04:00:00+00:00  40814327.0     701605.0  341.063608
       2026-09-23 04:00:00+00:00  31795692.0     636292.0  337.346040
       2026-09-24 04:00:00+00:00  24871878.0     524733.0  336.682496
       2026-09-25 04:00:00+00:00  30134469.0     605912.0  339.285622
       2026-09-28 04:00:00+00:00  32989725.0     710434.0  339.919521
       2026-09-29 04:00:00+00:00  38641024.0     764858.0  331.015191
       2026-09-30 04:00:00+00:00  50149031.0     791087.0  335.108110
       2026-10-01 04:00:00+00:00  36471598.0     707896.0  329.613724
       2026-10-02 04:00:00+00:00  33442044.0     628334.0  333.164889
       2026-10-05 04:00:00+00:00  34584115.0     648605.0  333.417529
       2026-10-06 04:00:00+00:00  30604659.0     592886.0  333.137074
       2026-10-07 04:00:00+00:00  34279939.0     615813.0  336.000429
       2026-10-08 04:00:00+00:00  35483577.0     668880.0  339.339077
       2026-10-09 04:00:00+00:00  38038338.0     735437.0  334.765394

In [ ]:
#promote symbol and timestamp to columns in df_aapl
df_aapl = df_aapl.reset_index()

In [45]:
df_aapl.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   symbol       21 non-null     str
 1   timestamp    21 non-null     datetime64[us, UTC]
 2   open         21 non-null     float64
 3   high         21 non-null     float64
 4   low          21 non-null     float64
 5   close        21 non-null     float64
 6   volume       21 non-null     float64
 7   trade_count  21 non-null     float64
 8   vwap         21 non-null     float64
dtypes: datetime64[us, UTC](1), float64(7), str(1)
memory usage: 1.7 KB

In [47]:
df_aapl.drop(columns=['symbol'])

,timestamp,open,high,low,close,volume,trade_count,vwap
0,2026-09-11 04:00:00+00:00,327.450,336.2200,326.3000,332.27,50906905.0,1001537.0,333.144960
1,2026-09-14 04:00:00+00:00,334.790,335.5000,331.3400,333.08,39524847.0,1031536.0,333.684654
2,2026-09-15 04:00:00+00:00,330.135,331.7800,328.3500,331.34,31916076.0,688356.0,330.541211
3,2026-09-16 04:00:00+00:00,332.530,335.4800,330.7000,332.41,36100868.0,637488.0,332.945495
4,2026-09-17 04:00:00+00:00,334.770,338.3400,330.1833,337.00,36817969.0,668736.0,335.467058
5,2026-09-18 04:00:00+00:00,337.905,338.4900,332.5300,336.13,86726840.0,681554.0,336.096486
6,2026-09-21 04:00:00+00:00,335.280,339.6400,333.0500,338.98,35165402.0,717707.0,337.856484
7,2026-09-22 04:00:00+00:00,340.135,345.3400,338.7500,339.75,40814327.0,701605.0,341.063608
8,2026-09-23 04:00:00+00:00,341.075,341.8000,335.5000,337.02,31795692.0,636292.0,337.346040
9,2026-09-24 04:00:00+00:00,336.720,338.9100,334.3000,335.92,24871878.0,524733.0,336.682496
10,2026-09-25 04:00:00+00:00,336.040,341.6700,334.5300,341.07,30134469.0,605912.0,339.285622
11,2026-09-28 04:00:00+00:00,340.370,342.9880,338.0400,338.40,32989725.0,710434.0,339.919521
12,2026-09-29 04:00:00+00:00,336.965,337.0850,328.7000,329.40,38641024.0,764858.0,331.015191
13,2026-09-30 04:00:00+00:00,330.800,339.5000,330.1401,333.02,50149031.0,791087.0,335.108110
14,2026-10-01 04:00:00+00:00,330.000,332.4816,325.8100,330.32,36471598.0,707896.0,329.613724
15,2026-10-02 04:00:00+00:00,333.260,334.5400,330.6100,333.69,33442044.0,628334.0,333.164889
16,2026-10-05 04:00:00+00:00,332.815,336.2100,331.6500,332.89,34584115.0,648605.0,333.417529
17,2026-10-06 04:00:00+00:00,332.280,334.3800,330.6200,333.63,30604659.0,592886.0,333.137074
18,2026-10-07 04:00:00+00:00,336.960,338.6700,332.7800,336.67,34279939.0,615813.0,336.000429
19,2026-10-08 04:00:00+00:00,336.815,341.5700,335.9000,340.42,35483577.0,668880.0,339.339077
20,2026-10-09 04:00:00+00:00,331.695,338.6100,330.7000,336.64,38038338.0,735437.0,334.765394

In [51]:
from io import StringIO

import pandas as pd
import requests

url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"

headers = {
    "User-Agent": "FinancialTickerUpdater/1.0 (contact: your-email@example.com)"
}

response = requests.get(url, headers=headers, timeout=30)
response.raise_for_status()

tables = pd.read_html(StringIO(response.text))
sp500_df = tables[0]

tickers = sp500_df["Symbol"].tolist()

In [52]:
tickers

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'AON',
 'APA',
 'APO',
 'AAPL',
 'AMAT',
 'APP',
 'APTV',
 'ACGL',
 'ADM',
 'ARES',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVY',
 'AXON',
 'BKR',
 'BALL',
 'BAC',
 'BAX',
 'BDX',
 'BRK.B',
 'BBY',
 'TECH',
 'BIIB',
 'BLK',
 'BX',
 'XYZ',
 'BE',
 'BNY',
 'BA',
 'BKNG',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BRO',
 'BF.B',
 'BG',
 'BXP',
 'CHRW',
 'CDNS',
 'CPT',
 'COF',
 'CAH',
 'CCL',
 'CARR',
 'CVNA',
 'CASY',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'COR',
 'CNC',
 'CNP',
 'CF',
 'CRL',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CIEN',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'COHR',
 'COIN',
 'CL',
 'CMCSA',
 'FIX',
 'COP',
 'ED',
 'STZ',
 'CEG',
 'COO',
 'CPRT',
 'GLW',
 'CPAY',
 'CSGP',
 'COST',
 'CRH',
 'CRWD',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHR',
 'DRI',
 'DDOG',
 'DVA',
 'DECK',
 'DE',
 'DELL',
 'DAL',
 'DVN',
 'DXCM',
 'FANG',
 'DLR',
 'DG',
 'DLTR',
 'D',
 'DPZ',
 'DASH',
 'DOV',
 'DOW',
 'DHI',
 'DTE',
 'DUK',
 'DD',
 'ETN',
 'EBAY',
 'ECHO',
 'ECL',
 'EIX',
 'EW',
 'ELV',
 'EME',
 'EMR',
 'ETR',
 'EOG',
 'EQT',
 'EFX',
 'EQIX',
 'ERIE',
 'ESS',
 'EL',
 'EG',
 'EVRG',
 'P',
 'ES',
 'EXC',
 'EXE',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FDS',
 'FICO',
 'FAST',
 'FRT',
 'FDX',
 'FDXF',
 'FERG',
 'FIS',
 'FITB',
 'FSLR',
 'FE',
 'FISV',
 'FLEX',
 'F',
 'FTNT',
 'FTV',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GRMN',
 'IT',
 'GE',
 'GEHC',
 'GEV',
 'GEN',
 'GNRC',
 'GD',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GPN',
 'GL',
 'GDDY',
 'GS',
 'HAL',
 'HIG',
 'HAS',
 'HCA',
 'DOC',
 'HSIC',
 'HSY',
 'HPE',
 'HLT',
 'HD',
 'HONA',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUBB',
 'HUM',
 'HBAN',
 'HII',
 'IBM',
 'IEX',
 'IDXX',
 'ITW',
 'ILMN',
 'INCY',
 'IR',
 'PODD',
 'INTC',
 'IBKR',
 'ICE',
 'IFF',
 'IP',
 'INTU',
 'ISRG',
 'IVZ',
 'INVH',
 'IQV',
 'IRM',
 'JBHT',
 'JBL',
 'JKHY',
 'J',
 'JNJ',
 'JCI',
 'JPM',
 'KVUE',
 'KDP',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KKR',
 'KLAC',
 'KHC',
 'KR',
 'LHX',
 'LH',
 'LRCX',
 'LVS',
 'LDOS',
 'LEN',
 'LII',
 'LLY',
 'LIN',
 'LYV',
 'LMT',
 'L',
 'LOW',
 'LULU',
 'LITE',
 'LYB',
 'MTB',
 'MPC',
 'MAR',
 'MRSH',
 'MLM',
 'MRVL',
 'MAS',
 'MA',
 'MKC',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'META',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MRNA',
 'MDLZ',
 'MPWR',
 'MNST',
 'MCO',
 'MS',
 'MOS',
 'MSI',
 'MSCI',
 'NDAQ',
 'NTAP',
 'NFLX',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NKE',
 'NI',
 'NDSN',
 'NSC',
 'NTRS',
 'NOC',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'NXPI',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'ON',
 'OKE',
 'ORCL',
 'OTIS',
 'PCAR',
 'PKG',
 'PLTR',
 'PANW',
 'PH',
 'PAYX',
 'PYPL',
 'PNR',
 'PEP',
 'PFE',
 'PCG',
 'PM',
 'PSX',
 'PNW',
 'PNC',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PTC',
 'PSA',
 'PHM',
 'PWR',
 'QCOM',
 'DGX',
 'Q',
 'RL',
 'RJF',
 'RDDT',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RVTY',
 'HOOD',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SNDK',
 'SBAC',
 'SLB',
 'STX',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SKYD',
 'SWKS',
 'SJM',
 'SW',
 'SNA',
 'SOLV',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STLD',
 'STE',
 'SYK',
 'SMCI',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TRGP',
 'TGT',
 'TEL',
 'TDY',
 'TER',
 'TSLA',
 'TXN',
 'TPL',
 'TXT',
 'TMO',
 'TJX',
 'TKO',
 'TSCO',
 'TT',
 'TDG',
 'TRV',
 'TRMB',
 'TFC',
 'TWLO',
 'TYL',
 'TSN',
 'USB',
 'UBER',
 'UDR',
 'ULTA',
 'UNP',
 'UAL',
 'UPS',
 'URI',
 'UNH',
 'UHS',
 'VLO',
 'VEEV',
 'VTR',
 'VLTO',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VRT',
 'VTRS',
 'VICI',
 'V',
 'VST',
 'VMRK',
 'VMC',
 'VYLR',
 'WRB',
 'GWW',
 'WAB',
 'WMT',
 'DIS',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WST',
 'WDC',
 'WY',
 'WSM',
 'WMB',
 'WTW',
 'WDAY',
 'WYNN',
 'XEL',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZTS']

In [85]:
#let's write the tickers list to a txt in documentation
#with open("../../documentation/sp500_tickers.txt", "w") as f:
#    for ticker in tickers:
#        f.write(f"{ticker}\n")
old_tickers = []
with open("../../documentation/sp500_tickers.txt", "r") as f:
    old_tickers = [line.strip() for line in f.readlines()]

old_tickers

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'AON',
 'APA',
 'APO',
 'AAPL',
 'AMAT',
 'APP',
 'APTV',
 'ACGL',
 'ADM',
 'ARES',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVY',
 'AXON',
 'BKR',
 'BALL',
 'BAC',
 'BAX',
 'BDX',
 'BRK.B',
 'BBY',
 'TECH',
 'BIIB',
 'BLK',
 'BX',
 'XYZ',
 'BE',
 'BNY',
 'BA',
 'BKNG',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BRO',
 'BF.B',
 'BG',
 'BXP',
 'CHRW',
 'CDNS',
 'CPT',
 'COF',
 'CAH',
 'CCL',
 'CARR',
 'CVNA',
 'CASY',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'COR',
 'CNC',
 'CNP',
 'CF',
 'CRL',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CIEN',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'COHR',
 'COIN',
 'CL',
 'CMCSA',
 'FIX',
 'COP',
 'ED',
 'STZ',
 'CEG',
 'COO',
 'CPRT',
 'GLW',
 'CPAY',
 'CSGP',
 'COST',
 'CRH',
 'CRWD',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHR',
 'DRI',
 'DDOG',
 'DVA',
 'DECK',
 'DE',
 'DELL',
 'DAL',
 'DVN',
 'DXCM',
 'FANG',
 'DLR',
 'DG',
 'DLTR',
 'D',
 'DPZ',
 'DASH',
 'DOV',
 'DOW',
 'DHI',
 'DTE',
 'DUK',
 'DD',
 'ETN',
 'EBAY',
 'ECHO',
 'ECL',
 'EIX',
 'EW',
 'ELV',
 'EME',
 'EMR',
 'ETR',
 'EOG',
 'EQT',
 'EFX',
 'EQIX',
 'ERIE',
 'ESS',
 'EL',
 'EG',
 'EVRG',
 'P',
 'ES',
 'EXC',
 'EXE',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FDS',
 'FICO',
 'FAST',
 'FRT',
 'FDX',
 'FDXF',
 'FERG',
 'FIS',
 'FITB',
 'FSLR',
 'FE',
 'FISV',
 'FLEX',
 'F',
 'FTNT',
 'FTV',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GRMN',
 'IT',
 'GE',
 'GEHC',
 'GEV',
 'GEN',
 'GNRC',
 'GD',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GPN',
 'GL',
 'GDDY',
 'GS',
 'HAL',
 'HIG',
 'HAS',
 'HCA',
 'DOC',
 'HSIC',
 'HSY',
 'HPE',
 'HLT',
 'HD',
 'HONA',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUBB',
 'HUM',
 'HBAN',
 'HII',
 'IBM',
 'IEX',
 'IDXX',
 'ITW',
 'ILMN',
 'INCY',
 'IR',
 'PODD',
 'INTC',
 'IBKR',
 'ICE',
 'IFF',
 'IP',
 'INTU',
 'ISRG',
 'IVZ',
 'INVH',
 'IQV',
 'IRM',
 'JBHT',
 'JBL',
 'JKHY',
 'J',
 'JNJ',
 'JCI',
 'JPM',
 'KVUE',
 'KDP',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KKR',
 'KLAC',
 'KHC',
 'KR',
 'LHX',
 'LH',
 'LRCX',
 'LVS',
 'LDOS',
 'LEN',
 'LII',
 'LLY',
 'LIN',
 'LYV',
 'LMT',
 'L',
 'LOW',
 'LULU',
 'LITE',
 'LYB',
 'MTB',
 'MPC',
 'MAR',
 'MRSH',
 'MLM',
 'MRVL',
 'MAS',
 'MA',
 'MKC',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'META',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MRNA',
 'MDLZ',
 'MPWR',
 'MNST',
 'MCO',
 'MS',
 'MOS',
 'MSI',
 'MSCI',
 'NDAQ',
 'NTAP',
 'NFLX',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NKE',
 'NI',
 'NDSN',
 'NSC',
 'NTRS',
 'NOC',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'NXPI',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'ON',
 'OKE',
 'ORCL',
 'OTIS',
 'PCAR',
 'PKG',
 'PLTR',
 'PANW',
 'PH',
 'PAYX',
 'PYPL',
 'PNR',
 'PEP',
 'PFE',
 'PCG',
 'PM',
 'PSX',
 'PNW',
 'PNC',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PTC',
 'PSA',
 'PHM',
 'PWR',
 'QCOM',
 'DGX',
 'Q',
 'RL',
 'RJF',
 'RDDT',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RVTY',
 'HOOD',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SNDK',
 'SBAC',
 'SLB',
 'STX',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SKYD',
 'SWKS',
 'SJM',
 'SW',
 'SNA',
 'SOLV',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STLD',
 'STE',
 'SYK',
 'SMCI',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TRGP',
 'TGT',
 'TEL',
 'TDY',
 'TER',
 'TSLA',
 'TXN',
 'TPL',
 'TXT',
 'TMO',
 'TJX',
 'TKO',
 'TSCO',
 'TT',
 'TDG',
 'TRV',
 'TRMB',
 'TFC',
 'TWLO',
 'TYL',
 'TSN',
 'USB',
 'UBER',
 'UDR',
 'ULTA',
 'UNP',
 'UAL',
 'UPS',
 'URI',
 'UNH',
 'UHS',
 'VLO',
 'VEEV',
 'VTR',
 'VLTO',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VRT',
 'VTRS',
 'VICI',
 'V',
 'VST',
 'VMRK',
 'VMC',
 'VYLR',
 'WRB',
 'GWW',
 'WAB',
 'WMT',
 'DIS',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WST',
 'WDC',
 'WY',
 'WSM',
 'WMB',
 'WTW',
 'WDAY',
 'WYNN',
 'XEL',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZTS']

In [56]:
today = datetime.today()
from time import sleep

In [57]:
for ticker in tickers:
    try:
        request_params = StockBarsRequest(
            symbol_or_symbols=[ticker],
            timeframe=TimeFrame.Day,
            start=datetime(1990, 1, 1),
            end=today
        )

        # Fetch data and convert to a pandas DataFrame
        bars = client.get_stock_bars(request_params)
        df = bars.df.reset_index().drop(columns=['symbol'])
        db.set_table_name(ticker.lower())
        db.set_pdf(df)
        db.write_pdf_to_sql()
        sleep(5)
    except Exception as e:
        print(f"Error processing ticker {ticker}: {e}")

In [64]:
engine = db.get_engine()
from sqlalchemy import text
from datetime import timedelta, datetime

In [ ]:
new_tickers = []
with engine.begin() as connection:
    for ticker in tickers:
        if ticker not in old_tickers:
            new_tickers.append(ticker)
            start_date = datetime(1990, 1, 1)
            request_params = StockBarsRequest(
                symbol_or_symbols=[ticker],
                timeframe=TimeFrame.Day,
                start=start_date,
                end=today
            )
            bars = client.get_stock_bars(request_params)
            df_to_append = bars.df.reset_index().drop(columns=['symbol'])
            if len(df_to_append) > 0:
                db.set_table_name(ticker.lower())
                db.set_pdf(df_to_append)
                db.write_pdf_to_sql(if_exists='append')
                sleep(1)
        else:
            max_date_query = text(f'SELECT MAX(timestamp) FROM "{ticker.lower()}"')
            result = connection.execute(max_date_query)
            max_date = result.scalar()
            print(f"Max date for {ticker}: {max_date}")
            #print(type((max_date + timedelta(days=1)).date()), type(today.date()))
            print('new range:', max_date + timedelta(days=1), today)
            if today.date() > (max_date + timedelta(days=1)).date():
                #print(f"Data for {ticker} is outdated. Needs update.")
                request_params = StockBarsRequest(
                    symbol_or_symbols=[ticker],
                    timeframe=TimeFrame.Day,
                    start=max_date + timedelta(days=1),
                    end=today
                )
                bars = client.get_stock_bars(request_params)
                df_to_append = bars.df.reset_index().drop(columns=['symbol'])
                df_to_append = df_to_append[df_to_append['timestamp'] > max_date]
                if len(df_to_append) > 0:
                    db.set_table_name(ticker.lower())
                    db.set_pdf(df_to_append)
                    db.write_pdf_to_sql(if_exists='append')
                    sleep(1)

with open("../../documentation/sp500_tickers.txt", "a") as f:
    for ticker in new_tickers:
        f.write(f"{ticker}\n")

Max date for MMM: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AOS: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ABT: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ABBV: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ACN: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ADBE: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AMD: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AES: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AFL: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for A: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for APD: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ABNB: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AKAM: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ALB: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ARE: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ALGN: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ALLE: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for LNT: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ALL: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for GOOGL: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for GOOG: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for MO: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AMZN: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AMCR: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AEE: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AEP: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AXP: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AIG: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AMT: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AWK: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AMP: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AME: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AMGN: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for APH: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ADI: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AON: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for APA: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for APO: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AAPL: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AMAT: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for APP: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for APTV: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ACGL: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ADM: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ARES: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ANET: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AJG: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AIZ: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for T: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ATO: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ADSK: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ADP: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AZO: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AVY: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AXON: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BKR: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BALL: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BAC: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BAX: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BDX: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BRK.B: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BBY: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for TECH: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BIIB: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BLK: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BX: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for XYZ: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BE: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BNY: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BA: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BKNG: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BSX: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BMY: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for AVGO: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BR: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BRO: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BF.B: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BG: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for BXP: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CHRW: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CDNS: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CPT: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for COF: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CAH: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CCL: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CARR: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CVNA: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CASY: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CAT: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CBOE: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CBRE: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CDW: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for COR: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CNC: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CNP: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CF: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CRL: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for SCHW: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CHTR: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CVX: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CMG: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CB: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CHD: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CIEN: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CI: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CINF: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CTAS: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CSCO: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for C: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CFG: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CLX: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CME: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CMS: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for KO: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CTSH: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for COHR: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for COIN: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CL: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CMCSA: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for FIX: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for COP: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ED: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for STZ: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CEG: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for COO: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CPRT: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for GLW: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CPAY: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CSGP: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for COST: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CRH: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CRWD: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CCI: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CSX: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CMI: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for CVS: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DHR: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DRI: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DDOG: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DVA: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DECK: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DE: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DELL: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DAL: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DVN: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DXCM: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for FANG: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DLR: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DG: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DLTR: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for D: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DPZ: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DASH: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DOV: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DOW: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DHI: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DTE: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DUK: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for DD: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ETN: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EBAY: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ECHO: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ECL: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EIX: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EW: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ELV: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EME: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EMR: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ETR: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EOG: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EQT: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EFX: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EQIX: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ERIE: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ESS: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EL: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EG: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EVRG: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for P: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for ES: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EXC: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EXE: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EXPE: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EXPD: 2026-10-11 21:00:00-07:00
new range: 2026-10-12 21:00:00-07:00 2026-10-12 11:42:45.144905
Max date for EXR: 2026-10-11 21:00:00-07:00