In [35]:
from fredapi import Fred
import pandas as pd
import os
from pathlib import Path
from dotenv import load_dotenv
import json
import seaborn as sns
import matplotlib.pyplot as plt
from time import sleep

In [36]:
load_dotenv(Path.cwd().parents[1] / ".env")
api_key = os.getenv("FRED_API_KEY")

print(f"API Key: {api_key[:3]}")

API Key: b7b

In [37]:
fred = Fred(api_key=api_key)
unemployment_data = fred.get_series('UNRATE', observation_start='2023-01-01', observation_end='2026-07-31')
print("--- Unemployment Rate Series ---")
print(unemployment_data.tail(24))

--- Unemployment Rate Series ---
2024-08-01    4.2
2024-09-01    4.1
2024-10-01    4.1
2024-11-01    4.2
2024-12-01    4.1
2025-01-01    4.0
2025-02-01    4.2
2025-03-01    4.2
2025-04-01    4.2
2025-05-01    4.3
2025-06-01    4.1
2025-07-01    4.3
2025-08-01    4.3
2025-09-01    4.4
2025-10-01    NaN
2025-11-01    4.5
2025-12-01    4.4
2026-01-01    4.3
2026-02-01    4.4
2026-03-01    4.3
2026-04-01    4.3
2026-05-01    4.3
2026-06-01    4.2
2026-07-01    4.1
dtype: float64

In [38]:
fred_ids = []
with open("../../documentation/fred_ids.txt", "r") as file:
    fred_ids = [line.strip() for line in file.readlines()]
#for id in fred_ids:print(id)

In [39]:
today = pd.Timestamp.today()
today_formatted = today.strftime('%Y-%m-%d')
today_formatted

'2026-10-08'

In [40]:
current_data = {}
for id in fred_ids:
    current_data[id] = fred.get_series(id, observation_start='1990-01-01', observation_end=today_formatted)
    #current_data[id] = fred.get_series(id, observation_start='2026-10-01', observation_end=today_formatted)
    print(f"--- {id} Series ---")
    print(current_data[id].tail(2))
    sleep(1)

--- DEXUSEU Series ---
2026-09-01    1.1593
2026-09-02    1.1592
2026-09-03    1.1623
2026-09-04    1.1618
2026-09-07       NaN
2026-09-08    1.1627
2026-09-09    1.1627
2026-09-10    1.1629
2026-09-11    1.1604
2026-09-14    1.1549
2026-09-15    1.1542
2026-09-16    1.1538
2026-09-17    1.1479
2026-09-18    1.1464
2026-09-21    1.1469
2026-09-22    1.1432
2026-09-23    1.1394
2026-09-24    1.1373
2026-09-25    1.1400
2026-09-28    1.1367
2026-09-29    1.1336
2026-09-30    1.1345
2026-10-01    1.1232
2026-10-02    1.1259
dtype: float64
--- DEXJPUS Series ---
2026-09-01    160.03
2026-09-02    158.79
2026-09-03    155.39
2026-09-04    156.11
2026-09-07       NaN
2026-09-08    154.24
2026-09-09    153.50
2026-09-10    154.06
2026-09-11    153.71
2026-09-14    154.42
2026-09-15    155.11
2026-09-16    155.08
2026-09-17    155.85
2026-09-18    156.87
2026-09-21    157.46
2026-09-22    157.55
2026-09-23    158.30
2026-09-24    158.92
2026-09-25    157.18
2026-09-28    157.44
2026-09-29    157.50
2026-09-30    157.25
2026-10-01    157.63
2026-10-02    157.81
dtype: float64
--- DEXUSUK Series ---
2026-09-01    1.3527
2026-09-02    1.3503
2026-09-03    1.3536
2026-09-04    1.3521
2026-09-07       NaN
2026-09-08    1.3542
2026-09-09    1.3549
2026-09-10    1.3532
2026-09-11    1.3524
2026-09-14    1.3494
2026-09-15    1.3479
2026-09-16    1.3451
2026-09-17    1.3347
2026-09-18    1.3372
2026-09-21    1.3371
2026-09-22    1.3326
2026-09-23    1.3253
2026-09-24    1.3217
2026-09-25    1.3250
2026-09-28    1.3257
2026-09-29    1.3212
2026-09-30    1.3267
2026-10-01    1.3196
2026-10-02    1.3234
dtype: float64
--- DEXUSAL Series ---
2026-09-01    0.7161
2026-09-02    0.7169
2026-09-03    0.7199
2026-09-04    0.7209
2026-09-07       NaN
2026-09-08    0.7218
2026-09-09    0.7219
2026-09-10    0.7171
2026-09-11    0.7174
2026-09-14    0.7141
2026-09-15    0.7128
2026-09-16    0.7132
2026-09-17    0.7114
2026-09-18    0.7111
2026-09-21    0.7123
2026-09-22    0.7102
2026-09-23    0.7036
2026-09-24    0.7016
2026-09-25    0.7033
2026-09-28    0.7020
2026-09-29    0.6979
2026-09-30    0.6952
2026-10-01    0.6911
2026-10-02    0.6953
dtype: float64
--- DEXCHUS Series ---
2026-09-01    6.7202
2026-09-02    6.7190
2026-09-03    6.7181
2026-09-04    6.7108
2026-09-07       NaN
2026-09-08    6.7105
2026-09-09    6.7059
2026-09-10    6.7061
2026-09-11    6.7080
2026-09-14    6.7082
2026-09-15    6.7112
2026-09-16    6.7060
2026-09-17    6.7074
2026-09-18    6.6975
2026-09-21    6.6947
2026-09-22    6.6996
2026-09-23    6.7111
2026-09-24    6.7128
2026-09-25    6.7110
2026-09-28    6.7103
2026-09-29    6.7030
2026-09-30    6.7045
2026-10-01    6.7038
2026-10-02    6.7038
dtype: float64
--- DEXINUS Series ---
2026-09-01    94.95
2026-09-02    94.97
2026-09-03    94.49
2026-09-04    94.49
2026-09-07      NaN
2026-09-08    94.82
2026-09-09    95.09
2026-09-10    95.44
2026-09-11    95.55
2026-09-14    95.55
2026-09-15    95.95
2026-09-16    95.96
2026-09-17    95.93
2026-09-18    95.87
2026-09-21    95.81
2026-09-22    95.59
2026-09-23    95.74
2026-09-24    95.96
2026-09-25    95.81
2026-09-28    95.98
2026-09-29    95.98
2026-09-30    95.83
2026-10-01    96.32
2026-10-02    96.31
dtype: float64
--- DEXBZUS Series ---
2026-09-01    5.1444
2026-09-02    5.1050
2026-09-03    5.1062
2026-09-04    5.1214
2026-09-07       NaN
2026-09-08    5.0836
2026-09-09    5.1021
2026-09-10    5.0983
2026-09-11    5.1009
2026-09-14    5.1516
2026-09-15    5.1498
2026-09-16    5.1424
2026-09-17    5.1528
2026-09-18    5.1596
2026-09-21    5.1107
2026-09-22    5.1111
2026-09-23    5.1483
2026-09-24    5.1953
2026-09-25    5.1921
2026-09-28    5.2198
2026-09-29    5.2323
2026-09-30    5.1818
2026-10-01    5.2329
2026-10-02    5.2222
dtype: float64
--- DEXCAUS Series ---
2026-09-01    1.3902
2026-09-02    1.3850
2026-09-03    1.3782
2026-09-04    1.3834
2026-09-07       NaN
2026-09-08    1.3779
2026-09-09    1.3805
2026-09-10    1.3806
2026-09-11    1.3864
2026-09-14    1.3911
2026-09-15    1.3916
2026-09-16    1.3934
2026-09-17    1.3991
2026-09-18    1.4008
2026-09-21    1.4023
2026-09-22    1.4070
2026-09-23    1.4098
2026-09-24    1.4140
2026-09-25    1.4140
2026-09-28    1.4169
2026-09-29    1.4189
2026-09-30    1.4210
2026-10-01    1.4253
2026-10-02    1.4253
dtype: float64
--- DEXSZUS Series ---
2026-09-01    0.8117
2026-09-02    0.8130
2026-09-03    0.8073
2026-09-04    0.8096
2026-09-07       NaN
2026-09-08    0.8091
2026-09-09    0.8102
2026-09-10    0.8113
2026-09-11    0.8159
2026-09-14    0.8173
2026-09-15    0.8190
2026-09-16    0.8191
2026-09-17    0.8245
2026-09-18    0.8242
2026-09-21    0.8213
2026-09-22    0.8219
2026-09-23    0.8250
2026-09-24    0.8286
2026-09-25    0.8282
2026-09-28    0.8322
2026-09-29    0.8347
2026-09-30    0.8348
2026-10-01    0.8314
2026-10-02    0.8293
dtype: float64
--- DEXHKUS Series ---
2026-09-01    7.8408
2026-09-02    7.8420
2026-09-03    7.8401
2026-09-04    7.8407
2026-09-07       NaN
2026-09-08    7.8412
2026-09-09    7.8418
2026-09-10    7.8411
2026-09-11    7.8427
2026-09-14    7.8435
2026-09-15    7.8443
2026-09-16    7.8447
2026-09-17    7.8456
2026-09-18    7.8456
2026-09-21    7.8456
2026-09-22    7.8437
2026-09-23    7.8431
2026-09-24    7.8423
2026-09-25    7.8439
2026-09-28    7.8447
2026-09-29    7.8463
2026-09-30    7.8467
2026-10-01    7.8453
2026-10-02    7.8470
dtype: float64
--- DEXMXUS Series ---
2026-09-01    16.9581
2026-09-02    16.9786
2026-09-03    16.9602
2026-09-04    16.8630
2026-09-07        NaN
2026-09-08    16.9137
2026-09-09    16.8941
2026-09-10    16.9730
2026-09-11    16.9704
2026-09-14    17.1104
2026-09-15    17.1393
2026-09-16    17.1360
2026-09-17    17.1829
2026-09-18    17.2454
2026-09-21    17.2252
2026-09-22    17.3022
2026-09-23    17.4851
2026-09-24    17.6704
2026-09-25    17.6932
2026-09-28    17.8439
2026-09-29    18.0534
2026-09-30    18.0609
2026-10-01    18.4001
2026-10-02    18.1920
dtype: float64
--- DEXUSNZ Series ---
2026-09-01    0.5905
2026-09-02    0.5847
2026-09-03    0.5885
2026-09-04    0.5890
2026-09-07       NaN
2026-09-08    0.5855
2026-09-09    0.5842
2026-09-10    0.5810
2026-09-11    0.5817
2026-09-14    0.5779
2026-09-15    0.5757
2026-09-16    0.5759
2026-09-17    0.5736
2026-09-18    0.5710
2026-09-21    0.5719
2026-09-22    0.5715
2026-09-23    0.5672
2026-09-24    0.5659
2026-09-25    0.5667
2026-09-28    0.5668
2026-09-29    0.5635
2026-09-30    0.5640
2026-10-01    0.5600
2026-10-02    0.5612
dtype: float64
--- T10Y2Y Series ---
2026-09-04    0.41
2026-09-07     NaN
2026-09-08    0.41
2026-09-09    0.40
2026-09-10    0.39
2026-09-11    0.33
2026-09-14    0.32
2026-09-15    0.33
2026-09-16    0.27
2026-09-17    0.27
2026-09-18    0.25
2026-09-21    0.20
2026-09-22    0.25
2026-09-23    0.26
2026-09-24    0.31
2026-09-25    0.36
2026-09-28    0.32
2026-09-29    0.37
2026-09-30    0.41
2026-10-01    0.46
2026-10-02    0.45
2026-10-05    0.47
2026-10-06    0.48
2026-10-07    0.51
dtype: float64
--- T10Y3M Series ---
2026-09-04    0.87
2026-09-07     NaN
2026-09-08    0.86
2026-09-09    0.88
2026-09-10    0.95
2026-09-11    0.89
2026-09-14    0.86
2026-09-15    0.89
2026-09-16    0.87
2026-09-17    0.82
2026-09-18    0.87
2026-09-21    0.79
2026-09-22    0.80
2026-09-23    0.92
2026-09-24    0.94
2026-09-25    0.93
2026-09-28    0.96
2026-09-29    1.01
2026-09-30    1.09
2026-10-01    1.07
2026-10-02    1.09
2026-10-05    1.09
2026-10-06    1.06
2026-10-07    1.06
dtype: float64
--- T10YIE Series ---
2026-09-04    2.35
2026-09-07     NaN
2026-09-08    2.37
2026-09-09    2.37
2026-09-10    2.40
2026-09-11    2.36
2026-09-14    2.37
2026-09-15    2.38
2026-09-16    2.33
2026-09-17    2.33
2026-09-18    2.33
2026-09-21    2.34
2026-09-22    2.33
2026-09-23    2.35
2026-09-24    2.33
2026-09-25    2.34
2026-09-28    2.34
2026-09-29    2.35
2026-09-30    2.36
2026-10-01    2.36
2026-10-02    2.36
2026-10-05    2.36
2026-10-06    2.36
2026-10-07    2.36
dtype: float64
--- TERMCBCCALLNS Series ---
2024-09-01      NaN
2024-10-01      NaN
2024-11-01    21.47
2024-12-01      NaN
2025-01-01      NaN
2025-02-01    21.37
2025-03-01      NaN
2025-04-01      NaN
2025-05-01    21.16
2025-06-01      NaN
2025-07-01      NaN
2025-08-01    21.39
2025-09-01      NaN
2025-10-01      NaN
2025-11-01    20.97
2025-12-01      NaN
2026-01-01      NaN
2026-02-01    21.00
2026-03-01      NaN
2026-04-01      NaN
2026-05-01    20.94
2026-06-01      NaN
2026-07-01      NaN
2026-08-01    21.19
dtype: float64
--- TOTALSL Series ---
2024-09-01    5058345.12
2024-10-01    5071588.43
2024-11-01    5065689.77
2024-12-01    4947229.57
2025-01-01    4955619.41
2025-02-01    4957607.46
2025-03-01    5021864.24
2025-04-01    5038214.15
2025-05-01    5048281.76
2025-06-01    5043533.83
2025-07-01    5055914.28
2025-08-01    5058589.77
2025-09-01    5071963.31
2025-10-01    5079764.65
2025-11-01    5083079.45
2025-12-01    5098820.82
2026-01-01    5103212.46
2026-02-01    5110390.78
2026-03-01    5131428.77
2026-04-01    5152527.91
2026-05-01    5155421.48
2026-06-01    5170757.74
2026-07-01    5188497.83
2026-08-01    5196778.44
dtype: float64
--- CPIAUCSL Series ---
2024-09-01    314.732
2024-10-01    315.631
2024-11-01    316.528
2024-12-01    317.604
2025-01-01    318.961
2025-02-01    319.679
2025-03-01    319.785
2025-04-01    320.302
2025-05-01    320.620
2025-06-01    321.435
2025-07-01    322.169
2025-08-01    323.291
2025-09-01    324.245
2025-10-01        NaN
2025-11-01    325.063
2025-12-01    326.031
2026-01-01    326.588
2026-02-01    327.460
2026-03-01    330.293
2026-04-01    332.407
2026-05-01    333.979
2026-06-01    332.568
2026-07-01    332.813
2026-08-01    334.131
dtype: float64
--- PCEPI Series ---
2024-09-01    124.146
2024-10-01    124.482
2024-11-01    124.666
2024-12-01    124.984
2025-01-01    125.423
2025-02-01    125.770
2025-03-01    125.869
2025-04-01    126.163
2025-05-01    126.408
2025-06-01    126.730
2025-07-01    126.906
2025-08-01    127.229
2025-09-01    127.601
2025-10-01    127.790
2025-11-01    128.045
2025-12-01    128.455
2026-01-01    128.845
2026-02-01    129.293
2026-03-01    130.105
2026-04-01    130.672
2026-05-01    131.241
2026-06-01    131.106
2026-07-01    131.172
2026-08-01    131.579
dtype: float64
--- CORESTICKM159SFRBATL Series ---
2024-09-01    4.011582
2024-10-01    3.975247
2024-11-01    3.890823
2024-12-01    3.752907
2025-01-01    3.624696
2025-02-01    3.520917
2025-03-01    3.265924
2025-04-01    3.178169
2025-05-01    3.167990
2025-06-01    3.302508
2025-07-01    3.427070
2025-08-01    3.430945
2025-09-01    3.322171
2025-10-01    3.077827
2025-11-01    2.954815
2025-12-01    3.006319
2026-01-01    2.979751
2026-02-01    2.903909
2026-03-01    2.929321
2026-04-01    3.038932
2026-05-01    3.091257
2026-06-01    2.806860
2026-07-01    2.715836
2026-08-01    2.700641
dtype: float64
--- DRCCLACBS Series ---
2020-07-01    1.99
2020-10-01    2.10
2021-01-01    1.88
2021-04-01    1.59
2021-07-01    1.53
2021-10-01    1.57
2022-01-01    1.69
2022-04-01    1.83
2022-07-01    2.05
2022-10-01    2.26
2023-01-01    2.47
2023-04-01    2.75
2023-07-01    2.95
2023-10-01    3.10
2024-01-01    3.17
2024-04-01    3.22
2024-07-01    3.20
2024-10-01    3.08
2025-01-01    3.05
2025-04-01    3.04
2025-07-01    2.99
2025-10-01    2.95
2026-01-01    2.91
2026-04-01    2.85
dtype: float64
--- DRSFRMACBS Series ---
2020-07-01    2.84
2020-10-01    2.75
2021-01-01    2.68
2021-04-01    2.47
2021-07-01    2.30
2021-10-01    2.29
2022-01-01    2.09
2022-04-01    1.96
2022-07-01    1.84
2022-10-01    1.79
2023-01-01    1.74
2023-04-01    1.72
2023-07-01    1.72
2023-10-01    1.70
2024-01-01    1.71
2024-04-01    1.73
2024-07-01    1.74
2024-10-01    1.77
2025-01-01    1.77
2025-04-01    1.78
2025-07-01    1.78
2025-10-01    1.79
2026-01-01    1.88
2026-04-01    1.86
dtype: float64
--- DRCLACBS Series ---
2020-07-01    1.81
2020-10-01    1.94
2021-01-01    1.69
2021-04-01    1.53
2021-07-01    1.52
2021-10-01    1.55
2022-01-01    1.65
2022-04-01    1.80
2022-07-01    1.92
2022-10-01    2.07
2023-01-01    2.22
2023-04-01    2.37
2023-07-01    2.52
2023-10-01    2.62
2024-01-01    2.67
2024-04-01    2.72
2024-07-01    2.73
2024-10-01    2.76
2025-01-01    2.77
2025-04-01    2.75
2025-07-01    2.72
2025-10-01    2.63
2026-01-01    2.64
2026-04-01    2.62
dtype: float64
--- DRBLACBS Series ---
2020-07-01    1.30
2020-10-01    1.24
2021-01-01    1.16
2021-04-01    1.06
2021-07-01    1.03
2021-10-01    1.12
2022-01-01    1.05
2022-04-01    1.03
2022-07-01    1.12
2022-10-01    1.02
2023-01-01    0.97
2023-04-01    1.00
2023-07-01    0.98
2023-10-01    1.02
2024-01-01    1.11
2024-04-01    1.15
2024-07-01    1.18
2024-10-01    1.27
2025-01-01    1.28
2025-04-01    1.29
2025-07-01    1.33
2025-10-01    1.34
2026-01-01    1.33
2026-04-01    1.27
dtype: float64
--- DRFLACBS Series ---
2020-07-01    2.44
2020-10-01    2.19
2021-01-01    2.02
2021-04-01    1.80
2021-07-01    1.70
2021-10-01    1.55
2022-01-01    1.28
2022-04-01    1.20
2022-07-01    1.07
2022-10-01    1.02
2023-01-01    0.91
2023-04-01    0.91
2023-07-01    0.99
2023-10-01    0.99
2024-01-01    1.01
2024-04-01    1.07
2024-07-01    1.11
2024-10-01    1.20
2025-01-01    1.34
2025-04-01    1.33
2025-07-01    1.32
2025-10-01    1.31
2026-01-01    1.34
2026-04-01    1.33
dtype: float64
--- DALLCCACBEP Series ---
2020-07-01    14186.0
2020-10-01    16001.0
2021-01-01    13126.0
2021-04-01    10472.0
2021-07-01    11089.0
2021-10-01    12681.0
2022-01-01    13212.0
2022-04-01    13928.0
2022-07-01    17394.0
2022-10-01    21263.0
2023-01-01    22331.0
2023-04-01    23847.0
2023-07-01    28167.0
2023-10-01    32199.0
2024-01-01    31398.0
2024-04-01    30230.0
2024-07-01    32544.0
2024-10-01    33486.0
2025-01-01    31247.0
2025-04-01    29647.0
2025-07-01    31480.0
2025-10-01    33040.0
2026-01-01    31054.0
2026-04-01    29013.0
dtype: float64
--- USPBS Series ---
2024-10-01    22486.0
2024-11-01    22499.0
2024-12-01    22532.0
2025-01-01    22480.0
2025-02-01    22473.0
2025-03-01    22457.0
2025-04-01    22470.0
2025-05-01    22450.0
2025-06-01    22419.0
2025-07-01    22403.0
2025-08-01    22375.0
2025-09-01    22359.0
2025-10-01    22335.0
2025-11-01    22391.0
2025-12-01    22372.0
2026-01-01    22408.0
2026-02-01    22412.0
2026-03-01    22440.0
2026-04-01    22460.0
2026-05-01    22466.0
2026-06-01    22502.0
2026-07-01    22496.0
2026-08-01    22491.0
2026-09-01    22482.0
dtype: float64
--- CES6054120001 Series ---
2024-10-01    1132.6
2024-11-01    1127.9
2024-12-01    1125.0
2025-01-01    1125.1
2025-02-01    1125.1
2025-03-01    1126.0
2025-04-01    1124.7
2025-05-01    1127.5
2025-06-01    1127.6
2025-07-01    1126.7
2025-08-01    1127.1
2025-09-01    1128.5
2025-10-01    1126.4
2025-11-01    1134.0
2025-12-01    1129.8
2026-01-01    1129.2
2026-02-01    1130.5
2026-03-01    1120.9
2026-04-01    1124.9
2026-05-01    1124.0
2026-06-01    1124.8
2026-07-01    1124.7
2026-08-01    1122.5
2026-09-01    1121.2
dtype: float64
--- USCONS Series ---
2024-10-01    8262.0
2024-11-01    8267.0
2024-12-01    8276.0
2025-01-01    8264.0
2025-02-01    8267.0
2025-03-01    8273.0
2025-04-01    8271.0
2025-05-01    8269.0
2025-06-01    8267.0
2025-07-01    8261.0
2025-08-01    8239.0
2025-09-01    8255.0
2025-10-01    8243.0
2025-11-01    8279.0
2025-12-01    8272.0
2026-01-01    8317.0
2026-02-01    8296.0
2026-03-01    8311.0
2026-04-01    8314.0
2026-05-01    8316.0
2026-06-01    8319.0
2026-07-01    8337.0
2026-08-01    8353.0
2026-09-01    8364.0
dtype: float64
--- UNRATE Series ---
2024-10-01    4.1
2024-11-01    4.2
2024-12-01    4.1
2025-01-01    4.0
2025-02-01    4.2
2025-03-01    4.2
2025-04-01    4.2
2025-05-01    4.3
2025-06-01    4.1
2025-07-01    4.3
2025-08-01    4.3
2025-09-01    4.4
2025-10-01    NaN
2025-11-01    4.5
2025-12-01    4.4
2026-01-01    4.3
2026-02-01    4.4
2026-03-01    4.3
2026-04-01    4.3
2026-05-01    4.3
2026-06-01    4.2
2026-07-01    4.1
2026-08-01    4.1
2026-09-01    4.2
dtype: float64
--- JTSJOR Series ---
2024-09-01    4.2
2024-10-01    4.5
2024-11-01    4.6
2024-12-01    4.4
2025-01-01    4.5
2025-02-01    4.4
2025-03-01    4.2
2025-04-01    4.3
2025-05-01    4.4
2025-06-01    4.3
2025-07-01    4.3
2025-08-01    4.2
2025-09-01    4.3
2025-10-01    4.3
2025-11-01    4.1
2025-12-01    4.0
2026-01-01    4.4
2026-02-01    4.2
2026-03-01    4.2
2026-04-01    4.6
2026-05-01    4.5
2026-06-01    4.3
2026-07-01    4.4
2026-08-01    4.3
dtype: float64
--- UNEMPLOY Series ---
2024-10-01    6951.0
2024-11-01    7089.0
2024-12-01    6920.0
2025-01-01    6865.0
2025-02-01    7104.0
2025-03-01    7132.0
2025-04-01    7155.0
2025-05-01    7248.0
2025-06-01    7054.0
2025-07-01    7272.0
2025-08-01    7380.0
2025-09-01    7605.0
2025-10-01       NaN
2025-11-01    7781.0
2025-12-01    7503.0
2026-01-01    7368.0
2026-02-01    7571.0
2026-03-01    7239.0
2026-04-01    7373.0
2026-05-01    7307.0
2026-06-01    7094.0
2026-07-01    6916.0
2026-08-01    7031.0
2026-09-01    7109.0
dtype: float64
--- PAYEMS Series ---
2024-10-01    157945.0
2024-11-01    158079.0
2024-12-01    158316.0
2025-01-01    158268.0
2025-02-01    158310.0
2025-03-01    158377.0
2025-04-01    158485.0
2025-05-01    158498.0
2025-06-01    158478.0
2025-07-01    158542.0
2025-08-01    158472.0
2025-09-01    158548.0
2025-10-01    158408.0
2025-11-01    158449.0
2025-12-01    158432.0
2026-01-01    158592.0
2026-02-01    158436.0
2026-03-01    158650.0
2026-04-01    158798.0
2026-05-01    158861.0
2026-06-01    158892.0
2026-07-01    158882.0
2026-08-01    159015.0
2026-09-01    159044.0
dtype: float64
--- CEU4348400001 Series ---
2024-10-01    1510.6
2024-11-01    1508.5
2024-12-01    1497.8
2025-01-01    1474.0
2025-02-01    1464.3
2025-03-01    1469.0
2025-04-01    1476.7
2025-05-01    1487.0
2025-06-01    1494.2
2025-07-01    1499.3
2025-08-01    1501.9
2025-09-01    1486.5
2025-10-01    1485.2
2025-11-01    1475.6
2025-12-01    1470.6
2026-01-01    1446.2
2026-02-01    1440.5
2026-03-01    1442.0
2026-04-01    1457.0
2026-05-01    1467.6
2026-06-01    1475.2
2026-07-01    1480.6
2026-08-01    1487.9
2026-09-01    1488.2
dtype: float64
--- LNS11300001 Series ---
2024-10-01    68.1
2024-11-01    67.9
2024-12-01    67.9
2025-01-01    68.0
2025-02-01    67.7
2025-03-01    67.8
2025-04-01    68.0
2025-05-01    67.8
2025-06-01    67.8
2025-07-01    67.7
2025-08-01    67.9
2025-09-01    67.8
2025-10-01     NaN
2025-11-01    67.7
2025-12-01    67.7
2026-01-01    67.3
2026-02-01    67.2
2026-03-01    67.0
2026-04-01    67.0
2026-05-01    67.2
2026-06-01    66.8
2026-07-01    66.8
2026-08-01    67.2
2026-09-01    67.2
dtype: float64
--- LNS11300002 Series ---
2024-10-01    57.3
2024-11-01    57.3
2024-12-01    57.3
2025-01-01    57.5
2025-02-01    57.5
2025-03-01    57.4
2025-04-01    57.5
2025-05-01    57.2
2025-06-01    57.0
2025-07-01    57.1
2025-08-01    57.0
2025-09-01    57.4
2025-10-01     NaN
2025-11-01    57.4
2025-12-01    57.3
2026-01-01    57.2
2026-02-01    57.2
2026-03-01    57.1
2026-04-01    57.0
2026-05-01    56.9
2026-06-01    56.6
2026-07-01    56.4
2026-08-01    56.5
2026-09-01    56.7
dtype: float64
--- LNS11300032 Series ---
2024-10-01    62.6
2024-11-01    62.2
2024-12-01    62.4
2025-01-01    62.4
2025-02-01    62.6
2025-03-01    60.9
2025-04-01    61.2
2025-05-01    61.7
2025-06-01    60.9
2025-07-01    61.2
2025-08-01    61.5
2025-09-01    61.9
2025-10-01     NaN
2025-11-01    62.5
2025-12-01    62.4
2026-01-01    62.6
2026-02-01    63.7
2026-03-01    63.3
2026-04-01    61.9
2026-05-01    62.1
2026-06-01    61.3
2026-07-01    60.6
2026-08-01    60.6
2026-09-01    61.9
dtype: float64
--- LNS11300012 Series ---
2024-10-01    35.9
2024-11-01    36.3
2024-12-01    37.4
2025-01-01    36.2
2025-02-01    37.1
2025-03-01    37.4
2025-04-01    36.7
2025-05-01    36.0
2025-06-01    35.1
2025-07-01    35.0
2025-08-01    34.8
2025-09-01    36.3
2025-10-01     NaN
2025-11-01    36.3

In [41]:
current_data

{'DEXUSEU': 1999-01-04    1.1812
 1999-01-05    1.1760
 1999-01-06    1.1636
 1999-01-07    1.1672
 1999-01-08    1.1554
                ...
 2026-09-28    1.1367
 2026-09-29    1.1336
 2026-09-30    1.1345
 2026-10-01    1.1232
 2026-10-02    1.1259
 Length: 7240, dtype: float64,
 'DEXJPUS': 1990-01-01       NaN
 1990-01-02    146.25
 1990-01-03    145.70
 1990-01-04    143.37
 1990-01-05    143.82
                ...
 2026-09-28    157.44
 2026-09-29    157.50
 2026-09-30    157.25
 2026-10-01    157.63
 2026-10-02    157.81
 Length: 9590, dtype: float64,
 'DEXUSUK': 1990-01-01       NaN
 1990-01-02    1.6110
 1990-01-03    1.6100
 1990-01-04    1.6293
 1990-01-05    1.6370
                ...
 2026-09-28    1.3257
 2026-09-29    1.3212
 2026-09-30    1.3267
 2026-10-01    1.3196
 2026-10-02    1.3234
 Length: 9590, dtype: float64,
 'DEXUSAL': 1990-01-01       NaN
 1990-01-02    0.7855
 1990-01-03    0.7818
 1990-01-04    0.7867
 1990-01-05    0.7860
                ...
 2026-09-28    0.7020
 2026-09-29    0.6979
 2026-09-30    0.6952
 2026-10-01    0.6911
 2026-10-02    0.6953
 Length: 9590, dtype: float64,
 'DEXCHUS': 1990-01-01       NaN
 1990-01-02    4.7339
 1990-01-03    4.7339
 1990-01-04    4.7339
 1990-01-05    4.7339
                ...
 2026-09-28    6.7103
 2026-09-29    6.7030
 2026-09-30    6.7045
 2026-10-01    6.7038
 2026-10-02    6.7038
 Length: 9590, dtype: float64,
 'DEXINUS': 1990-01-01      NaN
 1990-01-02    16.96
 1990-01-03    16.99
 1990-01-04    16.94
 1990-01-05    16.93
               ...
 2026-09-28    95.98
 2026-09-29    95.98
 2026-09-30    95.83
 2026-10-01    96.32
 2026-10-02    96.31
 Length: 9590, dtype: float64,
 'DEXBZUS': 1995-01-02    0.8440
 1995-01-03    0.8450
 1995-01-04    0.8450
 1995-01-05    0.8430
 1995-01-06    0.8400
                ...
 2026-09-28    5.2198
 2026-09-29    5.2323
 2026-09-30    5.1818
 2026-10-01    5.2329
 2026-10-02    5.2222
 Length: 8285, dtype: float64,
 'DEXCAUS': 1990-01-01       NaN
 1990-01-02    1.1605
 1990-01-03    1.1613
 1990-01-04    1.1614
 1990-01-05    1.1600
                ...
 2026-09-28    1.4169
 2026-09-29    1.4189
 2026-09-30    1.4210
 2026-10-01    1.4253
 2026-10-02    1.4253
 Length: 9590, dtype: float64,
 'DEXSZUS': 1990-01-01       NaN
 1990-01-02    1.5768
 1990-01-03    1.5785
 1990-01-04    1.5420
 1990-01-05    1.5370
                ...
 2026-09-28    0.8322
 2026-09-29    0.8347
 2026-09-30    0.8348
 2026-10-01    0.8314
 2026-10-02    0.8293
 Length: 9590, dtype: float64,
 'DEXHKUS': 1990-01-01       NaN
 1990-01-02    7.8120
 1990-01-03    7.8140
 1990-01-04    7.8150
 1990-01-05    7.8140
                ...
 2026-09-28    7.8447
 2026-09-29    7.8463
 2026-09-30    7.8467
 2026-10-01    7.8453
 2026-10-02    7.8470
 Length: 9590, dtype: float64,
 'DEXMXUS': 1993-11-08     3.1520
 1993-11-09     3.2400
 1993-11-10     3.2400
 1993-11-11        NaN
 1993-11-12     3.2400
                ...
 2026-09-28    17.8439
 2026-09-29    18.0534
 2026-09-30    18.0609
 2026-10-01    18.4001
 2026-10-02    18.1920
 Length: 8585, dtype: float64,
 'DEXUSNZ': 1990-01-01       NaN
 1990-01-02    0.5930
 1990-01-03    0.5940
 1990-01-04    0.5973
 1990-01-05    0.5970
                ...
 2026-09-28    0.5668
 2026-09-29    0.5635
 2026-09-30    0.5640
 2026-10-01    0.5600
 2026-10-02    0.5612
 Length: 9590, dtype: float64,
 'T10Y2Y': 1990-01-01     NaN
 1990-01-02    0.07
 1990-01-03    0.05
 1990-01-04    0.06
 1990-01-05    0.09
               ...
 2026-10-01    0.46
 2026-10-02    0.45
 2026-10-05    0.47
 2026-10-06    0.48
 2026-10-07    0.51
 Length: 9593, dtype: float64,
 'T10Y3M': 1990-01-01     NaN
 1990-01-02    0.11
 1990-01-03    0.10
 1990-01-04    0.14
 1990-01-05    0.20
               ...
 2026-10-01    1.07
 2026-10-02    1.09
 2026-10-05    1.09
 2026-10-06    1.06
 2026-10-07    1.06
 Length: 9593, dtype: float64,
 'T10YIE': 2003-01-02    1.64
 2003-01-03    1.62
 2003-01-06    1.63
 2003-01-07    1.62
 2003-01-08    1.71
               ...
 2026-10-01    2.36
 2026-10-02    2.36
 2026-10-05    2.36
 2026-10-06    2.36
 2026-10-07    2.36
 Length: 6200, dtype: float64,
 'TERMCBCCALLNS': 1994-11-01    15.69
 1994-12-01      NaN
 1995-01-01      NaN
 1995-02-01    16.10
 1995-03-01      NaN
               ...
 2026-04-01      NaN
 2026-05-01    20.94
 2026-06-01      NaN
 2026-07-01      NaN
 2026-08-01    21.19
 Length: 382, dtype: float64,
 'TOTALSL': 1990-01-01     797714.86
 1990-02-01     798773.19
 1990-03-01     798748.09
 1990-04-01     798747.01
 1990-05-01     799751.03
                  ...
 2026-04-01    5152527.91
 2026-05-01    5155421.48
 2026-06-01    5170757.74
 2026-07-01    5188497.83
 2026-08-01    5196778.44
 Length: 440, dtype: float64,
 'CPIAUCSL': 1990-01-01    127.500
 1990-02-01    128.000
 1990-03-01    128.600
 1990-04-01    128.900
 1990-05-01    129.100
                ...
 2026-04-01    332.407
 2026-05-01    333.979
 2026-06-01    332.568
 2026-07-01    332.813
 2026-08-01    334.131
 Length: 440, dtype: float64,
 'PCEPI': 1990-01-01     58.553
 1990-02-01     58.811
 1990-03-01     59.033
 1990-04-01     59.157
 1990-05-01     59.290
                ...
 2026-04-01    130.672
 2026-05-01    131.241
 2026-06-01    131.106
 2026-07-01    131.172
 2026-08-01    131.579
 Length: 440, dtype: float64,
 'CORESTICKM159SFRBATL': 1990-01-01    4.905908
 1990-02-01    4.917559
 1990-03-01    5.191525
 1990-04-01    5.276985
 1990-05-01    5.166732
                 ...
 2026-04-01    3.038932
 2026-05-01    3.091257
 2026-06-01    2.806860
 2026-07-01    2.715836
 2026-08-01    2.700641
 Length: 440, dtype: float64,
 'DRCCLACBS': 1991-01-01    5.26
 1991-04-01    5.48
 1991-07-01    5.35
 1991-10-01    5.32
 1992-01-01    5.27
               ...
 2025-04-01    3.04
 2025-07-01    2.99
 2025-10-01    2.95
 2026-01-01    2.91
 2026-04-01    2.85
 Length: 142, dtype: float64,
 'DRSFRMACBS': 1991-01-01    3.10
 1991-04-01    3.17
 1991-07-01    3.22
 1991-10-01    3.28
 1992-01-01    3.13
               ...
 2025-04-01    1.78
 2025-07-01    1.78
 2025-10-01    1.79
 2026-01-01    1.88
 2026-04-01    1.86
 Length: 142, dtype: float64,
 'DRCLACBS': 1990-01-01    3.60
 1990-04-01    3.61
 1990-07-01    3.81
 1990-10-01    4.01
 1991-01-01    4.12
               ...
 2025-04-01    2.75
 2025-07-01    2.72
 2025-10-01    2.63
 2026-01-01    2.64
 2026-04-01    2.62
 Length: 146, dtype: float64,
 'DRBLACBS': 1990-01-01    5.17
 1990-04-01    5.35
 1990-07-01    5.46
 1990-10-01    6.27
 1991-01-01    6.29
               ...
 2025-04-01    1.29
 2025-07-01    1.33
 2025-10-01    1.34
 2026-01-01    1.33
 2026-04-01    1.27
 Length: 146, dtype: float64,
 'DRFLACBS': 1991-01-01    4.24
 1991-04-01    4.27
 1991-07-01    4.39
 1991-10-01    4.38
 1992-01-01    4.25
               ...
 2025-04-01    1.33
 2025-07-01    1.32
 2025-10-01    1.31
 2026-01-01    1.34
 2026-04-01    1.33
 Length: 142, dtype: float64,
 'DALLCCACBEP': 1991-01-01     6838.0
 1991-04-01     6921.0
 1991-07-01     7101.0
 1991-10-01     7371.0
 1992-01-01     6875.0
                ...
 2025-04-01    29647.0
 2025-07-01    31480.0
 2025-10-01    33040.0
 2026-01-01    31054.0
 2026-04-01    29013.0
 Length: 142, dtype: float64,
 'USPBS': 1990-01-01    10821.0
 1990-02-01    10886.0
 1990-03-01    10920.0
 1990-04-01    10919.0
 1990-05-01    10909.0
                ...
 2026-05-01    22466.0
 2026-06-01    22502.0
 2026-07-01    22496.0
 2026-08-01    22491.0
 2026-09-01    22482.0
 Length: 441, dtype: float64,
 'CES6054120001': 1990-01-01     652.8
 1990-02-01     654.2
 1990-03-01     660.2
 1990-04-01     663.2
 1990-05-01     666.5
                ...
 2026-05-01    1124.0
 2026-06-01    1124.8
 2026-07-01    1124.7
 2026-08-01    1122.5
 2026-09-01    1121.2
 Length: 441, dtype: float64,
 'USCONS': 1990-01-01    5422.0
 1990-02-01    5416.0
 1990-03-01    5392.0
 1990-04-01    5355.0
 1990-05-01    5321.0
                ...
 2026-05-01    8316.0
 2026-06-01    8319.0
 2026-07-01    8337.0
 2026-08-01    8353.0
 2026-09-01    8364.0
 Length: 441, dtype: float64,
 'UNRATE': 1990-01-01    5.4
 1990-02-01    5.3
 1990-03-01    5.2
 1990-04-01    5.4
 1990-05-01    5.4
              ...
 2026-05-01    4.3
 2026-06-01    4.2
 2026-07-01    4.1
 2026-08-01    4.1
 2026-09-01    4.2
 Length: 441, dtype: float64,
 'JTSJOR': 2000-12-01    3.7
 2001-01-01    3.8
 2001-02-01    3.7
 2001-03-01    3.5
 2001-04-01    3.4
              ...
 2026-04-01    4.6
 2026-05-01    4.5
 2026-06-01    4.3
 2026-07-01    4.4
 2026-08-01    4.3
 Length: 309, dtype: float64,
 'UNEMPLOY': 1990-01-01    6752.0
 1990-02-01    6651.0
 1990-03-01    6598.0
 1990-04-01    6797.0
 1990-05-01    6742.0
                ...
 2026-05-01    7307.0
 2026-06-01    7094.0
 2026-07-01    6916.0
 2026-08-01    7031.0
 2026-09-01    7109.0
 Length: 441, dtype: float64,
 'PAYEMS': 1990-01-01    109196.0
 1990-02-01    109436.0
 1990-03-01    109640.0
 1990-04-01    109674.0
 1990-05-01    109828.0
                 ...
 2026-05-01    158861.0
 2026-06-01    158892.0
 2026-07-01    158882.0
 2026-08-01    159015.0
 2026-09-01    159044.0
 Length: 441, dtype: float64,
 'CEU4348400001': 1990-01-01    1104.7
 1990-02-01    1108.1
 1990-03-01    1115.2
 1990-04-01    1115.6
 1990-05-01    1123.5
                ...
 2026-05-01    1467.6
 2026-06-01    1475.2
 2026-07-01    1480.6
 2026-08-01    1487.9
 2026-09-01    1488.2
 Length: 441, dtype: float64,
 'LNS11300001': 1990-01-01    76.7
 1990-02-01    76.6
 1990-03-01    76.6
 1990-04-01    76.4
 1990-05-01    76.4
               ...
 2026-05-01    67.2
 2026-06-01    66.8
 2026-07-01    66.8
 2026-08-01    67.2
 2026-09-01    67.2
 Length: 441, dtype: float64,
 'LNS11300002': 1990-01-01    57.7
 1990-02-01    57.6
 1990-03-01    57.6
 1990-04-01    57.5
 1990-05-01    57.7
               ...
 2026-05-01    56.9
 2026-06-01    56.6
 2026-07-01    56.4
 2026-08-01    56.5
 2026-09-01    56.7
 Length: 441, dtype: float64,
 'LNS11300032': 1990-01-01    61.4
 1990-02-01    61.7
 1990-03-01    61.3
 1990-04-01    60.9
 1990-05-01    61.5
               ...
 2026-05-01    62.1
 2026-06-01    61.3
 2026-07-01    60.6
 2026-08-01    60.6
 2026-09-01    61.9
 Length: 441, dtype: float64,
 'LNS11300012': 1990-01-01    54.9
 1990-02-01    54.3
 1990-03-01    55.0
 1990-04-01    54.6
 1990-05-01    54.2
               ...
 2026-05-01    35.7
 2026-06-01    35.4
 2026-07-01    34.9
 2026-08-01    35.7
 2026-09-01    37.0
 Length: 441, dtype: float64,
 'ICSA': 1990-01-06    355000.0
 1990-01-13    369000.0
 1990-01-20    375000.0
 1990-01-27    345000.0
 1990-02-03    368000.0
                 ...
 2026-09-05    207000.0
 2026-09-12    198000.0
 2026-09-19    198000.0
 2026-09-26    199000.0
 2026-10-03    197000.0
 Length: 1918, dtype: float64,
 'M1V': 1990-01-01    7.356
 1990-04-01    7.391
 1990-07-01    7.377
 1990-10-01    7.303
 1991-01-01    7.247
               ...
 2025-04-01    1.640
 2025-07-01    1.654
 2025-10-01    1.653
 2026-01-01    1.652
 2026-04-01    1.656
 Length: 146, dtype: float64,
 'M2V': 1990-01-01    1.848
 1990-04-01    1.859
 1990-07-01    1.856
 1990-10-01    1.839
 1991-01-01    1.827
               ...
 2025-04-01    1.402
 2025-07-01    1.411
 2025-10-01    1.411
 2026-01-01    1.415
 2026-04-01    1.418
 Length: 146, dtype: float64,
 'BOGMBASE': 1990-01-01     293.1
 1990-02-01     287.7
 1990-03-01     292.4
 1990-04-01     297.4
 1990-05-01     297.3
                ...
 2026-04-01    5470.4
 2026-05-01    5538.9
 2026-06-01    5488.4
 2026-07-01    5523.9
 2026-08-01    5411.6
 Length: 440, dtype: float64,
 'BOGMBBM': 1990-01-01      36.3
 1990-02-01      33.0
 1990-03-01      35.6
 1990-04-01      37.5
 1990-05-01      34.9
                ...
 2026-04-01    3018.1
 2026-05-01    3078.8
 2026-06-01    3018.8
 2026-07-01    3051.5
 2026-08-01    2936.0
 Length: 440, dtype: float64,
 'MBCURRCIR': 1990-01-01     256.8
 1990-02-01     254.7
 1990-03-01     256.8
 1990-04-01     259.9
 1990-05-01     262.4
                ...
 2026-04-01    2452.4
 2026-05-01    2460.1
 2026-06-01    2469.6
 2026-07-01    2472.3
 2026-08-01    2475.6
 Length: 440, dtype: float64,
 'PPIACO': 1990-01-01    114.900
 1990-02-01    114.400
 1990-03-01    114.200
 1990-04-01    114.100
 1990-05-01    114.600
                ...
 2026-04-01    282.722
 2026-05-01    290.200
 2026-06-01    286.023
 2026-07-01    285.181
 2026-08-01    287.928
 Length: 440, dtype: float64,
 'PCUOMFGOMFG': 1990-01-01    112.700
 1990-02-01    112.200
 1990-03-01    112.300
 1990-04-01    112.600
 1990-05-01    113.100
                ...
 2026-04-01    273.056
 2026-05-01    281.390
 2026-06-01    276.061
 2026-07-01    275.295
 2026-08-01    279.699
 Length: 440, dtype: float64,
 'PCUAINFOAINFO': 2006-12-01    100.000
 2007-01-01     99.900
 2007-02-01    100.100
 2007-03-01    100.300
 2007-04-01    100.600
                ...
 2026-04-01    119.016
 2026-05-01    119.343
 2026-06-01    119.660
 2026-07-01    120.367
 2026-08-01    119.702
 Length: 237, dtype: float64,
 'PCUATRNWRATRNWR': 2006-12-01    100.000
 2007-01-01    101.700
 2007-02-01    101.900
 2007-03-01    102.300
 2007-04-01    102.800
                ...
 2026-04-01    190.570
 2026-05-01    192.597
 2026-06-01    192.664
 2026-07-01    190.930
 2026-08-01    193.183
 Length: 237, dtype: float64,
 'WFRBST01134': 1990-01-01    22.8
 1990-04-01    22.9
 1990-07-01    22.4
 1990-10-01    22.9
 1991-01-01    23.2
               ...
 2025-04-01    31.1
 2025-07-01    31.5
 2025-10-01    31.8
 2026-01-01    31.7
 2026-04-01    32.5
 Length: 146, dtype: float64,
 'WFRBLT01026': 1990-01-01     4754803.0
 1990-04-01     4846163.0
 1990-07-01     4721261.0
 1990-10-01     4902343.0
 1991-01-01     5087571.0
                  ...
 2025-04-01    51567387.0
 2025-07-01    53941887.0
 2025-10-01    54789114.0
 2026-01-01    54829515.0
 2026-04-01    60313023.0
 Length: 146, dtype: float64,
 'WFRBSN40188': 1990-01-01    36.0
 1990-04-01    36.1
 1990-07-01    36.6
 1990-10-01    36.3
 1991-01-01    36.2
               ...
 2025-04-01    30.1
 2025-07-01    29.5
 2025-10-01    29.3
 2026-01-01    29.5
 2026-04-01    28.8
 Length: 146, dtype: float64,
 'WFRBSB50215': 1990-01-01    3.5
 1990-04-01    3.4
 1990-07-01    3.5
 1990-10-01    3.6
 1991-01-01    3.5
              ...
 2025-04-01    2.4
 2025-07-01    2.4
 2025-10-01    2.4
 2026-01-01    2.4
 2026-04-01    2.3
 Length: 146, dtype: float64,
 'GASDESW': 1994-03-21    1.106
 1994-03-28    1.107
 1994-04-04    1.109
 1994-04-11    1.108
 1994-04-18    1.105
               ...
 2026-09-07    5.967
 2026-09-14    6.285
 2026-09-21    6.529
 2026-09-28    6.382
 2026-10-05    6.199
 Length: 1699, dtype: float64,
 'APU000072610': 1990-01-01    0.081
 1990-02-01    0.081
 1990-03-01    0.081
 1990-04-01    0.082
 1990-05-01    0.082
               ...
 2026-04-01    0.194
 2026-05-01    0.196
 2026-06-01    0.198
 2026-07-01    0.197
 2026-08-01    0.196
 Length: 440, dtype: float64,
 'PNRGINDEXM': 1992-01-01     44.452235
 1992-02-01     44.012857
 1992-03-01     43.828585
 1992-04-01     46.155698
 1992-05-01     48.205262
                  ...
 2026-03-01    242.277533
 2026-04-01    229.383300
 2026-05-01    231.982938
 2026-06-01    198.797740
 2026-07-01    198.703805
 Length: 415, dtype: float64,
 'GDPC1': 1990-01-01    10047.386
 1990-04-01    10083.855
 1990-07-01    10090.569
 1990-10-01     9998.704
 1991-01-01     9951.916
                 ...
 2025-04-01    23884.563
 2025-07-01    24112.966
 2025-10-01    24125.479
 2026-01-01    24274.383
 2026-04-01    24408.011
 Length: 146, dtype: float64,
 'PSAVERT': 1990-01-01    7.9
 1990-02-01    8.5
 1990-03-01    8.3
 1990-04-01    8.7
 1990-05-01    8.7
              ...
 2026-04-01    4.4
 2026-05-01    4.4
 2026-06-01    4.4
 2026-07-01    4.6
 2026-08-01    4.1
 Length: 440, dtype: float64,
 'TLCOMCONS': 2002-01-01     68254.0
 2002-02-01     65840.0
 2002-03-01     66722.0
 2002-04-01     64879.0
 2002-05-01     62741.0
                 ...
 2026-04-01    123156.0
 2026-05-01    123787.0
 2026-06-01    123315.0
 2026-07-01    123001.0
 2026-08-01    122810.0
 Length: 296, dtype: float64,
 'TLRESCONS': 2002-01-01    382979.0
 2002-02-01    391434.0
 2002-03-01    390942.0
 2002-04-01    404255.0
 2002-05-01    399164.0
                 ...
 2026-04-01    894242.0
 2026-05-01    887277.0
 2026-06-01    894328.0
 2026-07-01    884995.0
 2026-08-01    894597.0
 Length: 296, dtype: float64}

In [42]:
test_series = current_data.get(fred_ids[0])
test_series.tail(24)

2026-09-01    1.1593
2026-09-02    1.1592
2026-09-03    1.1623
2026-09-04    1.1618
2026-09-07       NaN
2026-09-08    1.1627
2026-09-09    1.1627
2026-09-10    1.1629
2026-09-11    1.1604
2026-09-14    1.1549
2026-09-15    1.1542
2026-09-16    1.1538
2026-09-17    1.1479
2026-09-18    1.1464
2026-09-21    1.1469
2026-09-22    1.1432
2026-09-23    1.1394
2026-09-24    1.1373
2026-09-25    1.1400
2026-09-28    1.1367
2026-09-29    1.1336
2026-09-30    1.1345
2026-10-01    1.1232
2026-10-02    1.1259
dtype: float64

In [43]:
test_series.to_frame()

                 0
1999-01-04  1.1812
1999-01-05  1.1760
1999-01-06  1.1636
1999-01-07  1.1672
1999-01-08  1.1554
...            ...
2026-09-28  1.1367
2026-09-29  1.1336
2026-09-30  1.1345
2026-10-01  1.1232
2026-10-02  1.1259

[7240 rows x 1 columns]

In [44]:
#convert fred series to dataframe with date and value columns
test_df = test_series.to_frame().reset_index()
test_df.columns = ['date', 'value']
test_df.tail(24)

           date   value
7216 2026-09-01  1.1593
7217 2026-09-02  1.1592
7218 2026-09-03  1.1623
7219 2026-09-04  1.1618
7220 2026-09-07     NaN
7221 2026-09-08  1.1627
7222 2026-09-09  1.1627
7223 2026-09-10  1.1629
7224 2026-09-11  1.1604
7225 2026-09-14  1.1549
7226 2026-09-15  1.1542
7227 2026-09-16  1.1538
7228 2026-09-17  1.1479
7229 2026-09-18  1.1464
7230 2026-09-21  1.1469
7231 2026-09-22  1.1432
7232 2026-09-23  1.1394
7233 2026-09-24  1.1373
7234 2026-09-25  1.1400
7235 2026-09-28  1.1367
7236 2026-09-29  1.1336
7237 2026-09-30  1.1345
7238 2026-10-01  1.1232
7239 2026-10-02  1.1259

In [45]:
def convert_series_to_df(series):
    df = series.to_frame().reset_index()
    df.columns = ['date', 'value']
    return df

In [46]:
test_frames = {}
for id, series in current_data.items():
    test_frames[id] = convert_series_to_df(series)

In [47]:
#now let's use the pgsql class from pgsql.py to write these dataframes to our sql db
from db.pgsql import pgsql
from sqlalchemy import text

In [48]:
db = pgsql()
engine = db.get_engine()

with engine.begin() as connection:
    for id in (fred_ids + ['CBBCHUSD','CBBTCUSD', 'CBETHUSD', 'CBLTCUSD']):
        query = text(f'DROP TABLE IF EXISTS "{id}"')
        connection.execute(query)
        query = text(f'DROP TABLE IF EXISTS "{id.lower()}"')
        connection.execute(query)

for id, frame in test_frames.items():
    db.set_table_name(id.lower())
    db.set_pdf(frame)
    db.write_pdf_to_sql()

In [49]:
db.set_table_name("fred_series_info")

fred_series_info = db.get_df_from_sql()
fred_series_info.head(3)

,id,realtime_start,realtime_end,title,observation_start,observation_end,frequency,frequency_short,units,units_short,seasonal_adjustment,seasonal_adjustment_short,last_updated,popularity,notes
0,DEXUSEU,2026-09-21,2026-09-21,U.S. Dollars to Euro Spot Exchange Rate,1999-01-04,2026-09-18,Daily,D,U.S. Dollars to One Euro,U.S. $ to 1 Euro,Not Seasonally Adjusted,NSA,2026-09-21 20:16:44+00:00,76,data source (https://www.federalreserve.gov/ap...
1,DEXJPUS,2026-09-22,2026-09-22,Japanese Yen to U.S. Dollar Spot Exchange Rate,1971-01-04,2026-09-18,Daily,D,Japanese Yen to One U.S. Dollar,Japanese Yen to 1 U.S. $,Not Seasonally Adjusted,NSA,2026-09-21 20:16:27+00:00,76,data source (https://www.federalreserve.gov/ap...
2,DEXUSUK,2026-09-21,2026-09-21,U.S. Dollars to U.K. Pound Sterling Spot Excha...,1971-01-04,2026-09-18,Daily,D,U.S. Dollars to One U.K. Pound Sterling,U.S. $ to 1 U.K. Pound Sterling,Not Seasonally Adjusted,NSA,2026-09-21 20:16:32+00:00,66,data source (https://www.federalreserve.gov/ap...

In [50]:
with engine.begin() as connection:
    query = text("SELECT MAX(date) FROM unrate")
    result = connection.execute(query)
    max_date = result.scalar()
    print(max_date)

2026-09-01 00:00:00

In [51]:
type(max_date)

datetime.datetime

In [52]:
pd.Timestamp(max_date)

Timestamp('2026-09-01 00:00:00')

In [53]:
today

Timestamp('2026-10-08 13:42:38.063292')

In [54]:
date_delta_dict = {'D': pd.Timedelta(days=1),
                   'W': pd.Timedelta(weeks=1),
                   'M': pd.Timedelta(days=30),
                   'Q': pd.Timedelta(days=91)}

In [55]:
date_delta_dict['D'] + pd.Timestamp(max_date)

Timestamp('2026-09-02 00:00:00')

In [56]:
today > date_delta_dict['D'] + pd.Timestamp(max_date)

True

In [57]:
with engine.begin() as connection:
    for id in fred_ids:
        max_date_query = text(f"SELECT MAX(date) FROM {id.lower()}")
        result = connection.execute(max_date_query)
        max_date = pd.Timestamp(result.scalar())
        print(f"Max date for {id}: {max_date}")
        frequency_short_query = text(f"SELECT frequency_short FROM fred_series_info WHERE id = '{id}' LIMIT 1")
        frequency_short_result = connection.execute(frequency_short_query)
        frequency_short = frequency_short_result.scalar()
        print(f"Frequency short for {id}: {frequency_short}")
        next_read_day = max_date + date_delta_dict[frequency_short]
        print(f"Next read day for {id}: {next_read_day}")
        if next_read_day <= today:
            print(f"Fetching data for {id} starting from {next_read_day}")
            #next_start_date = next_read_day
            #max_date + pd.Timedelta(days=1)
            temp_fresh_data = fred.get_series(id, 
                                              observation_start=next_read_day.strftime('%Y-%m-%d'),
                                              observation_end=today_formatted)
            print(f"--- {id} Series ---")
            if temp_fresh_data.empty:
                print(f"No new data returned for {id}, skipping")
                continue
            db.set_table_name(id.lower())
            df_to_append = convert_series_to_df(temp_fresh_data)
            df_to_append = df_to_append[df_to_append['date'] > pd.Timestamp(max_date)]
            #df_to_append['date'] = pd.to_datetime(df_to_append['date'])
            if len(df_to_append) == 0:
                print(f"No new data to append for {id}, skipping")
                continue
            db.set_pdf(df_to_append)
            db.write_pdf_to_sql(if_exists='append')
            sleep(1)

Max date for DEXUSEU: 2026-10-02 00:00:00
Frequency short for DEXUSEU: D
Next read day for DEXUSEU: 2026-10-03 00:00:00
Fetching data for DEXUSEU starting from 2026-10-03 00:00:00
--- DEXUSEU Series ---
No new data returned for DEXUSEU, skipping
Max date for DEXJPUS: 2026-10-02 00:00:00
Frequency short for DEXJPUS: D
Next read day for DEXJPUS: 2026-10-03 00:00:00
Fetching data for DEXJPUS starting from 2026-10-03 00:00:00
--- DEXJPUS Series ---
No new data returned for DEXJPUS, skipping
Max date for DEXUSUK: 2026-10-02 00:00:00
Frequency short for DEXUSUK: D
Next read day for DEXUSUK: 2026-10-03 00:00:00
Fetching data for DEXUSUK starting from 2026-10-03 00:00:00
--- DEXUSUK Series ---
No new data returned for DEXUSUK, skipping
Max date for DEXUSAL: 2026-10-02 00:00:00
Frequency short for DEXUSAL: D
Next read day for DEXUSAL: 2026-10-03 00:00:00
Fetching data for DEXUSAL starting from 2026-10-03 00:00:00
--- DEXUSAL Series ---
No new data returned for DEXUSAL, skipping
Max date for DEXCHUS: 2026-10-02 00:00:00
Frequency short for DEXCHUS: D
Next read day for DEXCHUS: 2026-10-03 00:00:00
Fetching data for DEXCHUS starting from 2026-10-03 00:00:00
--- DEXCHUS Series ---
No new data returned for DEXCHUS, skipping
Max date for DEXINUS: 2026-10-02 00:00:00
Frequency short for DEXINUS: D
Next read day for DEXINUS: 2026-10-03 00:00:00
Fetching data for DEXINUS starting from 2026-10-03 00:00:00
--- DEXINUS Series ---
No new data returned for DEXINUS, skipping
Max date for DEXBZUS: 2026-10-02 00:00:00
Frequency short for DEXBZUS: D
Next read day for DEXBZUS: 2026-10-03 00:00:00
Fetching data for DEXBZUS starting from 2026-10-03 00:00:00
--- DEXBZUS Series ---
No new data returned for DEXBZUS, skipping
Max date for DEXCAUS: 2026-10-02 00:00:00
Frequency short for DEXCAUS: D
Next read day for DEXCAUS: 2026-10-03 00:00:00
Fetching data for DEXCAUS starting from 2026-10-03 00:00:00
--- DEXCAUS Series ---
No new data returned for DEXCAUS, skipping
Max date for DEXSZUS: 2026-10-02 00:00:00
Frequency short for DEXSZUS: D
Next read day for DEXSZUS: 2026-10-03 00:00:00
Fetching data for DEXSZUS starting from 2026-10-03 00:00:00
--- DEXSZUS Series ---
No new data returned for DEXSZUS, skipping
Max date for DEXHKUS: 2026-10-02 00:00:00
Frequency short for DEXHKUS: D
Next read day for DEXHKUS: 2026-10-03 00:00:00
Fetching data for DEXHKUS starting from 2026-10-03 00:00:00
--- DEXHKUS Series ---
No new data returned for DEXHKUS, skipping
Max date for DEXMXUS: 2026-10-02 00:00:00
Frequency short for DEXMXUS: D
Next read day for DEXMXUS: 2026-10-03 00:00:00
Fetching data for DEXMXUS starting from 2026-10-03 00:00:00
--- DEXMXUS Series ---
No new data returned for DEXMXUS, skipping
Max date for DEXUSNZ: 2026-10-02 00:00:00
Frequency short for DEXUSNZ: D
Next read day for DEXUSNZ: 2026-10-03 00:00:00
Fetching data for DEXUSNZ starting from 2026-10-03 00:00:00
--- DEXUSNZ Series ---
No new data returned for DEXUSNZ, skipping
Max date for T10Y2Y: 2026-10-07 00:00:00
Frequency short for T10Y2Y: D
Next read day for T10Y2Y: 2026-10-08 00:00:00
Fetching data for T10Y2Y starting from 2026-10-08 00:00:00
--- T10Y2Y Series ---
No new data returned for T10Y2Y, skipping
Max date for T10Y3M: 2026-10-07 00:00:00
Frequency short for T10Y3M: D
Next read day for T10Y3M: 2026-10-08 00:00:00
Fetching data for T10Y3M starting from 2026-10-08 00:00:00
--- T10Y3M Series ---
No new data returned for T10Y3M, skipping
Max date for T10YIE: 2026-10-07 00:00:00
Frequency short for T10YIE: D
Next read day for T10YIE: 2026-10-08 00:00:00
Fetching data for T10YIE starting from 2026-10-08 00:00:00
--- T10YIE Series ---
No new data returned for T10YIE, skipping
Max date for TERMCBCCALLNS: 2026-08-01 00:00:00
Frequency short for TERMCBCCALLNS: M
Next read day for TERMCBCCALLNS: 2026-08-31 00:00:00
Fetching data for TERMCBCCALLNS starting from 2026-08-31 00:00:00
--- TERMCBCCALLNS Series ---
No new data to append for TERMCBCCALLNS, skipping
Max date for TOTALSL: 2026-08-01 00:00:00
Frequency short for TOTALSL: M
Next read day for TOTALSL: 2026-08-31 00:00:00
Fetching data for TOTALSL starting from 2026-08-31 00:00:00
--- TOTALSL Series ---
No new data to append for TOTALSL, skipping
Max date for CPIAUCSL: 2026-08-01 00:00:00
Frequency short for CPIAUCSL: M
Next read day for CPIAUCSL: 2026-08-31 00:00:00
Fetching data for CPIAUCSL starting from 2026-08-31 00:00:00
--- CPIAUCSL Series ---
No new data to append for CPIAUCSL, skipping
Max date for PCEPI: 2026-08-01 00:00:00
Frequency short for PCEPI: M
Next read day for PCEPI: 2026-08-31 00:00:00
Fetching data for PCEPI starting from 2026-08-31 00:00:00
--- PCEPI Series ---
No new data to append for PCEPI, skipping
Max date for CORESTICKM159SFRBATL: 2026-08-01 00:00:00
Frequency short for CORESTICKM159SFRBATL: M
Next read day for CORESTICKM159SFRBATL: 2026-08-31 00:00:00
Fetching data for CORESTICKM159SFRBATL starting from 2026-08-31 00:00:00
--- CORESTICKM159SFRBATL Series ---
No new data to append for CORESTICKM159SFRBATL, skipping
Max date for DRCCLACBS: 2026-04-01 00:00:00
Frequency short for DRCCLACBS: Q
Next read day for DRCCLACBS: 2026-07-01 00:00:00
Fetching data for DRCCLACBS starting from 2026-07-01 00:00:00
--- DRCCLACBS Series ---
No new data returned for DRCCLACBS, skipping
Max date for DRSFRMACBS: 2026-04-01 00:00:00
Frequency short for DRSFRMACBS: Q
Next read day for DRSFRMACBS: 2026-07-01 00:00:00
Fetching data for DRSFRMACBS starting from 2026-07-01 00:00:00
--- DRSFRMACBS Series ---
No new data returned for DRSFRMACBS, skipping
Max date for DRCLACBS: 2026-04-01 00:00:00
Frequency short for DRCLACBS: Q
Next read day for DRCLACBS: 2026-07-01 00:00:00
Fetching data for DRCLACBS starting from 2026-07-01 00:00:00
--- DRCLACBS Series ---
No new data returned for DRCLACBS, skipping
Max date for DRBLACBS: 2026-04-01 00:00:00
Frequency short for DRBLACBS: Q
Next read day for DRBLACBS: 2026-07-01 00:00:00
Fetching data for DRBLACBS starting from 2026-07-01 00:00:00
--- DRBLACBS Series ---
No new data returned for DRBLACBS, skipping
Max date for DRFLACBS: 2026-04-01 00:00:00
Frequency short for DRFLACBS: Q
Next read day for DRFLACBS: 2026-07-01 00:00:00
Fetching data for DRFLACBS starting from 2026-07-01 00:00:00
--- DRFLACBS Series ---
No new data returned for DRFLACBS, skipping
Max date for DALLCCACBEP: 2026-04-01 00:00:00
Frequency short for DALLCCACBEP: Q
Next read day for DALLCCACBEP: 2026-07-01 00:00:00
Fetching data for DALLCCACBEP starting from 2026-07-01 00:00:00
--- DALLCCACBEP Series ---
No new data returned for DALLCCACBEP, skipping
Max date for USPBS: 2026-09-01 00:00:00
Frequency short for USPBS: M
Next read day for USPBS: 2026-10-01 00:00:00
Fetching data for USPBS starting from 2026-10-01 00:00:00
--- USPBS Series ---
No new data returned for USPBS, skipping
Max date for CES6054120001: 2026-09-01 00:00:00
Frequency short for CES6054120001: M
Next read day for CES6054120001: 2026-10-01 00:00:00
Fetching data for CES6054120001 starting from 2026-10-01 00:00:00
--- CES6054120001 Series ---
No new data returned for CES6054120001, skipping
Max date for USCONS: 2026-09-01 00:00:00
Frequency short for USCONS: M
Next read day for USCONS: 2026-10-01 00:00:00
Fetching data for USCONS starting from 2026-10-01 00:00:00
--- USCONS Series ---
No new data returned for USCONS, skipping
Max date for UNRATE: 2026-09-01 00:00:00
Frequency short for UNRATE: M
Next read day for UNRATE: 2026-10-01 00:00:00
Fetching data for UNRATE starting from 2026-10-01 00:00:00
--- UNRATE Series ---
No new data returned for UNRATE, skipping
Max date for JTSJOR: 2026-08-01 00:00:00
Frequency short for JTSJOR: M
Next read day for JTSJOR: 2026-08-31 00:00:00
Fetching data for JTSJOR starting from 2026-08-31 00:00:00
--- JTSJOR Series ---
No new data to append for JTSJOR, skipping
Max date for UNEMPLOY: 2026-09-01 00:00:00
Frequency short for UNEMPLOY: M
Next read day for UNEMPLOY: 2026-10-01 00:00:00
Fetching data for UNEMPLOY starting from 2026-10-01 00:00:00
--- UNEMPLOY Series ---
No new data returned for UNEMPLOY, skipping
Max date for PAYEMS: 2026-09-01 00:00:00
Frequency short for PAYEMS: M
Next read day for PAYEMS: 2026-10-01 00:00:00
Fetching data for PAYEMS starting from 2026-10-01 00:00:00
--- PAYEMS Series ---
No new data returned for PAYEMS, skipping
Max date for CEU4348400001: 2026-09-01 00:00:00
Frequency short for CEU4348400001: M
Next read day for CEU4348400001: 2026-10-01 00:00:00
Fetching data for CEU4348400001 starting from 2026-10-01 00:00:00
--- CEU4348400001 Series ---
No new data returned for CEU4348400001, skipping
Max date for LNS11300001: 2026-09-01 00:00:00
Frequency short for LNS11300001: M
Next read day for LNS11300001: 2026-10-01 00:00:00
Fetching data for LNS11300001 starting from 2026-10-01 00:00:00
--- LNS11300001 Series ---
No new data returned for LNS11300001, skipping
Max date for LNS11300002: 2026-09-01 00:00:00
Frequency short for LNS11300002: M
Next read day for LNS11300002: 2026-10-01 00:00:00
Fetching data for LNS11300002 starting from 2026-10-01 00:00:00
--- LNS11300002 Series ---
No new data returned for LNS11300002, skipping
Max date for LNS11300032: 2026-09-01 00:00:00
Frequency short for LNS11300032: M
Next read day for LNS11300032: 2026-10-01 00:00:00
Fetching data for LNS11300032 starting from 2026-10-01 00:00:00
--- LNS11300032 Series ---
No new data returned for LNS11300032, skipping
Max date for LNS11300012: 2026-09-01 00:00:00
Frequency short for LNS11300012: M
Next read day for LNS11300012: 2026-10-01 00:00:00
Fetching data for LNS11300012 starting from 2026-10-01 00:00:00
--- LNS11300012 Series ---
No new data returned for LNS11300012, skipping
Max date for ICSA: 2026-10-03 00:00:00
Frequency short for ICSA: W
Next read day for ICSA: 2026-10-10 00:00:00
Max date for M1V: 2026-04-01 00:00:00
Frequency short for M1V: Q
Next read day for M1V: 2026-07-01 00:00:00
Fetching data for M1V starting from 2026-07-01 00:00:00
--- M1V Series ---
No new data returned for M1V, skipping
Max date for M2V: 2026-04-01 00:00:00
Frequency short for M2V: Q
Next read day for M2V: 2026-07-01 00:00:00
Fetching data for M2V starting from 2026-07-01 00:00:00
--- M2V Series ---
No new data returned for M2V, skipping
Max date for BOGMBASE: 2026-08-01 00:00:00
Frequency short for BOGMBASE: M
Next read day for BOGMBASE: 2026-08-31 00:00:00
Fetching data for BOGMBASE starting from 2026-08-31 00:00:00
--- BOGMBASE Series ---
No new data to append for BOGMBASE, skipping
Max date for BOGMBBM: 2026-08-01 00:00:00
Frequency short for BOGMBBM: M
Next read day for BOGMBBM: 2026-08-31 00:00:00
Fetching data for BOGMBBM starting from 2026-08-31 00:00:00
--- BOGMBBM Series ---
No new data to append for BOGMBBM, skipping
Max date for MBCURRCIR: 2026-08-01 00:00:00
Frequency short for MBCURRCIR: M
Next read day for MBCURRCIR: 2026-08-31 00:00:00
Fetching data for MBCURRCIR starting from 2026-08-31 00:00:00
--- MBCURRCIR Series ---
No new data to append for MBCURRCIR, skipping
Max date for PPIACO: 2026-08-01 00:00:00
Frequency short for PPIACO: M
Next read day for PPIACO: 2026-08-31 00:00:00
Fetching data for PPIACO starting from 2026-08-31 00:00:00
--- PPIACO Series ---
No new data to append for PPIACO, skipping
Max date for PCUOMFGOMFG: 2026-08-01 00:00:00
Frequency short for PCUOMFGOMFG: M
Next read day for PCUOMFGOMFG: 2026-08-31 00:00:00
Fetching data for PCUOMFGOMFG starting from 2026-08-31 00:00:00
--- PCUOMFGOMFG Series ---
No new data to append for PCUOMFGOMFG, skipping
Max date for PCUAINFOAINFO: 2026-08-01 00:00:00
Frequency short for PCUAINFOAINFO: M
Next read day for PCUAINFOAINFO: 2026-08-31 00:00:00
Fetching data for PCUAINFOAINFO starting from 2026-08-31 00:00:00
--- PCUAINFOAINFO Series ---
No new data to append for PCUAINFOAINFO, skipping
Max date for PCUATRNWRATRNWR: 2026-08-01 00:00:00
Frequency short for PCUATRNWRATRNWR: M
Next read day for PCUATRNWRATRNWR: 2026-08-31 00:00:00
Fetching data for PCUATRNWRATRNWR starting from 2026-08-31 00:00:00
--- PCUATRNWRATRNWR Series ---
No new data to append for PCUATRNWRATRNWR, skipping
Max date for WFRBST01134: 2026-04-01 00:00:00
Frequency short for WFRBST01134: Q
Next read day for WFRBST01134: 2026-07-01 00:00:00
Fetching data for WFRBST01134 starting from 2026-07-01 00:00:00
--- WFRBST01134 Series ---
No new data returned for WFRBST01134, skipping
Max date for WFRBLT01026: 2026-04-01 00:00:00
Frequency short for WFRBLT01026: Q
Next read day for WFRBLT01026: 2026-07-01 00:00:00
Fetching data for WFRBLT01026 starting from 2026-07-01 00:00:00
--- WFRBLT01026 Series ---
No new data returned for WFRBLT01026, skipping
Max date for WFRBSN40188: 2026-04-01 00:00:00
Frequency short for WFRBSN40188: Q
Next read day for WFRBSN40188: 2026-07-01 00:00:00
Fetching data for WFRBSN40188 starting from 2026-07-01 00:00:00
--- WFRBSN40188 Series ---
No new data returned for WFRBSN40188, skipping
Max date for WFRBSB50215: 2026-04-01 00:00:00
Frequency short for WFRBSB50215: Q
Next read day for WFRBSB50215: 2026-07-01 00:00:00
Fetching data for WFRBSB50215 starting from 2026-07-01 00:00:00
--- WFRBSB50215 Series ---
No new data returned for WFRBSB50215, skipping
Max date for GASDESW: 2026-10-05 00:00:00
Frequency short for GASDESW: W
Next read day for GASDESW: 2026-10-12 00:00:00
Max date for APU000072610: 2026-08-01 00:00:00
Frequency short for APU000072610: M
Next read day for APU000072610: 2026-08-31 00:00:00
Fetching data for APU000072610 starting from 2026-08-31 00:00:00
--- APU000072610 Series ---
No new data to append for APU000072610, skipping
Max date for PNRGINDEXM: 2026-07-01 00:00:00
Frequency short for PNRGINDEXM: M
Next read day for PNRGINDEXM: 2026-07-31 00:00:00
Fetching data for PNRGINDEXM starting from 2026-07-31 00:00:00
--- PNRGINDEXM Series ---
No new data to append for PNRGINDEXM, skipping
Max date for GDPC1: 2026-04-01 00:00:00
Frequency short for GDPC1: Q
Next read day for GDPC1: 2026-07-01 00:00:00
Fetching data for GDPC1 starting from 2026-07-01 00:00:00
--- GDPC1 Series ---
No new data returned for GDPC1, skipping
Max date for PSAVERT: 2026-08-01 00:00:00
Frequency short for PSAVERT: M
Next read day for PSAVERT: 2026-08-31 00:00:00
Fetching data for PSAVERT starting from 2026-08-31 00:00:00
--- PSAVERT Series ---
No new data to append for PSAVERT, skipping
Max date for TLCOMCONS: 2026-08-01 00:00:00
Frequency short for TLCOMCONS: M
Next read day for TLCOMCONS: 2026-08-31 00:00:00
Fetching data for TLCOMCONS starting from 2026-08-31 00:00:00
--- TLCOMCONS Series ---
No new data to append for TLCOMCONS, skipping
Max date for TLRESCONS: 2026-08-01 00:00:00
Frequency short for TLRESCONS: M
Next read day for TLRESCONS: 2026-08-31 00:00:00
Fetching data for TLRESCONS starting from 2026-08-31 00:00:00
--- TLRESCONS Series ---
No new data to append for TLRESCONS, skipping

In [58]:
df_to_append.info(verbose=True)

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    0 non-null      datetime64[us]
 1   value   0 non-null      float64
dtypes: datetime64[us](1), float64(1)
memory usage: 132.0 bytes

In [59]:
type(max_date)

pandas.Timestamp

In [60]:
pd.Timestamp(max_date)

Timestamp('2026-08-01 00:00:00')