In [ ]:
import os
import gc
#from dotenv import load_dotenv
#from sqlalchemy.exc import ProgrammingError
from sqlalchemy import create_engine, text, inspect
import pandas as pd
#import cudf

In [ ]:
#create a class for interacting with the postgresql db

class pgsql:
    def __init__(self):
        USER = os.getenv("DB_USER")
        PASSWORD = os.getenv("DB_PASSWORD")
        HOST = os.getenv("DB_HOST")
        PORT = os.getenv("DB_PORT")
        DB_NAME = os.getenv("DB_NAME")
        ADMIN_URL = f"postgresql+psycopg://{USER}:{PASSWORD}@{HOST}:{PORT}/{DB_NAME}"
        
        self.engine = create_engine(ADMIN_URL, isolation_level="AUTOCOMMIT")#, echo=True)
        self.inspector = inspect(self.engine)
        self.table_name = ""
        self.pdf = None
    #    self.cudf = None

    def refresh_inspector(self):
        self.inspector = inspect(self.engine)

    def set_table_name(self, table_name = ""):
        self.table_name = table_name

    def get_tables(self):
        return self.inspector.get_table_names()

    def get_sql_description(self, table_name = "", schema = "public"):
        if table_name == "":
            table_name = self.table_name
        columns = self.inspector.get_columns(table_name, schema=schema)
        primary_key_columns = self.inspector.get_pk_constraint(table_name, schema=schema).get("constrained_columns", [])
        return[
            {
                "name": column["name"],
                "type": column["type"],
                "nullable": column["nullable"],
                "default": column["default"],
                "primary_key": column["name"] in primary_key_columns
            } for column in columns
        ]
    
    def set_pdf(self, pdf = pd.DataFrame):
        self.pdf = pdf

    #def set_cudf(self, cudf = None):
    #    self.cudf = cudf

    def get_pdf(self):
        return self.pdf

    #def get_cudf(self):
    #    return self.cudf

    def clear_pdf(self):
        self.pdf = None

    #def clear_cudf(self):
    #    self.cudf = None

    def clear_dataframes(self):
        self.clear_pdf()
        self.clear_cudf()

    def check_pdf_compatability(self):
        #Check if columns names and types of pandas dataframe and sql table are compatible
        if self.pdf is None:
            return False
        sql_description = self.get_sql_description()
        sql_columns = {col["name"]: col["type"] for col in sql_description}
        for col in self.pdf.columns:
            if col not in sql_columns:
                return False
            # You can add more type checking here if needed
            if not pd.api.types.is_dtype_equal(self.pdf[col].dtype, sql_columns[col].python_type):
                return False
        return True

    #def check_cudf_compatability(self):
    #    #Check if columns names and types of cudf dataframe and sql table are compatible
    #    if self.cudf is None:
    #        return False
    #    sql_description = self.get_sql_description()
    #    sql_columns = {col["name"]: col["type"] for col in sql_description}
    #    for col in self.cudf.columns:
    #        if col not in sql_columns:
    #            return False
    #        # You can add more type checking here if needed
    #        if not pd.api.types.is_dtype_equal(self.cudf[col].dtype, sql_columns[col].python_type):
    #            return False
    #    return True

    def write_pdf_to_sql(self):
        if not self.check_pdf_compatability():
            raise ValueError("PDF is not compatible with SQL table")
        self.pdf.to_sql(self.table_name, self.engine, if_exists="replace", index=False)

    #def write_cudf_to_sql(self):
    #    if not self.check_cudf_compatability():
    #        raise ValueError("CUDF is not compatible with SQL table")
    #    self.cudf.to_pandas().to_sql(self.table_name, self.engine, if_exists="replace", index=False)

    def get_table_as_pdf(self):
        self.pdf = pd.read_sql_table(self.table_name, self.engine)
        return self.pdf

    #def get_table_as_cudf(self):
    #    self.cudf = cudf.read_sql_table(self.table_name, self.engine)
    #    return self.cudf


    #next we need a function that can return a subset of the sql table using a SQL query as a string
    def get_table_subset_as_pdf(self, query):
        self.pdf = pd.read_sql_query(query, self.engine)
        return self.pdf

    #def get_table_subset_as_cudf(self, query):
    #    self.cudf = cudf.read_sql_query(query, self.engine)
    #    return self.cudf

    def get_table_subset_as_pdf_with_where_clauses(self, where_clauses={}):
        query = "SELECT * FROM " + self.table_name + " WHERE " + " AND ".join([f"{k} = {v}" for k, v in where_clauses.items()])
        self.pdf = pd.read_sql_query(query, self.engine)
        return self.pdf

    #def get_table_subset_as_cudf_with_where_clauses(self, where_clauses={}):
    #    query = "SELECT * FROM " + self.table_name + " WHERE " + " AND ".join([f"{k} = {v}" for k, v in where_clauses.items()])
    #    self.cudf = cudf.read_sql_query(query, self.engine)
    #    return self.cudf
#where_clauses = {"year": 2024, "month": 1, "day_of_month": 1}
#query = "SELECT * FROM dim_date WHERE " + " AND ".join([f"{k} = {v}" for k, v in where_clauses.items()]) + " LIMIT 10"

In [23]:
test = pgsql()

In [24]:
tables = test.get_tables()
tables

['projects', 'alpaca_assets', 'fred_indicators', 'dim_date']

In [25]:
test.set_table_name("dim_date")

In [26]:
description = test.get_sql_description()
description

[{'name': 'id',
  'type': BIGINT(),
  'nullable': False,
  'default': None,
  'primary_key': True},
 {'name': 'date',
  'type': TIMESTAMP(timezone=True),
  'nullable': False,
  'default': None,
  'primary_key': False},
 {'name': 'year',
  'type': INTEGER(),
  'nullable': False,
  'default': None,
  'primary_key': False},
 {'name': 'quarter',
  'type': INTEGER(),
  'nullable': False,
  'default': None,
  'primary_key': False},
 {'name': 'month',
  'type': INTEGER(),
  'nullable': False,
  'default': None,
  'primary_key': False},
 {'name': 'day_of_month',
  'type': INTEGER(),
  'nullable': False,
  'default': None,
  'primary_key': False},
 {'name': 'hour',
  'type': INTEGER(),
  'nullable': False,
  'default': None,
  'primary_key': False},
 {'name': 'minute',
  'type': INTEGER(),
  'nullable': False,
  'default': None,
  'primary_key': False}]

In [27]:
limit_10 = test.get_table_subset_as_pdf("SELECT * FROM dim_date LIMIT 10")
limit_10

,id,date,year,quarter,month,day_of_month,hour,minute
0,0,1990-01-01 00:00:00+00:00,1990,1,1,1,0,0
1,1,1990-01-01 00:01:00+00:00,1990,1,1,1,0,1
2,2,1990-01-01 00:02:00+00:00,1990,1,1,1,0,2
3,3,1990-01-01 00:03:00+00:00,1990,1,1,1,0,3
4,4,1990-01-01 00:04:00+00:00,1990,1,1,1,0,4
5,5,1990-01-01 00:05:00+00:00,1990,1,1,1,0,5
6,6,1990-01-01 00:06:00+00:00,1990,1,1,1,0,6
7,7,1990-01-01 00:07:00+00:00,1990,1,1,1,0,7
8,8,1990-01-01 00:08:00+00:00,1990,1,1,1,0,8
9,9,1990-01-01 00:09:00+00:00,1990,1,1,1,0,9

In [28]:
test.get_table_subset_as_pdf("SELECT * FROM dim_date WHERE date = '2024-01-01' LIMIT 10")

,id,date,year,quarter,month,day_of_month,hour,minute
0,17882400,2024-01-01 08:00:00+00:00,2024,1,1,1,8,0

In [29]:
test.get_table_subset_as_pdf("SELECT * FROM dim_date WHERE year = 2024 and month = 1  and day_of_month = 1 LIMIT 10")

,id,date,year,quarter,month,day_of_month,hour,minute
0,17881920,2024-01-01 00:00:00+00:00,2024,1,1,1,0,0
1,17881921,2024-01-01 00:01:00+00:00,2024,1,1,1,0,1
2,17881922,2024-01-01 00:02:00+00:00,2024,1,1,1,0,2
3,17881923,2024-01-01 00:03:00+00:00,2024,1,1,1,0,3
4,17881924,2024-01-01 00:04:00+00:00,2024,1,1,1,0,4
5,17881925,2024-01-01 00:05:00+00:00,2024,1,1,1,0,5
6,17881926,2024-01-01 00:06:00+00:00,2024,1,1,1,0,6
7,17881927,2024-01-01 00:07:00+00:00,2024,1,1,1,0,7
8,17881928,2024-01-01 00:08:00+00:00,2024,1,1,1,0,8
9,17881929,2024-01-01 00:09:00+00:00,2024,1,1,1,0,9

In [30]:
where_clauses = {"year": 2024, "month": 1, "day_of_month": 1, "hour": 0}
query = "SELECT * FROM dim_date WHERE " + " AND ".join([f"{k} = {v}" for k, v in where_clauses.items()]) + " LIMIT 10"
test.get_table_subset_as_pdf(query)

,id,date,year,quarter,month,day_of_month,hour,minute
0,17881920,2024-01-01 00:00:00+00:00,2024,1,1,1,0,0
1,17881921,2024-01-01 00:01:00+00:00,2024,1,1,1,0,1
2,17881922,2024-01-01 00:02:00+00:00,2024,1,1,1,0,2
3,17881923,2024-01-01 00:03:00+00:00,2024,1,1,1,0,3
4,17881924,2024-01-01 00:04:00+00:00,2024,1,1,1,0,4
5,17881925,2024-01-01 00:05:00+00:00,2024,1,1,1,0,5
6,17881926,2024-01-01 00:06:00+00:00,2024,1,1,1,0,6
7,17881927,2024-01-01 00:07:00+00:00,2024,1,1,1,0,7
8,17881928,2024-01-01 00:08:00+00:00,2024,1,1,1,0,8
9,17881929,2024-01-01 00:09:00+00:00,2024,1,1,1,0,9

In [31]:
test.get_table_subset_as_pdf_with_where_clauses(where_clauses)

,id,date,year,quarter,month,day_of_month,hour,minute
0,17881920,2024-01-01 00:00:00+00:00,2024,1,1,1,0,0
1,17881921,2024-01-01 00:01:00+00:00,2024,1,1,1,0,1
2,17881922,2024-01-01 00:02:00+00:00,2024,1,1,1,0,2
3,17881923,2024-01-01 00:03:00+00:00,2024,1,1,1,0,3
4,17881924,2024-01-01 00:04:00+00:00,2024,1,1,1,0,4
5,17881925,2024-01-01 00:05:00+00:00,2024,1,1,1,0,5
6,17881926,2024-01-01 00:06:00+00:00,2024,1,1,1,0,6
7,17881927,2024-01-01 00:07:00+00:00,2024,1,1,1,0,7
8,17881928,2024-01-01 00:08:00+00:00,2024,1,1,1,0,8
9,17881929,2024-01-01 00:09:00+00:00,2024,1,1,1,0,9
10,17881930,2024-01-01 00:10:00+00:00,2024,1,1,1,0,10
11,17881931,2024-01-01 00:11:00+00:00,2024,1,1,1,0,11
12,17881932,2024-01-01 00:12:00+00:00,2024,1,1,1,0,12
13,17881933,2024-01-01 00:13:00+00:00,2024,1,1,1,0,13
14,17881934,2024-01-01 00:14:00+00:00,2024,1,1,1,0,14
15,17881935,2024-01-01 00:15:00+00:00,2024,1,1,1,0,15
16,17881936,2024-01-01 00:16:00+00:00,2024,1,1,1,0,16
17,17881937,2024-01-01 00:17:00+00:00,2024,1,1,1,0,17
18,17881938,2024-01-01 00:18:00+00:00,2024,1,1,1,0,18
19,17881939,2024-01-01 00:19:00+00:00,2024,1,1,1,0,19
20,17881940,2024-01-01 00:20:00+00:00,2024,1,1,1,0,20
21,17881941,2024-01-01 00:21:00+00:00,2024,1,1,1,0,21
22,17881942,2024-01-01 00:22:00+00:00,2024,1,1,1,0,22
23,17881943,2024-01-01 00:23:00+00:00,2024,1,1,1,0,23
24,17881944,2024-01-01 00:24:00+00:00,2024,1,1,1,0,24
25,17881945,2024-01-01 00:25:00+00:00,2024,1,1,1,0,25
26,17881946,2024-01-01 00:26:00+00:00,2024,1,1,1,0,26
27,17881947,2024-01-01 00:27:00+00:00,2024,1,1,1,0,27
28,17881948,2024-01-01 00:28:00+00:00,2024,1,1,1,0,28
29,17881949,2024-01-01 00:29:00+00:00,2024,1,1,1,0,29
30,17881950,2024-01-01 00:30:00+00:00,2024,1,1,1,0,30
31,17881951,2024-01-01 00:31:00+00:00,2024,1,1,1,0,31
32,17881952,2024-01-01 00:32:00+00:00,2024,1,1,1,0,32
33,17881953,2024-01-01 00:33:00+00:00,2024,1,1,1,0,33
34,17881954,2024-01-01 00:34:00+00:00,2024,1,1,1,0,34
35,17881955,2024-01-01 00:35:00+00:00,2024,1,1,1,0,35
36,17881956,2024-01-01 00:36:00+00:00,2024,1,1,1,0,36
37,17881957,2024-01-01 00:37:00+00:00,2024,1,1,1,0,37
38,17881958,2024-01-01 00:38:00+00:00,2024,1,1,1,0,38
39,17881959,2024-01-01 00:39:00+00:00,2024,1,1,1,0,39
40,17881960,2024-01-01 00:40:00+00:00,2024,1,1,1,0,40
41,17881961,2024-01-01 00:41:00+00:00,2024,1,1,1,0,41
42,17881962,2024-01-01 00:42:00+00:00,2024,1,1,1,0,42
43,17881963,2024-01-01 00:43:00+00:00,2024,1,1,1,0,43
44,17881964,2024-01-01 00:44:00+00:00,2024,1,1,1,0,44
45,17881965,2024-01-01 00:45:00+00:00,2024,1,1,1,0,45
46,17881966,2024-01-01 00:46:00+00:00,2024,1,1,1,0,46
47,17881967,2024-01-01 00:47:00+00:00,2024,1,1,1,0,47
48,17881968,2024-01-01 00:48:00+00:00,2024,1,1,1,0,48
49,17881969,2024-01-01 00:49:00+00:00,2024,1,1,1,0,49
50,17881970,2024-01-01 00:50:00+00:00,2024,1,1,1,0,50
51,17881971,2024-01-01 00:51:00+00:00,2024,1,1,1,0,51
52,17881972,2024-01-01 00:52:00+00:00,2024,1,1,1,0,52
53,17881973,2024-01-01 00:53:00+00:00,2024,1,1,1,0,53
54,17881974,2024-01-01 00:54:00+00:00,2024,1,1,1,0,54
55,17881975,2024-01-01 00:55:00+00:00,2024,1,1,1,0,55
56,17881976,2024-01-01 00:56:00+00:00,2024,1,1,1,0,56
57,17881977,2024-01-01 00:57:00+00:00,2024,1,1,1,0,57
58,17881978,2024-01-01 00:58:00+00:00,2024,1,1,1,0,58
59,17881979,2024-01-01 00:59:00+00:00,2024,1,1,1,0,59

In [33]:
test.get_pdf().head()

,id,date,year,quarter,month,day_of_month,hour,minute
0,17881920,2024-01-01 00:00:00+00:00,2024,1,1,1,0,0
1,17881921,2024-01-01 00:01:00+00:00,2024,1,1,1,0,1
2,17881922,2024-01-01 00:02:00+00:00,2024,1,1,1,0,2
3,17881923,2024-01-01 00:03:00+00:00,2024,1,1,1,0,3
4,17881924,2024-01-01 00:04:00+00:00,2024,1,1,1,0,4