In [25]:
import pandas as pd
import json
import ollama
#from pydantic import BaseModel, Field
import json
from db.pgsql import pgsql
import ast

from datetime import datetime, timedelta, timezone
#from getpass import getpass
import keyring
from pathlib import Path
import os
import time

import requests

In [26]:
ENDPOINT = "https://data.alpaca.markets/v1beta1/news"
PAGE_SIZE = 50
SYMBOLS_PER_REQUEST = 40
LOOKBACK = timedelta(hours=24)

api_key = os.getenv("ALPACA_API_KEY") or keyring.get_password(
    "api.alpaca.markets", "ALPACA_API_KEY")

secret_key = os.getenv("ALPACA_SECRET_KEY") or keyring.get_password(
    "api.alpaca.markets", "ALPACA_SECRET_KEY")


ticker_file = next(
    (
        parent / "documentation" / "alpaca_tickers.txt"
        for parent in (Path.cwd(), *Path.cwd().parents)
        if (parent / "documentation" / "alpaca_tickers.txt").is_file()
    ),
    None,
)
if ticker_file is None:
    raise FileNotFoundError(
        "Could not find documentation/alpaca_tickers.txt from the notebook's working directory."
    )

symbols = list(
    dict.fromkeys(
        line.strip().upper()
        for line in ticker_file.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    )
)
if not symbols:
    raise ValueError(f"No ticker symbols found in {ticker_file}")

#api_key = os.getenv("ALPACA_API_KEY") or getpass("Alpaca API key: ")
#secret_key = os.getenv("ALPACA_SECRET_KEY") or getpass("Alpaca secret key: ")
def get_api_key_secret():
    api_key = os.getenv("ALPACA_API_KEY") or keyring.get_password(
        "api.alpaca.markets", "ALPACA_API_KEY")
    secret_key = os.getenv("ALPACA_SECRET_KEY") or keyring.get_password(
        "api.alpaca.markets", "ALPACA_SECRET_KEY")
    if not api_key or not secret_key:
        raise ValueError("Both Alpaca API credentials are required.")
    return api_key, secret_key

def get_ticker_file(folder, file_name):
    ticker_file = next(
        (
            parent / folder / file_name
            for parent in (Path.cwd(), *Path.cwd().parents)
            if (parent / folder / file_name).is_file()
        ),
        None,
    )
    if ticker_file is None:
        raise FileNotFoundError(
            f"Could not find {folder}/{file_name} from the notebook's working directory."
        )
    return ticker_file

ticker_file = get_ticker_file("documentation", "alpaca_tickers.txt")

def get_symbols_from_file(ticker_file):
    return list(
        dict.fromkeys(
            line.strip().upper()
            for line in ticker_file.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        )
    )

symbols = get_symbols_from_file(ticker_file)


api_key, secret_key = get_api_key_secret()
headers = {
    "accept": "application/json",
    "APCA-API-KEY-ID": api_key,
    "APCA-API-SECRET-KEY": secret_key,
}

ENDPOINT = "https://data.alpaca.markets/v1beta1/news"
PAGE_SIZE = 50
SYMBOLS_PER_REQUEST = 40
LOOKBACK = timedelta(hours=24)

end_time = datetime.now(timezone.utc)
start_time = end_time - LOOKBACK


print(f"Loaded {len(symbols)} symbols from {ticker_file}")
print(f"News interval (UTC): {start_time:%Y-%m-%d %H:%M:%S} to {end_time:%Y-%m-%d %H:%M:%S}")

Loaded 515 symbols from /home/djmead/Documents/Projects/Financial/documentation/alpaca_tickers.txt
News interval (UTC): 2026-10-15 01:39:15 to 2026-10-16 01:39:15

In [27]:
def to_rfc3339(value):
    return value.isoformat(timespec="seconds").replace("+00:00", "Z")

def retrieve_articles(symbols):
    news_by_id = {}
    request_count = 0

    for offset in range(0, len(symbols), SYMBOLS_PER_REQUEST):
        symbol_batch = symbols[offset : offset + SYMBOLS_PER_REQUEST]
        page_token = None

        while True:
            params = {
                "symbols": ",".join(symbol_batch),
                "start": to_rfc3339(start_time),
                "end": to_rfc3339(end_time),
                "sort": "desc",
                "limit": PAGE_SIZE,
                "include_content": "false",
            }
            if page_token:
                params["page_token"] = page_token

            response = requests.get(ENDPOINT, headers=headers, params=params, timeout=30)
            response.raise_for_status()
            payload = response.json()
            if not isinstance(payload, dict) or not isinstance(payload.get("news"), list):
                raise ValueError("Unexpected Alpaca news response: expected an object with a 'news' list.")

            request_count += 1
            for article in payload["news"]:
                article_id = article.get("id")
                if article_id is None:
                    raise ValueError("Alpaca returned a news article without an ID.")

                if article_id not in news_by_id:
                    news_by_id[article_id] = article
                else:
                    known_symbols = set(news_by_id[article_id].get("symbols") or [])
                    known_symbols.update(article.get("symbols") or [])
                    news_by_id[article_id]["symbols"] = sorted(known_symbols)

            page_token = payload.get("next_page_token")
            if not page_token:
                break
            time.sleep(0.7)

        if offset + SYMBOLS_PER_REQUEST < len(symbols):
            time.sleep(0.7)

    articles = list(news_by_id.values())
    print(f"Received {len(articles)} unique articles in {request_count} API requests.")
    return articles

In [28]:
articles = retrieve_articles(symbols)
type(articles[0]['symbols'])

Received 372 unique articles in 18 API requests.

list

In [29]:
def fix_news_list_from_raw(articles: list[dict]) -> list[dict]:
    with open('../../tests/assets_us_equity.json', 'r') as file:
        assets_us_equity = json.load(file)
    assets_us_equity_df = pd.DataFrame(assets_us_equity)
    
    for news in articles:
        tickers = news.get('symbols', [])
        company_dict = {}
        for ticker in tickers:
            try:
                name = assets_us_equity_df.loc[assets_us_equity_df['symbol'] == ticker, 'name'].values[0]
            except IndexError:
                name = None
            company_dict[ticker] = name
        message = "HEADLINE: " + str(news.get('headline', '')) + "\nSUMMARY: " + str(news.get('summary', ''))  # if summary is not nan then message is summary, else message is headline
        while "\n\n" in message:
            message = message.replace("\n\n", "\n")

        news['message'] = message
        news['company_names'] = company_dict
    return articles

In [30]:

#with open('../../tests/assets_us_equity.json', 'r') as file:
#    assets_us_equity = json.load(file)
#assets_us_equity_df = pd.DataFrame(assets_us_equity)

def fix_news_list(news_list):
    with open('../../tests/assets_us_equity.json', 'r') as file:
        assets_us_equity = json.load(file)
    assets_us_equity_df = pd.DataFrame(assets_us_equity)
    
    for news in news_list:
        tickers = ast.literal_eval(news.get('tickers', []))
        company_dict = {}
        for ticker in tickers:
            try:
                name = assets_us_equity_df.loc[assets_us_equity_df['symbol'] == ticker, 'name'].values[0]
            except IndexError:
                name = None
            company_dict[ticker] = name
        message = "HEADLINE: " + str(news.get('headline', '')) + "\nSUMMARY: " + str(news.get('summary', ''))  # if summary is not nan then message is summary, else message is headline
        while "\n\n" in message:
            message = message.replace("\n\n", "\n")

        news['message'] = message
        news['company_names'] = company_dict
    return news_list


def build_scores_schema(tickers) -> dict:
    """JSON schema requiring one score in [-1, 1] for every ticker."""
    return {
        'type': 'object',
        'properties': {
            t: {'type': 'number', 'minimum': -1.0, 'maximum': 1.0} for t in tickers
        },
        'required': list(tickers),
        'additionalProperties': False,
    }


class HeadlineSentimentAnalyzer:
    def __init__(
        self,
        model: str = 'qwen3:8b',
        keep_alive: str = '10m',
        system_prompt_in_model: bool = False,
        temperature: float = 0.0,
    ):
        self.model = model
        self.keep_alive = keep_alive
        self.system_prompt_in_model = system_prompt_in_model
        self.temperature = temperature
        #self.system_prompt = (
        #    "You are an expert financial analyst. Your task is to look at a news message "
        #    "and judge its sentiment regarding each of the given publicly traded companies. "
        #    "You will be given a JSON dictionary (company_names) that matches ticker symbols to company names, "
        #    "and the news message. "
        #    "Provide a rating score for every ticker strictly between -1.0 (very bearish/negative) and "
        #    "+1.0 (very bullish/positive). Highly neutral or purely factual announcements "
        #    "without clear financial impact, or companies not meaningfully discussed, should be given 0.0. "
        #    "Return a JSON object with the ticker symbols as keys and their sentiment scores as values."
        #)
        self.system_prompt = ("""You are an expert financial analyst. 
            Your task is to analyze a news message and judge its sentiment regarding specific publicly traded companies. 

            INPUTS PROVIDED:
            1. `company_names`: A JSON dictionary mapping ticker symbols to company names.
            2. `news_message`: The text text to be analyzed.

            SCORING CRITERIA:
            Assign a sentiment score strictly between -1.0 and +1.0 for EVERY ticker provided in the `company_names` dictionary.
            * Scores can be a decimal from -1 to +1 such as -0.75, 0.31, 0.89, etc.
            * +1.0 = Very Bullish / Strongly Positive (e.g., massive earnings beat, major acquisition, large new government contract)
            * +0.5 = Moderately Bullish / Positive (e.g., incremental contract win, steady growth)
            *  0.0 = Neutral, purely factual announcements without immediate financial impact, mixed news, or if the company is merely mentioned without meaningful discussion.
            * -0.5 = Moderately Bearish / Negative (e.g., slight earnings miss, executive departure)
            * -1.0 = Very Bearish / Strongly Negative (e.g., severe regulatory fines, catastrophic fraud, loss of government contract)
            #* These are just examples. If you think it is appropriate to assign a different score, from -1 to +1, based on the context, you may do so.

            STRICT OUTPUT CONSTRAINTS:
            - You must return ONLY a raw JSON object where keys are the exact ticker symbols from `company_names` and values are the numerical sentiment scores (floats).
            - Do not include markdown blocks like ```json ... ```.
            - Do not include any introductory text, explanations, or postscript commentary. 
            - If a ticker from `company_names` is not mentioned or relevant to the text, you must still include it in the JSON object with a score of 0.0.

            OUTPUT TEMPLATE:
            {
            "TICKER1": 0.0,
            "TICKER2": 0.8,
            "TICKER3": -0.27,
            }
            """)
        self.custom_model = 'fin_news_analyzer'
        ollama.create(model = self.custom_model,
                      from_ = self.model,
                      system = self.system_prompt,
                      parameters={'temperature': self.temperature},
                      )

    def analyze_headline_sentiment(self, news_data: dict) -> dict:
        """Return a copy of the news dict with a 'scores' dict {ticker: score}."""
        company_names = news_data.get('company_names') or {}
        result = dict(news_data)
        if not company_names:
            result['scores'] = {}
            return result

        user_content = (
            f"company_names: {json.dumps(company_names, indent=2)}\n"
            f"message: {news_data.get('message', '')}"
        )
        messages = [{'role': 'user', 'content': user_content}]
        #if not self.system_prompt_in_model:
        #    messages.insert(0, {'role': 'system', 'content': self.system_prompt})

        try:
            response = ollama.chat(
                model=self.custom_model,
                messages=messages,
                format=build_scores_schema(list(company_names)),
                think=False,
                options={'temperature': 0.0},
                keep_alive=self.keep_alive,
            )
            content = response.get('message', {}).get('content', '').strip()
            if not content:
                raise RuntimeError(f"Ollama returned empty content: {response!r}")

            raw = json.loads(content)
            result['scores'] = {
                t: max(-1.0, min(1.0, float(raw.get(t, 0.0)))) for t in company_names
            }
            return result

        except ollama.ResponseError as e:
            raise RuntimeError(f"Ollama API error: {e.error}") from e

    def analyze_headlines(self, news_items: list[dict]) -> list[dict]:
        """Analyze every news item; return the batch with 'scores' added to each."""
        total = len(news_items)
        results = []
        for i, news in enumerate(news_items, start=1):
            print(f"analyzing news {i}/{total}: {news.get('headline', '')}")
            results.append(self.analyze_headline_sentiment(news))
        return results

def explode_scores(analized_list: list[dict]) -> pd.DataFrame:
    df_temp = pd.DataFrame(analized_list)
    df_temp['scores'] = df_temp['scores'].apply(lambda d: list(d.items()))
    df_temp = df_temp.explode('scores')
    df_temp[['ticker', 'score']] = pd.DataFrame(df_temp['scores'].tolist(), index=df_temp.index)
    return df_temp.reset_index()


def clean_columns(df_in: pd.DataFrame) -> pd.DataFrame:
    df_temp = df_in.copy()
    df_temp['timestamp'] = pd.to_datetime(df_temp['updated_at'])
    df_temp['unique_id'] = df_temp['id'].astype(str) + '-' + df_temp['ticker']
    df_temp = df_temp[df_temp['score'].notna()]
    df_temp = df_temp[df_temp['score'] != 0]
    return df_temp[['id', 'unique_id', 'url', 'timestamp', 'ticker', 'score', 'message']]

In [31]:
fixed_articles = fix_news_list_from_raw(articles)
fixed_articles[0]

{'author': 'Benzinga Newsdesk',
 'content': '',
 'created_at': '2026-10-15T21:07:07Z',
 'headline': "'Investors temper Anthropic IPO valuation expectations over revenue growth slowdown, sources say'- Reuters Exclusive",
 'id': 62401077,
 'images': [],
 'source': 'benzinga',
 'summary': '',
 'symbols': ['AMZN', 'GOOG', 'GOOGL', 'MSFT'],
 'updated_at': '2026-10-15T21:07:07Z',
 'url': 'https://www.benzinga.com/news/26/10/62401077/investors-temper-anthropic-ipo-valuation-expectations-over-revenue-growth-slowdown-sources-say-reute',
 'message': "HEADLINE: 'Investors temper Anthropic IPO valuation expectations over revenue growth slowdown, sources say'- Reuters Exclusive\nSUMMARY: ",
 'company_names': {'AMZN': 'Amazon.com, Inc. Common Stock',
  'GOOG': 'Alphabet Inc. Class C Capital Stock',
  'GOOGL': 'Alphabet Inc. Class A Common Stock',
  'MSFT': 'Microsoft Corporation Common Stock'}}

In [32]:
with open('../../documentation/alpaca_news.csv', 'r') as file:
    news_df = pd.read_csv(file).rename(columns={'symbols': 'tickers'})
    news_list = news_df.to_dict(orient='records')
    json_data = json.dumps(news_list, indent=2)

In [33]:
news_list[0]

{'id': 62341492,
 'created_at': '2026-10-13T20:51:37Z',
 'headline': 'Applied Materials Stock Sinks for 6th Day, but Cantor Sees 85% Upside',
 'author': 'Piero Cingari',
 'tickers': "['AMAT', 'ASML', 'AVGO', 'KLAC', 'LRCX', 'MU', 'SKHY', 'SSNLF']",
 'source': 'benzinga',
 'summary': 'Applied Materials stock fell 7% on investor day, its sixth straight loss. Cantor Fitzgerald kept an $850 target, implying 85% upside.',
 'url': 'https://www.benzinga.com/analyst-stock-ratings/analyst-color/26/10/62341492/applied-materials-stock-sinks-sixth-day-cantor-850-target'}

In [34]:
#assets_us_equity

In [35]:
#assets_us_equity_df.head(3)
#news_list

In [36]:
#news_list = fix_news_list(news_list)

#retrieve company name from the assets_us_equity_df and add to news_list
for news in news_list:
    tickers = ast.literal_eval(news.get('tickers', []))
    #print(tickers, type(tickers))
    company_dict = {}
    for ticker in tickers:#here we want to extract a single string value from name
        print(ticker)
        try:
            name = assets_us_equity_df.loc[assets_us_equity_df['symbol'] == ticker, 'name'].values[0]
        except IndexError:
            name = None
        #name = assets_us_equity_df.loc[assets_us_equity_df['symbol'] == ticker, 'name'].values[0]
        print(ticker, name, type(name))
        company_dict[ticker] = name
    #company_names = list(company_dict.values())
    print(company_dict)
    message = ""# if summary is not nan then message is summary, else message is headline
    if pd.notna(news.get('summary')):
        message = news['summary']
    else:
        message = news.get('headline', '')

    news['message'] = message
    news['company_names'] = company_dict

In [37]:
#news_list[:2]

def build_scores_schema(tickers) -> dict:
    """JSON schema requiring one score in [-1, 1] for every ticker."""
    return {
        'type': 'object',
        'properties': {
            t: {'type': 'number', 'minimum': -1.0, 'maximum': 1.0} for t in tickers
        },
        'required': list(tickers),
        'additionalProperties': False,
    }

class HeadlineSentimentAnalyzer:
    def __init__(
        self,
        model: str = 'qwen3:8b',
        keep_alive: str = '10m',
        system_prompt_in_model: bool = False,
    ):
        self.model = model
        self.keep_alive = keep_alive
        self.system_prompt_in_model = system_prompt_in_model
        self.system_prompt = (
            "You are an expert financial analyst. Your task is to look at a news message "
            "and judge its sentiment regarding each of the given publicly traded companies. "
            "You will be given a JSON dictionary (company_names) that matches ticker symbols to company names, "
            "and the news message. "
            "Provide a rating score for every ticker strictly between -1.0 (very bearish/negative) and "
            "+1.0 (very bullish/positive). Highly neutral or purely factual announcements "
            "without clear financial impact, or companies not meaningfully discussed, should be given 0.0. "
            "Return a JSON object with the ticker symbols as keys and their sentiment scores as values."
        )

    def analyze_headline_sentiment(self, news_data: dict) -> dict:
        """Return a copy of the news dict with a 'scores' dict {ticker: score}."""
        company_names = news_data.get('company_names') or {}
        result = dict(news_data)
        if not company_names:
            result['scores'] = {}
            return result

        user_content = (
            f"company_names: {json.dumps(company_names, indent=2)}\n"
            f"message: {news_data.get('message', '')}"
        )
        messages = [{'role': 'user', 'content': user_content}]
        if not self.system_prompt_in_model:
            messages.insert(0, {'role': 'system', 'content': self.system_prompt})

        try:
            response = ollama.chat(
                model=self.model,
                messages=messages,
                format=build_scores_schema(list(company_names)),
                think=False,
                options={'temperature': 0.0},
                keep_alive=self.keep_alive,
            )
            content = response.get('message', {}).get('content', '').strip()
            if not content:
                raise RuntimeError(f"Ollama returned empty content: {response!r}")

            raw = json.loads(content)
            result['scores'] = {
                t: max(-1.0, min(1.0, float(raw.get(t, 0.0)))) for t in company_names
            }
            return result

        except ollama.ResponseError as e:
            raise RuntimeError(f"Ollama API error: {e.error}") from e

    def analyze_headlines(self, news_items: list[dict]) -> list[dict]:
        """Analyze every news item; return the batch with 'scores' added to each."""
        total = len(news_items)
        results = []
        for i, news in enumerate(news_items, start=1):
            print(f"analyzing news {i}/{total}: {news.get('headline', '')}")
            results.append(self.analyze_headline_sentiment(news))
        return results

In [38]:
hsa = HeadlineSentimentAnalyzer()
analized = hsa.analyze_headlines(fixed_articles)

analyzing news 1/372: 'Investors temper Anthropic IPO valuation expectations over revenue growth slowdown, sources say'- Reuters Exclusive
analyzing news 2/372: Google Rolls Out Universal Cart In U.S. Across Google Search, Gemini
analyzing news 3/372: 𝕏 Product Creator Allegra Jacchia Posts "We’re doubling down on video on 𝕏. Today, we're piloting Video Kickstart Bonus, an invite-only program that rewards creators for posting their video content here..."
analyzing news 4/372: Scotiabank Initiates Coverage On APA with Sector Perform Rating, Announces Price Target of $44
analyzing news 5/372: Lam Research Stock Hits Longest Losing Streak Ever: Are There Buyers Around?
analyzing news 6/372: Anthropic Needs Nearly $2.7B in Additional Monthly Revenue to Reach $100B Run Rate by Year-End
analyzing news 7/372: Google Quantum AI Achieves 40-Fold Error Reduction In Magic State Cultivation, Advancing Practical Quantum Computing
analyzing news 8/372: Google's $4 Billion Fuel-Cell Project Puts Bloom Energy's AI Power Backlog to the Test
analyzing news 9/372: Michael Burry's 'Red October' Warning: Why QQQ and SMH Could Face More Pain
analyzing news 10/372: Mizuho Maintains Underperform on APA, Raises Price Target to $44
analyzing news 11/372: 10 Consumer Discretionary Stocks Whale Activity In Today’s Session
analyzing news 12/372: 'CNN And Google Strike Multiyear Partnership To Embrace Generative AI' - Variety
analyzing news 13/372: American Express Prelim U.S. Consumer Card 30 Days Past Due Rate 1.2% As Of Sept 30, 2026; Prelim U.S. Consumer Card Net Write-Off Rate (Principal Only) 1.5% As Of Sept 30, 2026; Prelim U.S. Small Business Card Net Write-Off Rate (Principal Only) 2.1% As Of Sept 30, 2026; Prelim U.S. Small Business Card 30 Days Past Due As A % Of Total 1.4% As Of Sept 30, 2026
analyzing news 14/372: Meta Announces Release Of Muse Spark Open, The Open Weights Version Of Muse Spark
analyzing news 15/372: Google Undercuts Some AI Rivals on Price as Gemini 4 Argon Reaches Enterprises
analyzing news 16/372: Adobe Stock Gains Ground Thursday: What's Happening?
analyzing news 17/372: Rate Pressure vs. AI Demand: Rising Treasury Yields Trigger Nvidia, AMD Slump
analyzing news 18/372: 'Apple and Meta team up to make Muse AI model run on Mac computers' - CNBC
analyzing news 19/372: Adobe And Nvidia Expand Partnership To Optimize Photoshop, Premiere, Substance 3D, Frame.io And Brand Concierge With Faster AI-Powered Creation, Production And Personalization
analyzing news 20/372: Apple Hits $5 Trillion Market Cap as Nvidia's Lead Shrinks
analyzing news 21/372: AI Financing Fears Hammer Chip Stocks: These 2 ETFs Are Cashing In on the Sell-Off
analyzing news 22/372: Morgan Stanley Maintains Underweight on APA, Raises Price Target to $43
analyzing news 23/372: OpenAI, Anthropic’s AI Lead Is ‘Very Perishable,’ IMD Professor Says: ‘You Don’t Need to Drive a Ferrari to Go to Walmart’
analyzing news 24/372: XPENG To Offer Google Play Within Its Cars
analyzing news 25/372: QUICK SPARK: Meet the 15 Worst-Performing Chip Stocks in the Last 7 Sessions
analyzing news 26/372: JP Morgan Maintains Overweight on Alphabet, Raises Price Target to $425
analyzing news 27/372: Defensives Lead Sectors In Thursday Trading As Technology Trails
analyzing news 28/372: JP Morgan Maintains Neutral on Aflac, Raises Price Target to $119
analyzing news 29/372: RBC Capital Maintains Sector Perform on APA, Raises Price Target to $49
analyzing news 30/372: AI Build-Out Has ‘Broken the Old Demand Cycle,’ Chip Veteran Says as TSMC Posts Record Profit
analyzing news 31/372: RBC Capital Maintains Outperform on Albemarle, Lowers Price Target to $129
analyzing news 32/372: RBC Capital Maintains Outperform on Air Products, Lowers Price Target to $346
analyzing news 33/372: $100 Invested In Analog Devices 10 Years Ago Would Be Worth This Much Today
analyzing news 34/372: Why Is Applied Digital Stock Falling on Thursday?
analyzing news 35/372: FTC Spokesman Says President Trump Task Force On AI To Meet Thursday
analyzing news 36/372: TD Cowen Maintains Hold on Accenture, Raises Price Target to $201
analyzing news 37/372: Evercore ISI Group Maintains Outperform on Applied Materials, Lowers Price Target to $590
analyzing news 38/372: Susquehanna Maintains Neutral on Accenture, Raises Price Target to $230
analyzing news 39/372: Nvidia CEO Jensen Huang Rejects Sam Altman's Advice to 'Accept' AI Cybersecurity Risks: ‘We Should Do Everything...to Avoid Them’
analyzing news 40/372: Fastenal To Rally More Than 15%? Here Are 10 Top Analyst Forecasts For Thursday
analyzing news 41/372: Amazon Rolls Out Bee Frontier, Bee Eclipse
analyzing news 42/372: This Align Technology Analyst Is No Longer Bullish; Here Are Top 5 Downgrades For Thursday
analyzing news 43/372: Allstate Reports Q3 Estimated Total Catastrophe Losses Of $1.65B Or $1.3B After-Tax
analyzing news 44/372: NYC Comptroller Mark Levine Says Urges Anthropic To Pause Its IPO Until Co Addresses AI Safety, Governance And Pace Concerns
analyzing news 45/372: Wall Street's Most Accurate Analysts Give Their Take On 3 Utilities Stocks Delivering High-Dividend Yields
analyzing news 46/372: When Can You Buy a Tesla Cybercab? Investors Press Elon Musk on Robotaxis, HW3 FSD and More Ahead of TSLA's Q3 Earnings
analyzing news 47/372: Apple Intelligence Reportedly Nears China Debut After Delays. What to Expect
analyzing news 48/372: Google Search’s $250 Billion Business Faces a New AI Threat: Why Gene Munster Thinks Meta’s Muse May Be More Dangerous Than ChatGPT
analyzing news 49/372: Baird Downgrades Align Technology to Neutral, Lowers Price Target to $162
analyzing news 50/372: Micron Stock Slides Again Thursday: What's Going On?
analyzing news 51/372: Industry Comparison: Evaluating Analog Devices Against Competitors In Semiconductors &amp; Semiconductor Equipment Industry
analyzing news 52/372: Market Analysis: Adobe And Competitors In Software Industry
analyzing news 53/372: Understanding Airbnb's Position In Hotels, Restaurants &amp; Leisure Industry Compared To Competitors
analyzing news 54/372: Assessing Apple's Performance Against Competitors In Technology Hardware, Storage &amp; Peripherals Industry
analyzing news 55/372: Apple Intelligence Finally Coming to China After 2-Year Wait — But AI Siri and Genmoji Are Missing
analyzing news 56/372: EasyJet Directors Recommend Apollo Cash Offer, Scheme Expected Effective Before Q1 2027 Ends; Multiple Unions Across Europe Raise Ownership And Control Concerns
analyzing news 57/372: Anthropic's Q3 Revenue Surged 45% to $16.8 Billion, Profitable on Adjusted Basis as Dario Amodei Courts Investors: Report
analyzing news 58/372: Iran Media Outlet Says Google, Meta, Microsoft, Amazon Should Pay Fees for Hormuz Undersea Cables (UPDATED)
analyzing news 59/372: Here’s How Much You Would Have Made Owning Ares Management Stock In The Last 10 Years
analyzing news 60/372: UBS Maintains Buy on BlackRock, Raises Price Target to $1300
analyzing news 61/372: QUICK SPARK: DRAM ETF Extends Losing Streak, But CEO Sees Long-Term Upside
analyzing news 62/372: Citigroup Maintains Buy on Bank of America, Lowers Price Target to $60
analyzing news 63/372: Nike, Moderna, Walmart Get a Lift as Traders Flee AI Stocks
analyzing news 64/372: These Analysts Boost Their Forecasts On BlackRock After Better-Than-Expected Q3 Results
analyzing news 65/372: 9 Industrials Stocks With Whale Alerts In Today’s Session
analyzing news 66/372: Bank of America Analysts Slash Their Forecasts Following Weak Q3 Results
analyzing news 67/372: Venture Global Taps GE Vernova, Baker Hughes to Fuel Its AI Infrastructure Ambitions
analyzing news 68/372: Why Is SoFi Stock Climbing on Thursday?
analyzing news 69/372: Full Transcript: Bank of New York Mellon Q3 2026 Earnings Call
analyzing news 70/372: Bank of New York Mellon Sees FY 2026 Revenue Growth Near Midpoint of 12%-13% Guidance Range, Excluding Notable Items
analyzing news 71/372: Morgan Stanley Maintains Overweight on BlackRock, Raises Price Target to $1531
analyzing news 72/372: Morgan Stanley Maintains Overweight on Bank of America, Lowers Price Target to $61
analyzing news 73/372: QUICK SPARK: Bank of America's Bond Losses Swell to $109 Billion
analyzing news 74/372: This Bank of America Analyst Cuts Estimates After Q3 Results
analyzing news 75/372: JP Morgan Maintains Overweight on BlackRock, Raises Price Target to $1449
analyzing news 76/372: Truist Securities Maintains Hold on Atmos Energy, Lowers Price Target to $174
analyzing news 77/372: Here's How Much $100 Invested In AppLovin 15 Years Ago Would Be Worth Today
analyzing news 78/372: This House of Representative Just Sold Up To $65K In AutoZone Stock
analyzing news 79/372: Bloom Energy Stock Continues to Fall: What's Happening?
analyzing news 80/372: RBC Capital Maintains Outperform on Bank of America, Lowers Price Target to $60
analyzing news 81/372: RBC Capital Maintains Outperform on Boeing, Lowers Price Target to $235
analyzing news 82/372: Barclays Maintains Overweight on BlackRock, Lowers Price Target to $1410
analyzing news 83/372: Barclays Maintains Overweight on Bank of America, Lowers Price Target to $68
analyzing news 84/372: Bank Of America Reports Credit Card Delinquency Rate Of 1.37% At September End; Credit Card Charge-Off Rate Was 2.07% In September
analyzing news 85/372: BlackRock CEO Larry Fink Says $40 Trillion US Debt ‘Will Not Be as Consequential’ If AI Drives 3% GDP Growth
analyzing news 86/372: Ericsson Plans Price Hikes As AI Boom Drives Up Equipment Costs
analyzing news 87/372: Watching Bloom Energy; Hearing Zacks Tazr Buys Stock
analyzing news 88/372: Wells Fargo Maintains Overweight on BlackRock, Raises Price Target to $1250
analyzing news 89/372: Wells Fargo Maintains Overweight on Bank of America, Lowers Price Target to $64
analyzing news 90/372: TD Cowen Maintains Hold on Bank of America, Lowers Price Target to $56
analyzing news 91/372: Evercore ISI Group Maintains Outperform on Bank of America, Lowers Price Target to $57
analyzing news 92/372: Axon Announces It Recently Receives Contracts From Multiple U.S. Federal Agencies
analyzing news 93/372: Capital Over Chips: Broadcom CEO Warns Financing Costs Could Slow AI Expansion
analyzing news 94/372: Keefe, Bruyette & Woods Maintains Outperform on BlackRock, Raises Price Target to $1310
analyzing news 95/372: This Walmart Analyst Turns Bullish; Here Are Top 5 Upgrades For Thursday
analyzing news 96/372: Verizon And Ericsson Successfully Complete World's First Pre-Standard 6G Field Call In 7 GHz From A Verizon Commercial Network Site In California
analyzing news 97/372: Baird Maintains Outperform on Bloom Energy, Raises Price Target to $351
analyzing news 98/372: Earnings Scheduled For October 15, 2026
analyzing news 99/372: AppLovin Stock Sinks To 52-Week Low - Here's Why
analyzing news 100/372: Bank of New York Mellon Q3 Adj. EPS $2.37 Beats $2.27 Estimate, Sales $5.676B Beat $5.547B Estimate
analyzing news 101/372: Baird Upgrades Bank of America to Outperform, Maintains Price Target to $62
analyzing news 102/372: JPMorgan, Bank of America, Wells Fargo Among 9 Banks Accused of Political, Religious Debanking by OCC
analyzing news 103/372: Venture Global Enters Power And Grid Frame Agreements With GE Vernova And Baker Hughes Energy Services For Up To Sixteen 720 MW Power Island Units And Associated Power Transformer Equipment
analyzing news 104/372: Insights Into Automatic Data Processing's Performance Versus Peers In Professional Services Sector
analyzing news 105/372: Bloomberg Reported Cathay Pacific To Seek 50 Additional Large Aircraft From Airbus, Boeing
analyzing news 106/372: BofA's Brian Moynihan Downplays Inflation Concerns on US Economy, Says it is 'Resilient and Growing' — Here’s What Clients Are Doing
analyzing news 107/372: Nasdaq Tumbles Over 500 Points After Inflation Data: Investor Sentiment Weakens Further, Greed Index Remains In ‘Fear’ Zone
analyzing news 108/372: Stock Market: Will S&P 500 Open Up or Down Today?
analyzing news 109/372: TSMC Q3 Earnings: Nicholas Mugalli Says Capex Hint Matters Most As Chipmaker Eyes Sixth Record Profit
analyzing news 110/372: SK Hynix Stock Plunges 11% in Seoul, Slips After Hours in New York as Hot CPI, Fed Hike Bets and AI Funding Worries Weigh
analyzing news 111/372: 'KFC Is Moving to Ditch Pepsi for Coke in Thousands of Restaurants' - WSJ Exclusive
analyzing news 112/372: Why Is Cisco Stock Falling on Thursday?
analyzing news 113/372: Citigroup Credit Card Charge-Offs 2.18% In September; Credit Card Delinquency Rate 1.35% At September End
analyzing news 114/372: Crude Oil Moves Higher; Charles Schwab Shares Fall After Q3 Results
analyzing news 115/372: Here’s How Much You Would Have Made Owning Cintas Stock In The Last 10 Years
analyzing news 116/372: Morgan Stanley Maintains Equal-Weight on Clorox, Lowers Price Target to $87
analyzing news 117/372: Morgan Stanley Maintains Equal-Weight on Chipotle Mexican Grill, Raises Price Target to $40
analyzing news 118/372: Morgan Stanley Maintains Overweight on Chevron, Raises Price Target to $226
analyzing news 119/372: Morgan Stanley Maintains Overweight on Carvana, Lowers Price Target to $88
analyzing news 120/372: Stephens & Co. Maintains Equal-Weight on Chipotle Mexican Grill, Lowers Price Target to $38
analyzing news 121/372: Caterpillar Investing $10M In Its North Carolina Operations
analyzing news 122/372: RBC Capital Upgrades Casey's General Stores to Outperform, Lowers Price Target to $825
analyzing news 123/372: B. Riley Securities Maintains Neutral on Coherent, Lowers Price Target to $297
analyzing news 124/372: Charles Schwab Q3 2026 Earnings Call: Complete Transcript
analyzing news 125/372: Charles Schwab Pulls in Record $190 Billion in New Assets
analyzing news 126/372: Keybanc Maintains Overweight on Comfort Systems USA, Raises Price Target to $2125
analyzing news 127/372: Mizuho Maintains Outperform on Carrier Global, Lowers Price Target to $70
analyzing news 128/372: 'Taiwan Blocks Coinbase, Kalshi Over Suspected Election Bets' - Bloomberg
analyzing news 129/372: Charles Schwab Q3 Adj. EPS $1.69 Beats $1.66 Estimate, Sales $7.171B Miss $7.192B Estimate
analyzing news 130/372: Coinbase Investigates Possible NEAR Network Send And Receive Delays For Some Users, Says Funds Safe; Buys, Sells, Fiat Withdrawals And Deposits Unaffected
analyzing news 131/372: Charles Schwab, US Bancorp And 3 Stocks To Watch Heading Into Thursday
analyzing news 132/372: Tigress Financial Maintains Buy on Costco Wholesale, Raises Price Target to $1250
analyzing news 133/372: Scotiabank Initiates Coverage On Devon Energy with Sector Outperform Rating, Announces Price Target of $61
analyzing news 134/372: Scotiabank Initiates Coverage On Diamondback Energy with Sector Outperform Rating, Announces Price Target of $250
analyzing news 135/372: Trump’s Power Grid Emergency Puts This AI Infrastructure ETFs in the Spotlight
analyzing news 136/372: Citigroup Maintains Buy on CrowdStrike Holdings, Raises Price Target to $295
analyzing news 137/372: Mizuho Maintains Outperform on Datadog, Raises Price Target to $330
analyzing news 138/372: Dow Jones Climbs to 52,000 While Chips Bleed on Rate-Hike Fears: Stock Market Today
analyzing news 139/372: Citigroup Maintains Neutral on D.R. Horton, Lowers Price Target to $150
analyzing news 140/372: CNBC Halftime Report Final Trades: Wells Fargo, CrowdStrike, Netflix
analyzing news 141/372: Morgan Stanley Maintains Equal-Weight on Diamondback Energy, Raises Price Target to $222
analyzing news 142/372: Morgan Stanley Maintains Overweight on Devon Energy, Raises Price Target to $65
analyzing news 143/372: Morgan Stanley Maintains Overweight on ConocoPhillips, Raises Price Target to $159
analyzing news 144/372: RBC Capital Maintains Underperform on D.R. Horton, Lowers Price Target to $119
analyzing news 145/372: Stock of the Day: Is Dollar General Breaking Out?
analyzing news 146/372: Why Is Dell Technologies Stock Sinking Thursday?
analyzing news 147/372: RBC Capital Maintains Outperform on DuPont de Nemours, Lowers Price Target to $160
analyzing news 148/372: Mizuho Maintains Outperform on Dover, Lowers Price Target to $245
analyzing news 149/372: Why Is Costco (COST) Stock Trending After Hours?
analyzing news 150/372: UBS Maintains Buy on EQT, Lowers Price Target to $76
analyzing news 151/372: UBS Maintains Buy on Expand Energy, Lowers Price Target to $120
analyzing news 152/372: Here's How Much $1000 Invested In Everpure 10 Years Ago Would Be Worth Today
analyzing news 153/372: Scotiabank Initiates Coverage On EOG Resources with Sector Perform Rating, Announces Price Target of $144
analyzing news 154/372: Scotiabank Initiates Coverage On EQT with Sector Perform Rating, Announces Price Target of $54
analyzing news 155/372: B of A Securities Reinstates Underperform on Fiserv, Announces $48 Price Target
analyzing news 156/372: Mizuho Maintains Outperform on EQT, Lowers Price Target to $68
analyzing news 157/372: Morgan Stanley Maintains Overweight on ExxonMobil Holdings, Raises Price Target to $185
analyzing news 158/372: Morgan Stanley Maintains Overweight on Expand Energy, Lowers Price Target to $124
analyzing news 159/372: Morgan Stanley Maintains Equal-Weight on Estee Lauder Cos, Raises Price Target to $112
analyzing news 160/372: Morgan Stanley Maintains Equal-Weight on EOG Resources, Raises Price Target to $163
analyzing news 161/372: Fastenal Analyst Cuts Estimates After Q3 Results
analyzing news 162/372: Barclays Maintains Overweight on First Solar, Lowers Price Target to $259
analyzing news 163/372: These Analysts Boost Their Forecasts On Fastenal After Q3 Results
analyzing news 164/372: Bernstein Maintains Underperform on Fastenal, Raises Price Target to $47
analyzing news 165/372: Mizuho Maintains Outperform on Emerson Electric, Raises Price Target to $180
analyzing news 166/372: Baird Maintains Outperform on Fastenal, Raises Price Target to $60
analyzing news 167/372: EOG Resources Q2 2026 Earnings Call: Complete Transcript
analyzing news 168/372: B of A Securities Reinstates Buy on Global Payments, Announces $114 Price Target
analyzing news 169/372: Mizuho Maintains Underperform on Fortinet, Raises Price Target to $160
analyzing news 170/372: Morgan Stanley Delivers Strong Q3 With Robust Equities Revenue, Record Wealth Flows
analyzing news 171/372: JP Morgan Maintains Neutral on Hershey, Lowers Price Target to $183
analyzing news 172/372: JP Morgan Maintains Overweight on Globe Life, Raises Price Target to $195
analyzing news 173/372: RBC Capital Maintains Sector Perform on General Dynamics, Lowers Price Target to $360
analyzing news 174/372: RBC Capital Maintains Outperform on Howmet Aerospace, Lowers Price Target to $300
analyzing news 175/372: RBC Capital Maintains Outperform on Honeywell Aerospace, Lowers Price Target to $210
analyzing news 176/372: Wells Fargo Maintains Underweight on Fortinet, Raises Price Target to $160
analyzing news 177/372: Mizuho Maintains Outperform on Hubbell, Lowers Price Target to $560
analyzing news 178/372: Mizuho Maintains Outperform on Honeywell Intl, Lowers Price Target to $255
analyzing news 179/372: Top Wall Street Forecasters Revamp Halliburton Expectations Ahead Of Q3 Earnings
analyzing news 180/372: Transcript: Howmet Aerospace Q2 2026 Earnings Conference Call
analyzing news 181/372: Nike, FMC Corp., Alcoa, Interactive Brokers and Kimberly-Clark: Why These 5 Stocks Are on Investors' Radars Today
analyzing news 182/372: JB Hunt Transport Servs Q3 2026 Earnings Call Transcript
analyzing news 183/372: Interactive Brokers Group Q3 2026 Earnings Call Transcript
analyzing news 184/372: JB Hunt Transport Servs Q3 EPS $1.82 Misses $1.95 Estimate, Sales $3.683B Beat $3.560B Estimate
analyzing news 185/372: Interactive Brokers Raises Quarterly Dividend From $0.0875 To $0.15/Share

In [39]:
fixed_articles[0]

{'author': 'Benzinga Newsdesk',
 'content': '',
 'created_at': '2026-10-15T21:07:07Z',
 'headline': "'Investors temper Anthropic IPO valuation expectations over revenue growth slowdown, sources say'- Reuters Exclusive",
 'id': 62401077,
 'images': [],
 'source': 'benzinga',
 'summary': '',
 'symbols': ['AMZN', 'GOOG', 'GOOGL', 'MSFT'],
 'updated_at': '2026-10-15T21:07:07Z',
 'url': 'https://www.benzinga.com/news/26/10/62401077/investors-temper-anthropic-ipo-valuation-expectations-over-revenue-growth-slowdown-sources-say-reute',
 'message': "HEADLINE: 'Investors temper Anthropic IPO valuation expectations over revenue growth slowdown, sources say'- Reuters Exclusive\nSUMMARY: ",
 'company_names': {'AMZN': 'Amazon.com, Inc. Common Stock',
  'GOOG': 'Alphabet Inc. Class C Capital Stock',
  'GOOGL': 'Alphabet Inc. Class A Common Stock',
  'MSFT': 'Microsoft Corporation Common Stock'}}

In [40]:
analized

[{'author': 'Benzinga Newsdesk',
  'content': '',
  'created_at': '2026-10-15T21:07:07Z',
  'headline': "'Investors temper Anthropic IPO valuation expectations over revenue growth slowdown, sources say'- Reuters Exclusive",
  'id': 62401077,
  'images': [],
  'source': 'benzinga',
  'summary': '',
  'symbols': ['AMZN', 'GOOG', 'GOOGL', 'MSFT'],
  'updated_at': '2026-10-15T21:07:07Z',
  'url': 'https://www.benzinga.com/news/26/10/62401077/investors-temper-anthropic-ipo-valuation-expectations-over-revenue-growth-slowdown-sources-say-reute',
  'message': "HEADLINE: 'Investors temper Anthropic IPO valuation expectations over revenue growth slowdown, sources say'- Reuters Exclusive\nSUMMARY: ",
  'company_names': {'AMZN': 'Amazon.com, Inc. Common Stock',
   'GOOG': 'Alphabet Inc. Class C Capital Stock',
   'GOOGL': 'Alphabet Inc. Class A Common Stock',
   'MSFT': 'Microsoft Corporation Common Stock'},
  'scores': {'AMZN': 0.0, 'GOOG': 0.0, 'GOOGL': 0.0, 'MSFT': 0.0}},
 {'author': 'Benzinga Newsdesk',
  'content': '',
  'created_at': '2026-10-15T20:41:25Z',
  'headline': 'Google Rolls Out Universal Cart In U.S. Across Google Search, Gemini',
  'id': 62400507,
  'images': [],
  'source': 'benzinga',
  'summary': '',
  'symbols': ['GOOG', 'GOOGL'],
  'updated_at': '2026-10-15T20:41:25Z',
  'url': 'https://www.benzinga.com/news/26/10/62400507/google-rolls-out-universal-cart-u-s-across-google-search-gemini',
  'message': 'HEADLINE: Google Rolls Out Universal Cart In U.S. Across Google Search, Gemini\nSUMMARY: ',
  'company_names': {'GOOG': 'Alphabet Inc. Class C Capital Stock',
   'GOOGL': 'Alphabet Inc. Class A Common Stock'},
  'scores': {'GOOG': 0.0, 'GOOGL': 0.0}},
 {'author': 'Benzinga Newsdesk',
  'content': '',
  'created_at': '2026-10-15T20:40:21Z',
  'headline': '𝕏 Product Creator Allegra Jacchia Posts "We’re doubling down on video on 𝕏. Today, we\'re piloting Video Kickstart Bonus, an invite-only program that rewards creators for posting their video content here..."',
  'id': 62400487,
  'images': [],
  'source': 'benzinga',
  'summary': '',
  'symbols': ['GOOG', 'GOOGL', 'SPCX'],
  'updated_at': '2026-10-15T20:40:21Z',
  'url': 'https://www.benzinga.com/news/26/10/62400487/product-creator-allegra-jacchia-posts-we-re-doubling-down-video-today-we-re-piloting-video-kickstart',
  'message': 'HEADLINE: 𝕏 Product Creator Allegra Jacchia Posts "We’re doubling down on video on 𝕏. Today, we\'re piloting Video Kickstart Bonus, an invite-only program that rewards creators for posting their video content here..."\nSUMMARY: ',
  'company_names': {'GOOG': 'Alphabet Inc. Class C Capital Stock',
   'GOOGL': 'Alphabet Inc. Class A Common Stock',
   'SPCX': 'Space Exploration Technologies Corp. Class A Common Stock'},
  'scores': {'GOOG': 0.0, 'GOOGL': 0.0, 'SPCX': 0.0}},
 {'author': 'Benzinga Newsdesk',
  'content': '',
  'created_at': '2026-10-15T20:26:40Z',
  'headline': 'Scotiabank Initiates Coverage On APA with Sector Perform Rating, Announces Price Target of $44',
  'id': 62399951,
  'images': [],
  'source': 'benzinga',
  'summary': '',
  'symbols': ['APA'],
  'updated_at': '2026-10-15T20:26:40Z',
  'url': 'https://www.benzinga.com/news/26/10/62399951/scotiabank-initiates-coverage-apa-sector-perform-rating-announces-price-target-44',
  'message': 'HEADLINE: Scotiabank Initiates Coverage On APA with Sector Perform Rating, Announces Price Target of $44\nSUMMARY: ',
  'company_names': {'APA': 'APA Corporation Common Stock'},
  'scores': {'APA': 0.5}},
 {'author': 'Piero Cingari',
  'content': '',
  'created_at': '2026-10-15T19:43:46Z',
  'headline': 'Lam Research Stock Hits Longest Losing Streak Ever: Are There Buyers Around?',
  'id': 62398300,
  'images': [{'size': 'large',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/LAM-Research.jpg?width=2048&height=1536'},
   {'size': 'small',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/LAM-Research.jpg?width=1024&height=768'},
   {'size': 'thumb',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/LAM-Research.jpg?width=250&height=187'}],
  'source': 'benzinga',
  'summary': 'Lam Research stock is on track for a ninth straight loss, a first since 1984. Benzinga’s 22 analysts see a $346 average target and 26% upside.',
  'symbols': ['AMAT', 'KLAC', 'LRCX'],
  'updated_at': '2026-10-15T19:43:46Z',
  'url': 'https://www.benzinga.com/markets/tech/26/10/62398300/lam-research-stock-longest-losing-streak-since-1984-analyst-price-target',
  'message': 'HEADLINE: Lam Research Stock Hits Longest Losing Streak Ever: Are There Buyers Around?\nSUMMARY: Lam Research stock is on track for a ninth straight loss, a first since 1984. Benzinga’s 22 analysts see a $346 average target and 26% upside.',
  'company_names': {'AMAT': 'Applied Materials, Inc. Common Stock',
   'KLAC': 'KLA Corporation Common Stock',
   'LRCX': 'Lam Research Corporation Common Stock'},
  'scores': {'AMAT': 0.0, 'KLAC': 0.0, 'LRCX': -0.5}},
 {'author': 'The Arora Report',
  'content': '',
  'created_at': '2026-10-15T18:33:56Z',
  'headline': 'Anthropic Needs Nearly $2.7B in Additional Monthly Revenue to Reach $100B Run Rate by Year-End',
  'id': 62396265,
  'images': [{'size': 'large',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/Anthropic-Logo.jpg?width=2048&height=1536'},
   {'size': 'small',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/Anthropic-Logo.jpg?width=1024&height=768'},
   {'size': 'thumb',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/Anthropic-Logo.jpg?width=250&height=187'}],
  'source': 'benzinga',
  'summary': '\n\n\n\nPPI Spikes\n\n\n\nPlease click here for an enlarged chart of Taiwan Semiconductor Mfg. Co. Ltd. (NYSE:TSM).\n\n\n\nNote the following:\n\n\n\n\nThis article is about the big picture, not an individual stock.\xa0 The chart of TSM',
  'symbols': ['AAPL',
   'AMZN',
   'BTCUSD',
   'GOOG',
   'META',
   'MSFT',
   'NVDA',
   'QQQ',
   'SPY',
   'TSLA',
   'TSM',
   'USO'],
  'updated_at': '2026-10-15T18:37:19Z',
  'url': 'https://www.benzinga.com/Opinion/26/10/62396265/anthropic-needs-nearly-2700-million-in-additional-monthly-revenue-to-reach-100b-run-rate-by-year-end',
  'message': 'HEADLINE: Anthropic Needs Nearly $2.7B in Additional Monthly Revenue to Reach $100B Run Rate by Year-End\nSUMMARY: \nPPI Spikes\nPlease click here for an enlarged chart of Taiwan Semiconductor Mfg. Co. Ltd. (NYSE:TSM).\nNote the following:\nThis article is about the big picture, not an individual stock.\xa0 The chart of TSM',
  'company_names': {'AAPL': 'Apple Inc. Common Stock',
   'AMZN': 'Amazon.com, Inc. Common Stock',
   'BTCUSD': None,
   'GOOG': 'Alphabet Inc. Class C Capital Stock',
   'META': 'Meta Platforms, Inc. Class A Common Stock',
   'MSFT': 'Microsoft Corporation Common Stock',
   'NVDA': 'NVIDIA Corporation Common Stock',
   'QQQ': 'Invesco QQQ Trust, Series 1',
   'SPY': 'State Street SPDR S&P 500 ETF Trust',
   'TSLA': 'Tesla, Inc. Common Stock',
   'TSM': 'Taiwan Semiconductor Manufacturing Company Ltd.',
   'USO': 'United States Oil Fund, LP'},
  'scores': {'AAPL': 0.0,
   'AMZN': 0.0,
   'BTCUSD': 0.0,
   'GOOG': 0.0,
   'META': 0.0,
   'MSFT': 0.0,
   'NVDA': 0.0,
   'QQQ': 0.0,
   'SPY': 0.0,
   'TSLA': 0.0,
   'TSM': 0.0,
   'USO': 0.0}},
 {'author': 'Benzinga Newsdesk',
  'content': '',
  'created_at': '2026-10-15T18:12:35Z',
  'headline': 'Google Quantum AI Achieves 40-Fold Error Reduction In Magic State Cultivation, Advancing Practical Quantum Computing',
  'id': 62395544,
  'images': [],
  'source': 'benzinga',
  'summary': '',
  'symbols': ['GOOG', 'GOOGL'],
  'updated_at': '2026-10-15T18:12:35Z',
  'url': 'https://www.benzinga.com/news/26/10/62395544/google-quantum-ai-achieves-40-fold-error-reduction-magic-state-cultivation-advancing-practical-quant',
  'message': 'HEADLINE: Google Quantum AI Achieves 40-Fold Error Reduction In Magic State Cultivation, Advancing Practical Quantum Computing\nSUMMARY: ',
  'company_names': {'GOOG': 'Alphabet Inc. Class C Capital Stock',
   'GOOGL': 'Alphabet Inc. Class A Common Stock'},
  'scores': {'GOOG': 0.8, 'GOOGL': 0.8}},
 {'author': 'Surbhi Jain',
  'content': '',
  'created_at': '2026-10-15T18:08:14Z',
  'headline': "Google's $4 Billion Fuel-Cell Project Puts Bloom Energy's AI Power Backlog to the Test",
  'id': 62395420,
  'images': [{'size': 'large',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/Ai-Network-And-Financial-Symbols-Over-Po.jpg?width=2048&height=1536'},
   {'size': 'small',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/Ai-Network-And-Financial-Symbols-Over-Po.jpg?width=1024&height=768'},
   {'size': 'thumb',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/Ai-Network-And-Financial-Symbols-Over-Po.jpg?width=250&height=187'}],
  'source': 'benzinga',
  'summary': 'Google&#39;s 702-MW Wyoming project puts Bloom Energy&#39;s AI power demand in focus ahead of earnings. Here&#39;s what investors should watch.',
  'symbols': ['BE', 'GOOG', 'GOOGL'],
  'updated_at': '2026-10-15T18:08:14Z',
  'url': 'https://www.benzinga.com/trading-ideas/long-ideas/26/10/62395420/google-bloom-energy-ai-power',
  'message': "HEADLINE: Google's $4 Billion Fuel-Cell Project Puts Bloom Energy's AI Power Backlog to the Test\nSUMMARY: Google&#39;s 702-MW Wyoming project puts Bloom Energy&#39;s AI power demand in focus ahead of earnings. Here&#39;s what investors should watch.",
  'company_names': {'BE': 'Bloom Energy Corporation',
   'GOOG': 'Alphabet Inc. Class C Capital Stock',
   'GOOGL': 'Alphabet Inc. Class A Common Stock'},
  'scores': {'BE': 0.5, 'GOOG': 0.5, 'GOOGL': 0.5}},
 {'author': 'Chandrima Sanyal',
  'content': '',
  'created_at': '2026-10-15T18:04:31Z',
  'headline': "Michael Burry's 'Red October' Warning: Why QQQ and SMH Could Face More Pain",
  'id': 62395307,
  'images': [{'size': 'large',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/xrdDAE9HpS4rJc10535-j6448429399417680500.jpg?width=2048&height=1536'},
   {'size': 'small',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/xrdDAE9HpS4rJc10535-j6448429399417680500.jpg?width=1024&height=768'},
   {'size': 'thumb',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/xrdDAE9HpS4rJc10535-j6448429399417680500.jpg?width=250&height=187'}],
  'source': 'benzinga',
  'summary': 'Michael Burry warns of a potential market top as falling bond yields fail to lift tech stocks. Here&#39;s why QQQ and SMH ETFs face growing risks.',
  'symbols': ['AAPL',
   'AMZN',
   'DIA',
   'GOOGL',
   'META',
   'MSFT',
   'NVDA',
   'QQQ',
   'SMH',
   'SPY',
   'TSLA',
   'TSM'],
  'updated_at': '2026-10-15T18:04:31Z',
  'url': 'https://www.benzinga.com/etfs/sector-etfs/26/10/62395307/michael-burry-red-october-warning-qqq-smh-pain',
  'message': "HEADLINE: Michael Burry's 'Red October' Warning: Why QQQ and SMH Could Face More Pain\nSUMMARY: Michael Burry warns of a potential market top as falling bond yields fail to lift tech stocks. Here&#39;s why QQQ and SMH ETFs face growing risks.",
  'company_names': {'AAPL': 'Apple Inc. Common Stock',
   'AMZN': 'Amazon.com, Inc. Common Stock',
   'DIA': 'State Street SPDR Dow Jones Industrial Average ETF Trust',
   'GOOGL': 'Alphabet Inc. Class A Common Stock',
   'META': 'Meta Platforms, Inc. Class A Common Stock',
   'MSFT': 'Microsoft Corporation Common Stock',
   'NVDA': 'NVIDIA Corporation Common Stock',
   'QQQ': 'Invesco QQQ Trust, Series 1',
   'SMH': 'VanEck Semiconductor ETF',
   'SPY': 'State Street SPDR S&P 500 ETF Trust',
   'TSLA': 'Tesla, Inc. Common Stock',
   'TSM': 'Taiwan Semiconductor Manufacturing Company Ltd.'},
  'scores': {'AAPL': 0.0,
   'AMZN': 0.0,
   'DIA': 0.0,
   'GOOGL': 0.0,
   'META': 0.0,
   'MSFT': 0.0,
   'NVDA': 0.0,
   'QQQ': -0.5,
   'SMH': -0.5,
   'SPY': 0.0,
   'TSLA': 0.0,
   'TSM': 0.0}},
 {'author': 'Benzinga Newsdesk',
  'content': '',
  'created_at': '2026-10-15T17:45:58Z',
  'headline': 'Mizuho Maintains Underperform on APA, Raises Price Target to $44',
  'id': 62394729,
  'images': [],
  'source': 'benzinga',
  'summary': '',
  'symbols': ['APA'],
  'updated_at': '2026-10-15T17:45:58Z',
  'url': 'https://www.benzinga.com/news/26/10/62394729/mizuho-maintains-underperform-apa-raises-price-target-44',
  'message': 'HEADLINE: Mizuho Maintains Underperform on APA, Raises Price Target to $44\nSUMMARY: ',
  'company_names': {'APA': 'APA Corporation Common Stock'},
  'scores': {'APA': 0.0}},
 {'author': 'Benzinga Insights',
  'content': '',
  'created_at': '2026-10-15T17:35:10Z',
  'headline': '10 Consumer Discretionary Stocks Whale Activity In Today’s Session',
  'id': 62394208,
  'images': [{'size': 'large',
    'url': 'https://cdn.benzinga.com/files/images/story/2025/11/06/aggregated_options_2.jpg?width=2048&height=1536'},
   {'size': 'small',
    'url': 'https://cdn.benzinga.com/files/images/story/2025/11/06/aggregated_options_2.jpg?width=1024&height=768'},
   {'size': 'thumb',
    'url': 'https://cdn.benzinga.com/files/images/story/2025/11/06/aggregated_options_2.jpg?width=250&height=187'}],
  'source': 'benzinga',
  'summary': 'This whale alert can help traders discover the next big trading opportunities.\nWhales are entities with large sums of money and we track their transactions here at Benzinga on our options activity scanner.\nTraders often',
  'symbols': ['AMZN',
   'BBY',
   'BKNG',
   'ETSY',
   'LVS',
   'MCD',
   'MELI',
   'NKE',
   'SGI',
   'TSLA'],
  'updated_at': '2026-10-15T17:35:10Z',
  'url': 'https://www.benzinga.com/markets/options/26/10/62394208/10-consumer-discretionary-stocks-whale-activity-today-s-session',
  'message': 'HEADLINE: 10 Consumer Discretionary Stocks Whale Activity In Today’s Session\nSUMMARY: This whale alert can help traders discover the next big trading opportunities.\nWhales are entities with large sums of money and we track their transactions here at Benzinga on our options activity scanner.\nTraders often',
  'company_names': {'AMZN': 'Amazon.com, Inc. Common Stock',
   'BBY': 'Best Buy Company, Inc.',
   'BKNG': 'Booking Holdings Inc. Common Stock',
   'ETSY': 'Etsy, Inc.',
   'LVS': 'Las Vegas Sands Corp.',
   'MCD': "McDonald's Corporation",
   'MELI': 'MercadoLibre, Inc. Common Stock',
   'NKE': 'Nike, Inc.',
   'SGI': 'Somnigroup International Inc.',
   'TSLA': 'Tesla, Inc. Common Stock'},
  'scores': {'AMZN': 0.0,
   'BBY': 0.0,
   'BKNG': 0.0,
   'ETSY': 0.0,
   'LVS': 0.0,
   'MCD': 0.0,
   'MELI': 0.0,
   'NKE': 0.0,
   'SGI': 0.0,
   'TSLA': 0.0}},
 {'author': 'Benzinga Newsdesk',
  'content': '',
  'created_at': '2026-10-15T17:30:57Z',
  'headline': "'CNN And Google Strike Multiyear Partnership To Embrace Generative AI' - Variety",
  'id': 62394034,
  'images': [],
  'source': 'benzinga',
  'summary': '',
  'symbols': ['GOOG', 'GOOGL', 'SKYD'],
  'updated_at': '2026-10-15T17:30:57Z',
  'url': 'https://www.benzinga.com/news/26/10/62394034/cnn-and-google-strike-multiyear-partnership-embrace-generative-ai-variety',
  'message': "HEADLINE: 'CNN And Google Strike Multiyear Partnership To Embrace Generative AI' - Variety\nSUMMARY: ",
  'company_names': {'GOOG': 'Alphabet Inc. Class C Capital Stock',
   'GOOGL': 'Alphabet Inc. Class A Common Stock',
   'SKYD': None},
  'scores': {'GOOG': 0.8, 'GOOGL': 0.8, 'SKYD': 0.0}},
 {'author': 'Benzinga Newsdesk',
  'content': '',
  'created_at': '2026-10-15T17:30:00Z',
  'headline': 'American Express Prelim U.S. Consumer Card 30 Days Past Due Rate 1.2% As Of Sept 30, 2026; Prelim U.S. Consumer Card Net Write-Off Rate (Principal Only) 1.5% As Of Sept 30, 2026; Prelim U.S. Small Business Card Net Write-Off Rate (Principal Only) 2.1% As Of Sept 30, 2026; Prelim U.S. Small Business Card 30 Days Past Due As A % Of Total 1.4% As Of Sept 30, 2026',
  'id': 62393993,
  'images': [],
  'source': 'benzinga',
  'summary': '',
  'symbols': ['AXP'],
  'updated_at': '2026-10-15T17:30:00Z',
  'url': 'https://www.benzinga.com/news/26/10/62393993/american-express-prelim-u-s-consumer-card-30-days-past-due-rate-1-2-sept-30-2026-prelim-u-s-consumer',
  'message': 'HEADLINE: American Express Prelim U.S. Consumer Card 30 Days Past Due Rate 1.2% As Of Sept 30, 2026; Prelim U.S. Consumer Card Net Write-Off Rate (Principal Only) 1.5% As Of Sept 30, 2026; Prelim U.S. Small Business Card Net Write-Off Rate (Principal Only) 2.1% As Of Sept 30, 2026; Prelim U.S. Small Business Card 30 Days Past Due As A % Of Total 1.4% As Of Sept 30, 2026\nSUMMARY: ',
  'company_names': {'AXP': 'American Express Company'},
  'scores': {'AXP': 0.0}},
 {'author': 'Benzinga Newsdesk',
  'content': '',
  'created_at': '2026-10-15T17:26:44Z',
  'headline': 'Meta Announces Release Of Muse Spark Open, The Open Weights Version Of Muse Spark',
  'id': 62393847,
  'images': [],
  'source': 'benzinga',
  'summary': '',
  'symbols': ['AAPL', 'META', 'MSFT'],
  'updated_at': '2026-10-15T17:26:44Z',
  'url': 'https://www.benzinga.com/news/26/10/62393847/meta-announces-release-muse-spark-open-open-weights-version-muse-spark',
  'message': 'HEADLINE: Meta Announces Release Of Muse Spark Open, The Open Weights Version Of Muse Spark\nSUMMARY: ',
  'company_names': {'AAPL': 'Apple Inc. Common Stock',
   'META': 'Meta Platforms, Inc. Class A Common Stock',
   'MSFT': 'Microsoft Corporation Common Stock'},
  'scores': {'AAPL': 0.0, 'META': 0.8, 'MSFT': 0.0}},
 {'author': 'Anusuya Lahiri',
  'content': '',
  'created_at': '2026-10-15T17:17:33Z',
  'headline': 'Google Undercuts Some AI Rivals on Price as Gemini 4 Argon Reaches Enterprises',
  'id': 62393416,
  'images': [{'size': 'large',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/Alphabet-Inc.jpg?width=2048&height=1536'},
   {'size': 'small',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/Alphabet-Inc.jpg?width=1024&height=768'},
   {'size': 'thumb',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/Alphabet-Inc.jpg?width=250&height=187'}],
  'source': 'benzinga',
  'summary': 'Google parent Alphabet trades higher as analysts highlight Gemini 4 Argon competitive pricing, AI infrastructure investments, and upcoming quarterly earnings.',
  'symbols': ['GOOG', 'GOOGL', 'GTOP', 'IXP', 'JGRO', 'MSFT'],
  'updated_at': '2026-10-15T17:17:34Z',
  'url': 'https://www.benzinga.com/markets/tech/26/10/62393416/google-undercuts-some-ai-rivals-on-price-as-gemini-4-argon-reaches-enterprises',
  'message': 'HEADLINE: Google Undercuts Some AI Rivals on Price as Gemini 4 Argon Reaches Enterprises\nSUMMARY: Google parent Alphabet trades higher as analysts highlight Gemini 4 Argon competitive pricing, AI infrastructure investments, and upcoming quarterly earnings.',
  'company_names': {'GOOG': 'Alphabet Inc. Class C Capital Stock',
   'GOOGL': 'Alphabet Inc. Class A Common Stock',
   'GTOP': 'Goldman Sachs ETF Trust Goldman Sachs Technology Opportunities ETF',
   'IXP': 'iShares Global Comm Services ETF',
   'JGRO': 'JPMorgan Active Growth ETF',
   'MSFT': 'Microsoft Corporation Common Stock'},
  'scores': {'GOOG': 0.8,
   'GOOGL': 0.8,
   'GTOP': 0.3,
   'IXP': 0.1,
   'JGRO': 0.1,
   'MSFT': 0.0}},
 {'author': 'Evette Mitkov',
  'content': '',
  'created_at': '2026-10-15T17:17:06Z',
  'headline': "Adobe Stock Gains Ground Thursday: What's Happening?",
  'id': 62393394,
  'images': [{'size': 'large',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/London--Uk---April-3rd-2025-The-Adobe-Lo.jpg?width=2048&height=1536'},
   {'size': 'small',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/London--Uk---April-3rd-2025-The-Adobe-Lo.jpg?width=1024&height=768'},
   {'size': 'thumb',
    'url': 'https://cdn.benzinga.com/files/images/story/2026/10/15/London--Uk---April-3rd-2025-The-Adobe-Lo.jpg?width=250&height=187'}],
  'source': 'benzinga',

In [41]:
analized[0]

{'author': 'Benzinga Newsdesk',
 'content': '',
 'created_at': '2026-10-15T21:07:07Z',
 'headline': "'Investors temper Anthropic IPO valuation expectations over revenue growth slowdown, sources say'- Reuters Exclusive",
 'id': 62401077,
 'images': [],
 'source': 'benzinga',
 'summary': '',
 'symbols': ['AMZN', 'GOOG', 'GOOGL', 'MSFT'],
 'updated_at': '2026-10-15T21:07:07Z',
 'url': 'https://www.benzinga.com/news/26/10/62401077/investors-temper-anthropic-ipo-valuation-expectations-over-revenue-growth-slowdown-sources-say-reute',
 'message': "HEADLINE: 'Investors temper Anthropic IPO valuation expectations over revenue growth slowdown, sources say'- Reuters Exclusive\nSUMMARY: ",
 'company_names': {'AMZN': 'Amazon.com, Inc. Common Stock',
  'GOOG': 'Alphabet Inc. Class C Capital Stock',
  'GOOGL': 'Alphabet Inc. Class A Common Stock',
  'MSFT': 'Microsoft Corporation Common Stock'},
 'scores': {'AMZN': 0.0, 'GOOG': 0.0, 'GOOGL': 0.0, 'MSFT': 0.0}}

In [42]:
df_expanded = explode_scores(analized)
pd.unique(df_expanded['score'])

array([ 0.  ,  0.5 , -0.5 ,  0.8 ,  0.3 ,  0.1 ,  1.  , -0.75,  0.6 ,
       -1.  , -0.8 , -0.85, -0.7 , -0.3 ])

In [43]:


df_expanded_cleaned = clean_columns(df_expanded)

In [44]:
#create a column in df_expanded called timestamp that is a timestamp tyupe from updated_at
#df_expanded['timestamp'] = pd.to_datetime(df_expanded['updated_at'])
#df_expanded['unique_id'] = df_expanded['id'].astype(str) + '-' + df_expanded['ticker']
#df_expanded.info(verbose=True)
#df_expanded_cleaned = df_expanded[['id', 'unique_id', 'url', 'timestamp', 'ticker', 'score', 'message']]

In [45]:
#df_expanded[['id', 'unique_id', 'url', 'timestamp', 'ticker', 'score', 'message']]

In [46]:
df_expanded_cleaned.reset_index()

,index,id,unique_id,url,timestamp,ticker,score,message
0,9,62399951,62399951-APA,https://www.benzinga.com/news/26/10/62399951/s...,2026-10-15 20:26:40+00:00,APA,0.5,HEADLINE: Scotiabank Initiates Coverage On APA...
1,12,62398300,62398300-LRCX,https://www.benzinga.com/markets/tech/26/10/62...,2026-10-15 19:43:46+00:00,LRCX,-0.5,HEADLINE: Lam Research Stock Hits Longest Losi...
2,25,62395544,62395544-GOOG,https://www.benzinga.com/news/26/10/62395544/g...,2026-10-15 18:12:35+00:00,GOOG,0.8,HEADLINE: Google Quantum AI Achieves 40-Fold E...
3,26,62395544,62395544-GOOGL,https://www.benzinga.com/news/26/10/62395544/g...,2026-10-15 18:12:35+00:00,GOOGL,0.8,HEADLINE: Google Quantum AI Achieves 40-Fold E...
4,27,62395420,62395420-BE,https://www.benzinga.com/trading-ideas/long-id...,2026-10-15 18:08:14+00:00,BE,0.5,HEADLINE: Google's $4 Billion Fuel-Cell Projec...
...,...,...,...,...,...,...,...,...
376,809,62400669,62400669-WAT,https://www.benzinga.com/news/26/10/62400669/h...,2026-10-15 20:45:31+00:00,WAT,0.5,HEADLINE: Here’s How Much You Would Have Made ...
377,811,62386427,62386427-XEL,https://www.benzinga.com/news/26/10/62386427/b...,2026-10-15 14:40:59+00:00,XEL,0.5,HEADLINE: Barclays Maintains Overweight on Xce...
378,812,62386057,62386057-WDAY,https://www.benzinga.com/news/26/10/62386057/s...,2026-10-15 14:34:39+00:00,WDAY,0.3,"HEADLINE: Stifel Maintains Hold on Workday, Ra..."
379,813,62379021,62379021-WMT,https://www.benzinga.com/trading-ideas/movers/...,2026-10-15 12:33:52+00:00,WMT,0.8,HEADLINE: Why Is Walmart Stock Trading Higher ...
380,814,62375629,62375629-WMT,https://www.benzinga.com/news/26/10/62375629/d...,2026-10-15 10:30:38+00:00,WMT,0.8,HEADLINE: Deutsche Bank Upgrades Walmart to Bu...

In [47]:
db = pgsql()
db.set_table_name('newstest')
db.set_pdf(df_expanded_cleaned)
db.write_pdf_to_sql()

True

In [48]:
df_expanded_cleaned

,id,unique_id,url,timestamp,ticker,score,message
9,62399951,62399951-APA,https://www.benzinga.com/news/26/10/62399951/s...,2026-10-15 20:26:40+00:00,APA,0.5,HEADLINE: Scotiabank Initiates Coverage On APA...
12,62398300,62398300-LRCX,https://www.benzinga.com/markets/tech/26/10/62...,2026-10-15 19:43:46+00:00,LRCX,-0.5,HEADLINE: Lam Research Stock Hits Longest Losi...
25,62395544,62395544-GOOG,https://www.benzinga.com/news/26/10/62395544/g...,2026-10-15 18:12:35+00:00,GOOG,0.8,HEADLINE: Google Quantum AI Achieves 40-Fold E...
26,62395544,62395544-GOOGL,https://www.benzinga.com/news/26/10/62395544/g...,2026-10-15 18:12:35+00:00,GOOGL,0.8,HEADLINE: Google Quantum AI Achieves 40-Fold E...
27,62395420,62395420-BE,https://www.benzinga.com/trading-ideas/long-id...,2026-10-15 18:08:14+00:00,BE,0.5,HEADLINE: Google's $4 Billion Fuel-Cell Projec...
...,...,...,...,...,...,...,...
809,62400669,62400669-WAT,https://www.benzinga.com/news/26/10/62400669/h...,2026-10-15 20:45:31+00:00,WAT,0.5,HEADLINE: Here’s How Much You Would Have Made ...
811,62386427,62386427-XEL,https://www.benzinga.com/news/26/10/62386427/b...,2026-10-15 14:40:59+00:00,XEL,0.5,HEADLINE: Barclays Maintains Overweight on Xce...
812,62386057,62386057-WDAY,https://www.benzinga.com/news/26/10/62386057/s...,2026-10-15 14:34:39+00:00,WDAY,0.3,"HEADLINE: Stifel Maintains Hold on Workday, Ra..."
813,62379021,62379021-WMT,https://www.benzinga.com/trading-ideas/movers/...,2026-10-15 12:33:52+00:00,WMT,0.8,HEADLINE: Why Is Walmart Stock Trading Higher ...
814,62375629,62375629-WMT,https://www.benzinga.com/news/26/10/62375629/d...,2026-10-15 10:30:38+00:00,WMT,0.8,HEADLINE: Deutsche Bank Upgrades Walmart to Bu...